import { Track } from "./types";

export const aiDataScientistTrack: Track = {
  id: "ai-data-scientist",
  title: "AI & Data Scientist",
  description:
    "Master mathematics, statistics, experiment design, and machine learning foundations for rigorous data science research and applications.",
  icon: "Microscope",
  color: "fuchsia",
  category: "data-ai",
  modules: [
    {
      id: "ads-math",
      title: "Mathematics for Data Science",
      description: "Linear algebra, calculus, and optimization essential for ML and statistics.",
      icon: "Calculator",
      trackId: "ai-data-scientist",
      order: 1,
      lessons: [
        {
          id: "ads-math-1",
          title: "Linear Algebra Essentials",
          description: "Vectors, matrices, eigenvalues, and decompositions.",
          duration: "20 min",
          videoId: "fNk_zzaMoSs",
          videoTitle: "Essence of Linear Algebra",
          videoChannel: "3Blue1Brown",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Use NumPy to create matrices, compute dot products, and find eigenvalues.",
            validation: "np\\.dot|np\\.linalg\\.eig|numpy",
          },
        },
        {
          id: "ads-math-2",
          title: "Calculus for ML",
          description: "Derivatives, gradients, and the chain rule in optimization.",
          duration: "15 min",
          videoId: "WUvTyaaNkzM",
          videoTitle: "Essence of Calculus",
          videoChannel: "3Blue1Brown",
          hasTerminal: false,
        },
        {
          id: "ads-math-3",
          title: "Optimization Methods",
          description: "Gradient descent, convexity, and convergence.",
          duration: "15 min",
          videoId: "fNk_zzaMoSs",
          videoTitle: "Vectors - Chapter 1, Essence of linear algebra",
          videoChannel: "3Blue1Brown",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Implement gradient descent from scratch to minimize a quadratic function.",
            validation: "gradient|learning_rate|step|descent",
          },
        },
        {
          id: "ads-math-4",
          title: "Probability Theory Foundations",
          description: "Bayes' theorem, conditional probability, and random variables.",
          duration: "12 min",
          videoId: "PFDu9oVAE-g",
          videoTitle: "Eigenvectors and eigenvalues",
          videoChannel: "3Blue1Brown",
          hasTerminal: false,
        },
        {
          id: "ads-math-5",
          title: "Information Theory Basics",
          description: "Entropy, KL divergence, and cross-entropy.",
          duration: "10 min",
          videoId: "IHZwWFHWa-w",
          videoTitle: "Gradient descent, how neural networks learn",
          videoChannel: "3Blue1Brown",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Compute the entropy and KL divergence for two probability distributions in Python.",
            validation: "entropy|kl_div|log|scipy",
          },
        },
      ],
      project: {
        title: "Math Foundations Notebook",
        description: "Create a Jupyter notebook demonstrating key math concepts with visualizations.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["Linear Algebra", "Calculus", "NumPy"],
      },
    },
    {
      id: "ads-statistics",
      title: "Statistics & Probability",
      description: "Inferential statistics, distributions, and statistical modeling.",
      icon: "TrendingUp",
      trackId: "ai-data-scientist",
      order: 2,
      lessons: [
        {
          id: "ads-stat-1",
          title: "Probability Distributions",
          description: "Normal, binomial, Poisson, exponential distributions and when to use each.",
          duration: "15 min",
          videoId: "oI3hZJqXJuc",
          videoTitle: "The Normal Distribution",
          videoChannel: "StatQuest",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Generate samples from normal, binomial, and Poisson distributions and plot their histograms.",
            validation: "np\\.random|normal|binomial|poisson|hist",
          },
        },
        {
          id: "ads-stat-2",
          title: "Bayesian Statistics",
          description: "Prior, likelihood, posterior — Bayesian inference in practice.",
          duration: "15 min",
          videoId: "3OJEae7Qb_o",
          videoTitle: "Bayes Theorem",
          videoChannel: "3Blue1Brown",
          hasTerminal: false,
        },
        {
          id: "ads-stat-3",
          title: "Hypothesis Testing & p-Values",
          description: "t-tests, ANOVA, chi-square, and interpreting p-values correctly.",
          duration: "15 min",
          videoId: "9wCnvr7Xw4E",
          videoTitle: "Bayes Theorem, Clearly Explained",
          videoChannel: "StatQuest with Josh Starmer",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Perform a one-way ANOVA test on three groups of sample data using scipy.",
            validation: "f_oneway|anova|scipy\\.stats",
          },
        },
        {
          id: "ads-stat-4",
          title: "Maximum Likelihood Estimation",
          description: "MLE for parameter estimation and model fitting.",
          duration: "12 min",
          videoId: "nk2CQITm_eo",
          videoTitle: "Linear Regression, Clearly Explained",
          videoChannel: "StatQuest with Josh Starmer",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Implement MLE to estimate the parameters of a normal distribution from sample data.",
            validation: "likelihood|maximize|optimize|MLE",
          },
        },
        {
          id: "ads-stat-5",
          title: "Non-Parametric Methods",
          description: "Mann-Whitney, Kruskal-Wallis, and bootstrap methods.",
          duration: "10 min",
          videoId: "GE3JOFwTWVM",
          videoTitle: "What is Time Series Analysis?",
          videoChannel: "IBM Technology",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Statistical Inference Study",
        description: "Design and execute a statistical study with hypothesis testing on a real dataset.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["Statistics", "Hypothesis Testing", "Bayesian Inference"],
      },
    },
    {
      id: "ads-experiments",
      title: "Experiment Design & A/B Testing",
      description: "Design rigorous experiments and A/B tests for data-driven decisions.",
      icon: "FlaskConical",
      trackId: "ai-data-scientist",
      order: 3,
      lessons: [
        {
          id: "ads-exp-1",
          title: "Principles of Experiment Design",
          description: "Control groups, randomization, and sample size calculation.",
          duration: "12 min",
          videoId: "arWJoWPpOqY",
          videoTitle: "Design of experiments and A/B testing",
          videoChannel: "Leonid Zhukov",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Calculate the required sample size for an A/B test with 80% power and 5% significance.",
            validation: "sample_size|power|significance|statsmodels",
          },
        },
        {
          id: "ads-exp-2",
          title: "A/B Testing Framework",
          description: "End-to-end A/B testing: design, execution, and analysis.",
          duration: "15 min",
          videoId: "DUNk4GPZ9bw",
          videoTitle: "A/B Testing in Data Science Interviews",
          videoChannel: "DataInterview",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Simulate an A/B test for a website conversion rate and analyze results with a chi-square test.",
            validation: "chi2|conversion|control|treatment",
          },
        },
        {
          id: "ads-exp-3",
          title: "Multi-Armed Bandits",
          description: "Thompson sampling, UCB, and adaptive experimentation.",
          duration: "12 min",
          videoId: "gRkUhg9Wb-I",
          videoTitle: "Causal Inference, Part 1",
          videoChannel: "MIT OpenCourseWare",
          hasTerminal: false,
        },
        {
          id: "ads-exp-4",
          title: "Causal Inference",
          description: "Difference-in-differences, instrumental variables, and causal graphs.",
          duration: "15 min",
          videoId: "e3L4VocZnnQ",
          videoTitle: "Multi-Armed Bandit: Data Science Concepts",
          videoChannel: "ritvikmath",
          hasTerminal: false,
        },
      ],
      project: {
        title: "A/B Test Analysis",
        description: "Design, simulate, and analyze a complete A/B test with statistical rigor.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["A/B Testing", "Experiment Design", "Statistical Analysis"],
      },
    },
    {
      id: "ads-econometrics",
      title: "Econometrics & Regression",
      description: "Advanced regression techniques and econometric modeling.",
      icon: "Sigma",
      trackId: "ai-data-scientist",
      order: 4,
      lessons: [
        {
          id: "ads-econ-1",
          title: "Linear Regression Deep Dive",
          description: "OLS assumptions, diagnostics, and interpretation.",
          duration: "15 min",
          videoId: "2EhRT2mOXm8",
          videoTitle: "Whats the Difference Between Econometrics and Data Science?",
          videoChannel: "Marginal Revolution University",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Build a linear regression model with statsmodels, check residuals, and interpret coefficients.",
            validation: "OLS|statsmodels|fit|summary|residuals",
          },
        },
        {
          id: "ads-econ-2",
          title: "Logistic Regression",
          description: "Classification with logistic regression, odds ratios, and ROC curves.",
          duration: "15 min",
          videoId: "yIYKR4sgzI8",
          videoTitle: "Logistic Regression",
          videoChannel: "StatQuest",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Build a logistic regression model with scikit-learn and plot the ROC curve.",
            validation: "LogisticRegression|roc_curve|sklearn",
          },
        },
        {
          id: "ads-econ-3",
          title: "Time Series Analysis",
          description: "ARIMA, seasonality, and forecasting.",
          duration: "15 min",
          videoId: "eiffOVbYvNc",
          videoTitle: "Introduction to Differences-in-Differences",
          videoChannel: "Marginal Revolution University",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Fit an ARIMA model to a time series dataset and generate forecasts.",
            validation: "ARIMA|forecast|statsmodels|pmdarima",
          },
        },
        {
          id: "ads-econ-4",
          title: "Regularization (Ridge, Lasso, ElasticNet)",
          description: "Preventing overfitting with L1/L2 penalties.",
          duration: "12 min",
          videoId: "NLgB2WGGKUw",
          videoTitle: "Instrumental Variables - an introduction",
          videoChannel: "Ben Lambert",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Compare Ridge, Lasso, and ElasticNet regression on a dataset with many features.",
            validation: "Ridge|Lasso|ElasticNet|alpha",
          },
        },
      ],
      project: {
        title: "Predictive Modeling Report",
        description: "Build and compare multiple regression models for a real-world prediction task.",
        difficulty: "advanced",
        estimatedHours: 6,
        skills: ["Regression", "Time Series", "Model Selection"],
      },
    },
    {
      id: "ads-ml-foundations",
      title: "Machine Learning Foundations",
      description: "Core ML algorithms and practical implementation for data scientists.",
      icon: "Cpu",
      trackId: "ai-data-scientist",
      order: 5,
      lessons: [
        {
          id: "ads-ml-1",
          title: "Supervised Learning Overview",
          description: "Decision trees, random forests, SVMs, and gradient boosting.",
          duration: "15 min",
          videoId: "Gv9_4yMHFhI",
          videoTitle: "Machine Learning Course",
          videoChannel: "StatQuest",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Train a Random Forest classifier on a dataset and evaluate with accuracy and F1 score.",
            validation: "RandomForest|fit|predict|f1_score|accuracy",
          },
        },
        {
          id: "ads-ml-2",
          title: "Unsupervised Learning",
          description: "K-Means, DBSCAN, PCA, and dimensionality reduction.",
          duration: "15 min",
          videoId: "J4Wdy0Wc_xQ",
          videoTitle: "Random Forests Part 1 - Building, Using and Evaluating",
          videoChannel: "StatQuest with Josh Starmer",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Apply K-Means clustering to a dataset and visualize clusters with PCA.",
            validation: "KMeans|PCA|fit_transform|cluster",
          },
        },
        {
          id: "ads-ml-3",
          title: "Model Evaluation & Cross-Validation",
          description: "Cross-validation, confusion matrix, precision, recall, and AUC.",
          duration: "12 min",
          videoId: "aircAruvnKk",
          videoTitle: "But what is a neural network?",
          videoChannel: "3Blue1Brown",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Perform 5-fold cross-validation on a classifier and report mean accuracy with std.",
            validation: "cross_val_score|cv.*5|mean|std",
          },
        },
        {
          id: "ads-ml-4",
          title: "Feature Engineering & Selection",
          description: "Creating features, encoding, scaling, and selecting important features.",
          duration: "12 min",
          videoId: "MQ6fFDwjuco",
          videoTitle: "SHAP values for beginners",
          videoChannel: "A Data Odyssey",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Apply StandardScaler, one-hot encoding, and SelectKBest to a dataset.",
            validation: "StandardScaler|OneHotEncoder|SelectKBest|fit_transform",
          },
        },
      ],
      project: {
        title: "End-to-End ML Pipeline",
        description: "Build a complete ML pipeline from data preprocessing to model evaluation for a classification task.",
        difficulty: "advanced",
        estimatedHours: 8,
        skills: ["scikit-learn", "Feature Engineering", "Model Evaluation"],
      },
    },
  ],
};
