import { Track } from "./types";

export const aiEngineerTrack: Track = {
  id: "ai-engineer",
  title: "AI Engineer",
  description:
    "Build production AI applications with LLMs, RAG, embeddings, and AI agents. Master prompt engineering, vector databases, and AI safety.",
  icon: "Sparkles",
  color: "violet",
  category: "data-ai",
  modules: [
    {
      id: "aie-intro",
      title: "Introduction to AI Engineering",
      description: "Understand the AI engineering landscape, tools, and career paths.",
      icon: "BookOpen",
      trackId: "ai-engineer",
      order: 1,
      lessons: [
        {
          id: "aie-intro-1",
          title: "What is AI Engineering?",
          description: "The role of an AI engineer vs data scientist vs ML engineer.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "aie-intro-2",
          title: "AI Engineering Landscape",
          description: "Overview of LLMs, foundation models, and the modern AI stack.",
          duration: "12 min",
          videoId: "5sLYAQS9sWQ",
          videoTitle: "How AI Works",
          videoChannel: "Fireship",
          hasTerminal: false,
        },
        {
          id: "aie-intro-3",
          title: "Setting Up Your AI Dev Environment",
          description: "Python, API keys, virtual environments, and essential tools.",
          duration: "10 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Create a Python virtual environment and install openai, langchain, and chromadb packages.",
            validation: "pip install|venv|openai|langchain",
          },
        },
      ],
      project: {
        title: "AI Tool Survey",
        description: "Research and compare 5 AI platforms/tools and present findings.",
        difficulty: "beginner",
        estimatedHours: 2,
        skills: ["Research", "AI Landscape"],
      },
    },
    {
      id: "aie-llm-fundamentals",
      title: "LLM Fundamentals",
      description: "Understand how Large Language Models work under the hood.",
      icon: "Brain",
      trackId: "ai-engineer",
      order: 2,
      lessons: [
        {
          id: "aie-llm-1",
          title: "How LLMs Work",
          description: "Transformer architecture, tokenization, and attention mechanisms.",
          duration: "15 min",
          videoId: "zjkBMFhNj_g",
          videoTitle: "Intro to Large Language Models",
          videoChannel: "Andrej Karpathy",
          hasTerminal: false,
        },
        {
          id: "aie-llm-2",
          title: "Tokenization Deep Dive",
          description: "BPE, SentencePiece, and understanding token limits.",
          duration: "12 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Use the tiktoken library to tokenize a sentence and count the tokens.",
            validation: "tiktoken|encode|tokens",
          },
        },
        {
          id: "aie-llm-3",
          title: "Model Families & Capabilities",
          description: "GPT, Claude, Llama, Gemini — capabilities and trade-offs.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "aie-llm-4",
          title: "Fine-Tuning vs In-Context Learning",
          description: "When to fine-tune, when to prompt, and when to use RAG.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "aie-llm-5",
          title: "Open Source vs Closed Source Models",
          description: "Comparing open-source (Llama, Mistral) with proprietary models.",
          duration: "10 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Model Comparison Report",
        description: "Compare 3 different LLMs on the same set of tasks and document quality, latency, and cost.",
        difficulty: "beginner",
        estimatedHours: 3,
        skills: ["LLMs", "Benchmarking", "Technical Writing"],
      },
    },
    {
      id: "aie-openai",
      title: "OpenAI Platform & API",
      description: "Master the OpenAI API for building production AI features.",
      icon: "Zap",
      trackId: "ai-engineer",
      order: 3,
      lessons: [
        {
          id: "aie-api-1",
          title: "OpenAI API Basics",
          description: "Authentication, chat completions, and API parameters.",
          duration: "15 min",
          videoId: "uRQH2CFvedY",
          videoTitle: "OpenAI API Tutorial",
          videoChannel: "freeCodeCamp",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a Python script that calls the OpenAI chat completions API with a system and user message.",
            validation: "openai|chat\\.completions|messages",
          },
        },
        {
          id: "aie-api-2",
          title: "Function Calling & Tool Use",
          description: "Structured outputs and function calling with the API.",
          duration: "15 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Define a function schema for a weather API and use OpenAI function calling.",
            validation: "functions|function_call|tools",
          },
        },
        {
          id: "aie-api-3",
          title: "Streaming & Error Handling",
          description: "Stream responses, handle rate limits, and implement retries.",
          duration: "12 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Implement streaming chat completions with proper error handling and retry logic.",
            validation: "stream.*True|for.*chunk|retry|except",
          },
        },
        {
          id: "aie-api-4",
          title: "Vision & Multimodal APIs",
          description: "Using GPT-4V for image understanding and multimodal tasks.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "aie-api-5",
          title: "Cost Optimization",
          description: "Token counting, model selection, and caching strategies.",
          duration: "10 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "AI-Powered CLI Tool",
        description: "Build a command-line tool that uses the OpenAI API for a practical task.",
        difficulty: "intermediate",
        estimatedHours: 4,
        skills: ["OpenAI API", "Python", "CLI"],
      },
    },
    {
      id: "aie-prompting",
      title: "Prompt Engineering",
      description: "Master the art and science of crafting effective prompts.",
      icon: "MessageSquare",
      trackId: "ai-engineer",
      order: 4,
      lessons: [
        {
          id: "aie-prompt-1",
          title: "Prompt Engineering Fundamentals",
          description: "Zero-shot, few-shot, and chain-of-thought prompting.",
          duration: "12 min",
          videoId: "_ZvnD96BVzI",
          videoTitle: "Prompt Engineering Tutorial",
          videoChannel: "freeCodeCamp",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a few-shot prompt that classifies customer reviews as positive, negative, or neutral.",
            validation: "positive|negative|neutral|example|few.shot",
          },
        },
        {
          id: "aie-prompt-2",
          title: "System Prompts & Personas",
          description: "Designing effective system prompts for consistent behavior.",
          duration: "10 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Create a system prompt that makes an LLM act as a SQL expert that responds only with SQL queries.",
            validation: "system|role|SQL",
          },
        },
        {
          id: "aie-prompt-3",
          title: "Structured Output & JSON Mode",
          description: "Getting reliable structured data from LLMs.",
          duration: "12 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a prompt that extracts structured JSON data (name, date, amount) from invoice text.",
            validation: "json|JSON|structured|extract",
          },
        },
        {
          id: "aie-prompt-4",
          title: "Prompt Chaining & Decomposition",
          description: "Breaking complex tasks into sequential prompt chains.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "aie-prompt-5",
          title: "Evaluation & Testing Prompts",
          description: "Measuring prompt quality and building evaluation datasets.",
          duration: "10 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Prompt Library",
        description: "Build a library of 10 reusable, tested prompts for common tasks with evaluation metrics.",
        difficulty: "intermediate",
        estimatedHours: 4,
        skills: ["Prompt Engineering", "Evaluation", "LLMs"],
      },
    },
    {
      id: "aie-embeddings",
      title: "Embeddings & Vector Databases",
      description: "Understand embeddings and use vector databases for semantic search.",
      icon: "Boxes",
      trackId: "ai-engineer",
      order: 5,
      lessons: [
        {
          id: "aie-embed-1",
          title: "What Are Embeddings?",
          description: "Vector representations, similarity metrics, and embedding models.",
          duration: "12 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Generate embeddings for 3 sentences using OpenAI's embedding API and compute cosine similarity.",
            validation: "embeddings|cosine|similarity|openai",
          },
        },
        {
          id: "aie-embed-2",
          title: "Vector Databases (Pinecone, ChromaDB)",
          description: "Storing, indexing, and querying vector embeddings.",
          duration: "15 min",
          videoId: "dN0lsF2cvm4",
          videoTitle: "Vector Databases Explained",
          videoChannel: "Fireship",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Set up a ChromaDB collection, add documents with embeddings, and perform a similarity search.",
            validation: "chromadb|collection|add|query",
          },
        },
        {
          id: "aie-embed-3",
          title: "Chunking Strategies",
          description: "Splitting documents for optimal embedding and retrieval.",
          duration: "10 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Implement a recursive text splitter that chunks a document by paragraphs with overlap.",
            validation: "chunk|split|overlap|RecursiveCharacterTextSplitter",
          },
        },
        {
          id: "aie-embed-4",
          title: "Hybrid Search",
          description: "Combining keyword and semantic search for better results.",
          duration: "10 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Semantic Document Search",
        description: "Build a semantic search engine over a collection of documents using embeddings and ChromaDB.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["Embeddings", "Vector DB", "Semantic Search"],
      },
    },
    {
      id: "aie-rag",
      title: "RAG (Retrieval-Augmented Generation)",
      description: "Build RAG pipelines that ground LLM responses in your data.",
      icon: "FileSearch",
      trackId: "ai-engineer",
      order: 6,
      lessons: [
        {
          id: "aie-rag-1",
          title: "RAG Architecture",
          description: "End-to-end RAG pipeline: ingest, embed, store, retrieve, generate.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "aie-rag-2",
          title: "Building a Basic RAG Pipeline",
          description: "Implement RAG with LangChain, ChromaDB, and OpenAI.",
          duration: "20 min",
          videoId: "tcqEUSNCn8I",
          videoTitle: "RAG Tutorial",
          videoChannel: "freeCodeCamp",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Build a RAG pipeline that loads a PDF, chunks it, stores embeddings, and answers questions.",
            validation: "load|chunk|embed|retrieve|chain",
          },
        },
        {
          id: "aie-rag-3",
          title: "Advanced RAG Techniques",
          description: "Re-ranking, query rewriting, parent-child retrieval, and multi-query RAG.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "aie-rag-4",
          title: "Evaluating RAG Systems",
          description: "Measuring retrieval precision, answer quality, and hallucination rates.",
          duration: "12 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "RAG-Powered Q&A Bot",
        description: "Build a question-answering chatbot that answers from your own documents with citations.",
        difficulty: "advanced",
        estimatedHours: 6,
        skills: ["RAG", "LangChain", "Vector DB", "LLMs"],
      },
    },
    {
      id: "aie-agents",
      title: "AI Agents",
      description: "Build autonomous AI agents that can reason, plan, and use tools.",
      icon: "Bot",
      trackId: "ai-engineer",
      order: 7,
      lessons: [
        {
          id: "aie-agent-1",
          title: "What Are AI Agents?",
          description: "ReAct pattern, tool use, and the agent loop.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "aie-agent-2",
          title: "Building Agents with LangChain",
          description: "Create agents that can search the web, run code, and query databases.",
          duration: "20 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Build a LangChain agent with a calculator tool and a search tool that can answer complex questions.",
            validation: "Agent|tool|create_react_agent|AgentExecutor",
          },
        },
        {
          id: "aie-agent-3",
          title: "Multi-Agent Systems",
          description: "Coordinating multiple specialized agents for complex tasks.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "aie-agent-4",
          title: "Agent Memory & State",
          description: "Short-term and long-term memory patterns for persistent agents.",
          duration: "12 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Research Agent",
        description: "Build an AI agent that can research a topic, summarize findings, and generate a report.",
        difficulty: "advanced",
        estimatedHours: 6,
        skills: ["AI Agents", "LangChain", "Tool Use", "LLMs"],
      },
    },
    {
      id: "aie-safety",
      title: "AI Safety & Ethics",
      description: "Build responsible AI applications with safety guardrails.",
      icon: "ShieldCheck",
      trackId: "ai-engineer",
      order: 8,
      lessons: [
        {
          id: "aie-safe-1",
          title: "AI Safety Fundamentals",
          description: "Prompt injection, jailbreaking, and adversarial attacks.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "aie-safe-2",
          title: "Guardrails & Content Filtering",
          description: "Implementing input/output filters and safety layers.",
          duration: "12 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Implement a simple guardrail that checks LLM output for harmful content before returning it.",
            validation: "filter|guard|check|moderate|safety",
          },
        },
        {
          id: "aie-safe-3",
          title: "Bias, Fairness & Responsible AI",
          description: "Understanding and mitigating bias in AI systems.",
          duration: "10 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Safe AI Application",
        description: "Add comprehensive safety guardrails to an existing AI application.",
        difficulty: "intermediate",
        estimatedHours: 4,
        skills: ["AI Safety", "Guardrails", "Ethics"],
      },
    },
  ],
};
