import { Track } from "./types";

export const androidTrack: Track = {
  id: "android",
  title: "Android Developer",
  description:
    "Build native Android applications with Kotlin. Master Jetpack Compose, architecture patterns, data persistence, networking, and publishing to the Play Store.",
  icon: "Smartphone",
  color: "green",
  category: "mobile",
  modules: [
    {
      id: "and-intro",
      title: "Android Fundamentals",
      description: "Getting started with Android development and Kotlin.",
      icon: "BookOpen",
      trackId: "android",
      order: 1,
      lessons: [
        {
          id: "and-intro-1",
          title: "Android Development Overview",
          description: "The Android ecosystem, platform architecture, and tooling.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "and-intro-2",
          title: "Setting Up Android Studio",
          description: "Install Android Studio, configure SDK, and run your first app.",
          duration: "15 min",
          videoId: "fis26HvvDII",
          videoTitle: "Android Development Full Course",
          videoChannel: "freeCodeCamp",
          hasTerminal: false,
        },
        {
          id: "and-intro-3",
          title: "Project Structure & Gradle",
          description: "Understanding Android project layout, manifests, and build system.",
          duration: "10 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Hello Android",
        description: "Create your first Android app that displays a greeting and responds to button taps.",
        difficulty: "beginner",
        estimatedHours: 2,
        skills: ["Android Studio", "Project Setup"],
      },
    },
    {
      id: "and-kotlin",
      title: "Kotlin Programming",
      description: "Kotlin language fundamentals for Android development.",
      icon: "Code",
      trackId: "android",
      order: 2,
      lessons: [
        {
          id: "and-kt-1",
          title: "Kotlin Basics",
          description: "Variables, types, control flow, functions, and null safety.",
          duration: "15 min",
          videoId: "F9UC9DY-vIU",
          videoTitle: "Kotlin Course",
          videoChannel: "freeCodeCamp",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a Kotlin function that takes a nullable String and returns its length or -1 if null.",
            validation: "fun.*String\\?|\\?\\.|\\?:",
          },
        },
        {
          id: "and-kt-2",
          title: "Object-Oriented Kotlin",
          description: "Classes, inheritance, interfaces, data classes, and sealed classes.",
          duration: "15 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Create a sealed class hierarchy for UI states (Loading, Success, Error) with data.",
            validation: "sealed class|data class|object",
          },
        },
        {
          id: "and-kt-3",
          title: "Functional Kotlin",
          description: "Lambdas, higher-order functions, collections, and extension functions.",
          duration: "15 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Use Kotlin collection operations (map, filter, groupBy) to process a list of items.",
            validation: "map|filter|groupBy|let|apply",
          },
        },
        {
          id: "and-kt-4",
          title: "Coroutines",
          description: "Asynchronous programming with Kotlin coroutines.",
          duration: "15 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a coroutine that fetches data from two sources concurrently using async/await.",
            validation: "suspend|coroutineScope|async|await|launch",
          },
        },
      ],
      project: {
        title: "Kotlin Exercises",
        description: "Complete a series of Kotlin challenges covering all core concepts.",
        difficulty: "beginner",
        estimatedHours: 3,
        skills: ["Kotlin", "Coroutines", "OOP"],
      },
    },
    {
      id: "and-compose",
      title: "Jetpack Compose",
      description: "Build modern UIs with Jetpack Compose declarative framework.",
      icon: "Layout",
      trackId: "android",
      order: 3,
      lessons: [
        {
          id: "and-comp-1",
          title: "Compose Fundamentals",
          description: "Composable functions, modifiers, state, and recomposition.",
          duration: "20 min",
          videoId: "cDabx3SjuOY",
          videoTitle: "Jetpack Compose Course",
          videoChannel: "Philipp Lackner",
          hasTerminal: false,
        },
        {
          id: "and-comp-2",
          title: "Layouts in Compose",
          description: "Row, Column, Box, LazyColumn, and custom layouts.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "and-comp-3",
          title: "State Management in Compose",
          description: "remember, mutableStateOf, state hoisting, and ViewModel integration.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "and-comp-4",
          title: "Theming & Material Design 3",
          description: "Material 3 components, dynamic color, and custom themes.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "and-comp-5",
          title: "Animations in Compose",
          description: "AnimatedVisibility, animate*AsState, and transition animations.",
          duration: "12 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Compose UI Showcase",
        description: "Build a multi-screen app showcasing various Compose components and animations.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["Jetpack Compose", "Material 3", "Animations"],
      },
    },
    {
      id: "and-architecture",
      title: "App Architecture",
      description: "MVVM, Clean Architecture, and Android architecture components.",
      icon: "Layers",
      trackId: "android",
      order: 4,
      lessons: [
        {
          id: "and-arch-1",
          title: "MVVM Pattern",
          description: "Model-View-ViewModel pattern and ViewModel class.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "and-arch-2",
          title: "Repository Pattern",
          description: "Abstracting data sources with the repository pattern.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "and-arch-3",
          title: "Dependency Injection with Hilt",
          description: "Setting up Hilt for dependency injection in Android.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "and-arch-4",
          title: "Clean Architecture",
          description: "Layered architecture: data, domain, and presentation layers.",
          duration: "12 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Well-Architected App",
        description: "Refactor a simple app to follow MVVM + Clean Architecture with Hilt.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["MVVM", "Clean Architecture", "Hilt"],
      },
    },
    {
      id: "and-navigation",
      title: "Navigation",
      description: "Navigate between screens with Jetpack Navigation and Compose Navigation.",
      icon: "Route",
      trackId: "android",
      order: 5,
      lessons: [
        {
          id: "and-nav-1",
          title: "Compose Navigation Basics",
          description: "NavHost, NavController, routes, and passing arguments.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "and-nav-2",
          title: "Bottom Navigation & Tabs",
          description: "Bottom bars, tab rows, and nested navigation graphs.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "and-nav-3",
          title: "Deep Links & Type-Safe Navigation",
          description: "Type-safe routes with Kotlin serialization and deep linking.",
          duration: "10 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Multi-Screen Navigation App",
        description: "Build an app with bottom navigation, nested graphs, and deep link support.",
        difficulty: "intermediate",
        estimatedHours: 4,
        skills: ["Navigation", "Compose", "Deep Links"],
      },
    },
    {
      id: "and-data",
      title: "Data Persistence",
      description: "Store data locally with Room, DataStore, and SQLite.",
      icon: "Database",
      trackId: "android",
      order: 6,
      lessons: [
        {
          id: "and-data-1",
          title: "Room Database",
          description: "Entities, DAOs, database class, and migrations.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "and-data-2",
          title: "DataStore & Preferences",
          description: "Proto DataStore and Preferences DataStore for key-value storage.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "and-data-3",
          title: "Room with Flow & Coroutines",
          description: "Reactive data queries with Flow and coroutines.",
          duration: "12 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Offline-First App",
        description: "Build a note-taking app with Room database and offline support.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["Room", "DataStore", "Offline-First"],
      },
    },
    {
      id: "and-network",
      title: "Networking",
      description: "Make API calls with Retrofit, Ktor, and handle network state.",
      icon: "Globe",
      trackId: "android",
      order: 7,
      lessons: [
        {
          id: "and-net-1",
          title: "Retrofit & OkHttp",
          description: "REST API calls, serialization, and interceptors.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "and-net-2",
          title: "Ktor Client",
          description: "Modern Kotlin HTTP client for API communication.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "and-net-3",
          title: "Error Handling & Caching",
          description: "Network error handling, retry, and response caching.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "and-net-4",
          title: "Image Loading (Coil)",
          description: "Efficient image loading and caching with Coil.",
          duration: "8 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "API-Connected App",
        description: "Build an app that fetches, displays, and caches data from a REST API.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["Retrofit", "Networking", "Caching"],
      },
    },
    {
      id: "and-testing",
      title: "Testing",
      description: "Unit tests, UI tests, and integration tests for Android.",
      icon: "TestTube",
      trackId: "android",
      order: 8,
      lessons: [
        {
          id: "and-test-1",
          title: "Unit Testing with JUnit & MockK",
          description: "Testing ViewModels, repositories, and use cases.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "and-test-2",
          title: "Compose UI Testing",
          description: "Testing composables with ComposeTestRule.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "and-test-3",
          title: "End-to-End Testing",
          description: "Full flow testing with Espresso and UI Automator.",
          duration: "10 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Test Suite",
        description: "Add comprehensive test coverage to an existing Android app.",
        difficulty: "intermediate",
        estimatedHours: 4,
        skills: ["JUnit", "MockK", "Compose Testing"],
      },
    },
    {
      id: "and-publishing",
      title: "Publishing & Distribution",
      description: "Prepare and publish apps to the Google Play Store.",
      icon: "Upload",
      trackId: "android",
      order: 9,
      lessons: [
        {
          id: "and-pub-1",
          title: "App Signing & Release Build",
          description: "ProGuard/R8, signing configs, and release builds.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "and-pub-2",
          title: "Play Store Listing",
          description: "Screenshots, descriptions, and store listing optimization.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "and-pub-3",
          title: "CI/CD for Android",
          description: "Automated builds, tests, and deployments with GitHub Actions.",
          duration: "12 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a GitHub Actions workflow that builds an Android APK and runs tests.",
            validation: "name.*Android|gradle|assembleRelease|connectedCheck",
          },
        },
      ],
      project: {
        title: "Publish-Ready App",
        description: "Prepare a complete app with signed release build and store listing.",
        difficulty: "advanced",
        estimatedHours: 4,
        skills: ["Play Store", "CI/CD", "App Signing"],
      },
    },
  ],
};
