import { Track } from "./types";

export const biAnalystTrack: Track = {
  id: "bi-analyst",
  title: "BI Analyst",
  description:
    "Turn data into business intelligence. Master SQL, BI platforms, data modeling, visualization, and storytelling to inform strategic decisions.",
  icon: "PieChart",
  color: "lime",
  category: "data-ai",
  modules: [
    {
      id: "bi-intro",
      title: "Introduction to Business Intelligence",
      description: "What BI is, its role in organizations, and the BI analyst skillset.",
      icon: "BookOpen",
      trackId: "bi-analyst",
      order: 1,
      lessons: [
        {
          id: "bi-intro-1",
          title: "What is Business Intelligence?",
          description: "BI definition, history, and the modern BI landscape.",
          duration: "10 min",
          videoId: "GJqbpi7_7CQ",
          videoTitle: "Intro to Business Intelligence",
          videoChannel: "Pragmatic Works",
          hasTerminal: false,
        },
        {
          id: "bi-intro-2",
          title: "The BI Analyst Role",
          description: "Day-to-day responsibilities, career paths, and key skills.",
          duration: "8 min",
          videoId: "Fef9Vk9fVPg",
          videoTitle: "How I'd Become a BI Analyst in 2025",
          videoChannel: "Adam Finer - Learn BI Online",
          hasTerminal: false,
        },
        {
          id: "bi-intro-3",
          title: "BI Tools & Technology Stack",
          description: "Overview of tools: Power BI, Tableau, Looker, SQL, Python.",
          duration: "10 min",
          videoId: "z4IxOU4KpMk",
          videoTitle: "7 Business Intelligence Terms Everyone Should Know",
          videoChannel: "Adam Finer - Learn BI Online",
          hasTerminal: false,
        },
      ],
      project: {
        title: "BI Landscape Research",
        description: "Research and compare 3 BI tools, documenting pros, cons, and use cases.",
        difficulty: "beginner",
        estimatedHours: 2,
        skills: ["Research", "BI Tools"],
      },
    },
    {
      id: "bi-data-types",
      title: "Types of Data Analysis",
      description: "Different analysis approaches and when to apply each.",
      icon: "BarChart",
      trackId: "bi-analyst",
      order: 2,
      lessons: [
        {
          id: "bi-types-1",
          title: "Descriptive Analytics",
          description: "Summarizing historical data — what happened?",
          duration: "10 min",
          videoId: "kbKty5ZVKMY",
          videoTitle: "Learn Basic SQL in 15 Minutes for Business Intelligence",
          videoChannel: "Adam Finer - Learn BI Online",
          hasTerminal: false,
        },
        {
          id: "bi-types-2",
          title: "Diagnostic Analytics",
          description: "Investigating root causes — why did it happen?",
          duration: "10 min",
          videoId: "yHzT_BUggQk",
          videoTitle: "Advanced Pivot Table Techniques",
          videoChannel: "Leila Gharani",
          hasTerminal: false,
        },
        {
          id: "bi-types-3",
          title: "Predictive & Prescriptive Analytics",
          description: "Forecasting and recommending actions — what will/should happen?",
          duration: "12 min",
          videoId: "CfZa1daLjwo",
          videoTitle: "Introduction to Probability Distributions",
          videoChannel: "365 Data Science",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Analysis Type Framework",
        description: "Classify 5 business questions into analysis types and propose approaches.",
        difficulty: "beginner",
        estimatedHours: 2,
        skills: ["Analytical Thinking", "Problem Framing"],
      },
    },
    {
      id: "bi-stats",
      title: "Statistics for BI",
      description: "Statistical concepts every BI analyst needs to know.",
      icon: "TrendingUp",
      trackId: "bi-analyst",
      order: 3,
      lessons: [
        {
          id: "bi-stat-1",
          title: "Descriptive Statistics",
          description: "Mean, median, mode, distributions, and percentiles.",
          duration: "12 min",
          videoId: "xxpc-HPKN28",
          videoTitle: "Statistics Fundamentals",
          videoChannel: "StatQuest",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Calculate mean, median, mode, and percentiles for a dataset using Python.",
            validation: "mean|median|mode|percentile|numpy|statistics",
          },
        },
        {
          id: "bi-stat-2",
          title: "Correlation & Trend Analysis",
          description: "Finding relationships between business metrics.",
          duration: "10 min",
          videoId: "0oc49DyA3hU",
          videoTitle: "Hypothesis Testing and The Null Hypothesis",
          videoChannel: "StatQuest with Josh Starmer",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Compute the correlation matrix for business metrics and identify strong relationships.",
            validation: "corr|correlation|heatmap|pearson",
          },
        },
        {
          id: "bi-stat-3",
          title: "Statistical Significance in Business",
          description: "When a difference matters — p-values and confidence intervals for stakeholders.",
          duration: "12 min",
          videoId: "qA-x72ju2kM",
          videoTitle: "Correlation and Regression Explained",
          videoChannel: "365 Data Science",
          hasTerminal: false,
        },
        {
          id: "bi-stat-4",
          title: "Forecasting Basics",
          description: "Simple forecasting methods: moving averages, trend lines, seasonality.",
          duration: "12 min",
          videoId: "SplCk-t1BeA",
          videoTitle: "Descriptive Statistics: FULL Tutorial",
          videoChannel: "Grad Coach",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Compute a 7-day moving average on time series sales data using Pandas.",
            validation: "rolling|mean|window|7",
          },
        },
      ],
      project: {
        title: "Business Metrics Analysis",
        description: "Analyze a set of business metrics with descriptive statistics and trend analysis.",
        difficulty: "beginner",
        estimatedHours: 3,
        skills: ["Statistics", "Python", "Business Metrics"],
      },
    },
    {
      id: "bi-data-fund",
      title: "Data Fundamentals",
      description: "Understanding data types, quality, and governance.",
      icon: "FileStack",
      trackId: "bi-analyst",
      order: 4,
      lessons: [
        {
          id: "bi-data-1",
          title: "Data Types & Structures",
          description: "Structured, semi-structured, unstructured data and common formats.",
          duration: "10 min",
          videoId: "wR0jg0eQsZA",
          videoTitle: "Database Tutorial for Beginners",
          videoChannel: "Lucid Software",
          hasTerminal: false,
        },
        {
          id: "bi-data-2",
          title: "Data Quality & Cleaning",
          description: "Identifying and resolving data quality issues.",
          duration: "12 min",
          videoId: "kbKty5ZVKMY",
          videoTitle: "Learn Basic SQL in 15 Minutes",
          videoChannel: "Adam Finer - Learn BI Online",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a Python script to check a dataset for nulls, duplicates, and inconsistent formatting.",
            validation: "isnull|duplicated|strip|lower|clean",
          },
        },
        {
          id: "bi-data-3",
          title: "Data Governance & Ethics",
          description: "Data privacy, compliance (GDPR), and ethical data use.",
          duration: "10 min",
          videoId: "k4tK2ttdSDg",
          videoTitle: "What is a Data Warehouse?",
          videoChannel: "IBM Technology",
          hasTerminal: false,
        },
        {
          id: "bi-data-4",
          title: "Data Catalogs & Documentation",
          description: "Documenting data sources, lineage, and metadata.",
          duration: "8 min",
          videoId: "OW5OgsLpDCQ",
          videoTitle: "What is ETL (Extract, Transform, Load)?",
          videoChannel: "IBM Technology",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Data Quality Report",
        description: "Audit a dataset for quality issues and produce a documented quality report.",
        difficulty: "beginner",
        estimatedHours: 3,
        skills: ["Data Quality", "Documentation"],
      },
    },
    {
      id: "bi-sql",
      title: "SQL Fundamentals",
      description: "SQL for querying, aggregating, and transforming business data.",
      icon: "Database",
      trackId: "bi-analyst",
      order: 5,
      lessons: [
        {
          id: "bi-sql-1",
          title: "SELECT, WHERE, ORDER BY",
          description: "Filtering and sorting data with basic SQL.",
          duration: "12 min",
          videoId: "HXV3zeQKqGY",
          videoTitle: "SQL Tutorial",
          videoChannel: "freeCodeCamp",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write SQL queries to filter a sales table by date range and sort by revenue.",
            validation: "SELECT.*FROM.*WHERE.*ORDER BY",
          },
        },
        {
          id: "bi-sql-2",
          title: "GROUP BY & Aggregate Functions",
          description: "Summarizing data with COUNT, SUM, AVG, and HAVING.",
          duration: "12 min",
          videoId: "xkYpNfpmbGY",
          videoTitle: "SQL Joins - Beginner to PRO Masterclass",
          videoChannel: "Chandoo",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a SQL query to find total revenue by product category, filtered by HAVING > 10000.",
            validation: "GROUP BY|SUM|HAVING",
          },
        },
        {
          id: "bi-sql-3",
          title: "JOINs for Business Data",
          description: "Combining tables to answer multi-dimensional business questions.",
          duration: "15 min",
          videoId: "7NBt0V8ebGk",
          videoTitle: "Window Functions in SQL",
          videoChannel: "Alex The Analyst",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Join orders, customers, and products tables to find top customers by category.",
            validation: "JOIN.*ON|INNER JOIN|LEFT JOIN",
          },
        },
        {
          id: "bi-sql-4",
          title: "Window Functions for BI",
          description: "Running totals, rankings, and period-over-period comparisons.",
          duration: "15 min",
          videoId: "BHwzDmr6d7s",
          videoTitle: "Secret To Optimizing SQL Queries",
          videoChannel: "ByteByteGo",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a SQL query using window functions to calculate month-over-month revenue growth.",
            validation: "OVER|PARTITION BY|LAG|ROW_NUMBER|RANK",
          },
        },
      ],
      project: {
        title: "SQL Business Analysis",
        description: "Answer 10 complex business questions using SQL on a multi-table database.",
        difficulty: "intermediate",
        estimatedHours: 4,
        skills: ["SQL", "JOINs", "Window Functions"],
      },
    },
    {
      id: "bi-eda",
      title: "Exploratory Data Analysis",
      description: "Systematic techniques for exploring and understanding business data.",
      icon: "Search",
      trackId: "bi-analyst",
      order: 6,
      lessons: [
        {
          id: "bi-eda-1",
          title: "EDA Workflow for BI",
          description: "A structured approach to exploring new datasets.",
          duration: "10 min",
          videoId: "_jmiEGZ6PIY",
          videoTitle: "Cleaning Data in Excel",
          videoChannel: "Alex The Analyst",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Load a business dataset and run .info(), .describe(), .value_counts() to understand it.",
            validation: "info\\(\\)|describe\\(\\)|value_counts",
          },
        },
        {
          id: "bi-eda-2",
          title: "Distribution Analysis",
          description: "Understanding the shape and spread of business metrics.",
          duration: "10 min",
          videoId: "Liv6eeb1VfE",
          videoTitle: "Exploratory Data Analysis in Pandas",
          videoChannel: "Alex The Analyst",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Plot histograms and box plots for key business metrics to understand distributions.",
            validation: "hist|boxplot|plt\\.|sns\\.",
          },
        },
        {
          id: "bi-eda-3",
          title: "Segmentation Analysis",
          description: "Customer, product, and geographic segmentation techniques.",
          duration: "12 min",
          videoId: "bDhvCp3_lYw",
          videoTitle: "Data Cleaning in Pandas",
          videoChannel: "Alex The Analyst",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Segment customers by total spend into tiers (low, medium, high) and analyze each.",
            validation: "pd\\.cut|qcut|segment|tier|groupby",
          },
        },
        {
          id: "bi-eda-4",
          title: "Time Series EDA",
          description: "Analyzing trends, seasonality, and anomalies in time series data.",
          duration: "12 min",
          videoId: "OW5OgsLpDCQ",
          videoTitle: "What is ETL (Extract, Transform, Load)?",
          videoChannel: "IBM Technology",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Resample daily sales to weekly/monthly and plot trends with a moving average overlay.",
            validation: "resample|rolling|plot|trend",
          },
        },
      ],
      project: {
        title: "Business Dataset EDA",
        description: "Perform a comprehensive EDA on a real business dataset and present findings.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["EDA", "Pandas", "Visualization", "Business Analysis"],
      },
    },
    {
      id: "bi-viz",
      title: "Data Visualization Fundamentals",
      description: "Principles and best practices for effective data visualization.",
      icon: "BarChart3",
      trackId: "bi-analyst",
      order: 7,
      lessons: [
        {
          id: "bi-viz-1",
          title: "Visualization Principles",
          description: "Choosing chart types, color theory, and avoiding common pitfalls.",
          duration: "12 min",
          videoId: "ZUeWXNK-9yA",
          videoTitle: "Data Visualization Crash Course",
          videoChannel: "Analyst Academy",
          hasTerminal: false,
        },
        {
          id: "bi-viz-2",
          title: "Bar, Line & Pie Charts",
          description: "When and how to use basic chart types effectively.",
          duration: "10 min",
          videoId: "TazNFzgWtgA",
          videoTitle: "Make an AMAZING Dashboard with Power BI",
          videoChannel: "Chandoo",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Create a grouped bar chart and a line chart showing sales trends using Matplotlib.",
            validation: "plt\\.bar|plt\\.plot|xlabel|ylabel|title",
          },
        },
        {
          id: "bi-viz-3",
          title: "Advanced Chart Types",
          description: "Treemaps, waterfall charts, funnel charts, and geo maps.",
          duration: "12 min",
          videoId: "fBgk_cNCnsk",
          videoTitle: "How to Choose the Best Chart for Your Data",
          videoChannel: "Maven Analytics",
          hasTerminal: false,
        },
        {
          id: "bi-viz-4",
          title: "Dashboard Design Principles",
          description: "Layout, hierarchy, interactivity, and user experience in dashboards.",
          duration: "10 min",
          videoId: "r5_34YnCmMY",
          videoTitle: "Telling Stories with Data in 3 Steps",
          videoChannel: "Harvard Business Review",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Visualization Best Practices Guide",
        description: "Create a guide with examples of good and bad visualizations for common business scenarios.",
        difficulty: "beginner",
        estimatedHours: 3,
        skills: ["Data Visualization", "Design Principles"],
      },
    },
    {
      id: "bi-platforms",
      title: "BI Platforms (Power BI, Tableau, Looker)",
      description: "Build dashboards and reports with industry BI tools.",
      icon: "LayoutDashboard",
      trackId: "bi-analyst",
      order: 8,
      lessons: [
        {
          id: "bi-plat-1",
          title: "Power BI Deep Dive",
          description: "Data connections, DAX, measures, and report building.",
          duration: "20 min",
          videoId: "3u7MQz1EyPY",
          videoTitle: "Power BI Full Course",
          videoChannel: "freeCodeCamp",
          hasTerminal: false,
        },
        {
          id: "bi-plat-2",
          title: "Tableau Deep Dive",
          description: "Calculated fields, parameters, LOD expressions, and story points.",
          duration: "20 min",
          videoId: "TPMlZxRRaBQ",
          videoTitle: "Tableau Full Course",
          videoChannel: "freeCodeCamp",
          hasTerminal: false,
        },
        {
          id: "bi-plat-3",
          title: "Looker & LookML Basics",
          description: "Looker modeling, explores, and dashboards.",
          duration: "15 min",
          videoId: "6xv1KvCMF1Q",
          videoTitle: "How to Install Tableau and Create First Visualization",
          videoChannel: "Alex The Analyst",
          hasTerminal: false,
        },
        {
          id: "bi-plat-4",
          title: "Comparing BI Platforms",
          description: "Feature comparison and choosing the right tool.",
          duration: "8 min",
          videoId: "6oFTdbrugUs",
          videoTitle: "Make an AWESOME Tableau Dashboard in 10 Minutes",
          videoChannel: "Andy Kriebel",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Multi-Platform Dashboard",
        description: "Build the same dashboard in two different BI platforms and compare the experience.",
        difficulty: "intermediate",
        estimatedHours: 6,
        skills: ["Power BI", "Tableau", "Dashboard Design"],
      },
    },
    {
      id: "bi-modeling",
      title: "Data Modeling & Warehousing",
      description: "Design data models and understand warehouse concepts for BI.",
      icon: "Boxes",
      trackId: "bi-analyst",
      order: 9,
      lessons: [
        {
          id: "bi-model-1",
          title: "Dimensional Modeling",
          description: "Star schema, snowflake schema, fact and dimension tables.",
          duration: "15 min",
          videoId: "4ePNrdxWtY0",
          videoTitle: "Learn Data Modelling and Star Schema for Power BI",
          videoChannel: "Chandoo",
          hasTerminal: false,
        },
        {
          id: "bi-model-2",
          title: "ETL/ELT for BI",
          description: "Understanding how data flows into your BI layer.",
          duration: "10 min",
          videoId: "b0yWfnb2Vbw",
          videoTitle: "Power BI DAX Tutorial for Beginners",
          videoChannel: "Pragmatic Works",
          hasTerminal: false,
        },
        {
          id: "bi-model-3",
          title: "Data Warehouse Architecture",
          description: "Modern data stack, data lakes, and lakehouses from a BI perspective.",
          duration: "12 min",
          videoId: "yFCLCtBVpDw",
          videoTitle: "DAX Patterns second edition",
          videoChannel: "SQLBI",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Dimensional Model Design",
        description: "Design a star schema for a retail business with fact and dimension tables.",
        difficulty: "intermediate",
        estimatedHours: 4,
        skills: ["Data Modeling", "Star Schema", "Dimensional Design"],
      },
    },
    {
      id: "bi-storytelling",
      title: "BI Reporting & Data Storytelling",
      description: "Communicate data insights to stakeholders effectively.",
      icon: "Presentation",
      trackId: "bi-analyst",
      order: 10,
      lessons: [
        {
          id: "bi-story-1",
          title: "Data Storytelling Framework",
          description: "Context, narrative, and visuals — the three pillars of data storytelling.",
          duration: "10 min",
          videoId: "r5_34YnCmMY",
          videoTitle: "Telling Stories with Data in 3 Steps",
          videoChannel: "Harvard Business Review",
          hasTerminal: false,
        },
        {
          id: "bi-story-2",
          title: "Building Executive Reports",
          description: "Creating concise, action-oriented reports for leadership.",
          duration: "12 min",
          videoId: "TazNFzgWtgA",
          videoTitle: "Make an AMAZING Dashboard with Power BI",
          videoChannel: "Chandoo",
          hasTerminal: false,
        },
        {
          id: "bi-story-3",
          title: "KPIs & Metrics Design",
          description: "Designing meaningful KPIs and metrics that drive decisions.",
          duration: "10 min",
          videoId: "BLxW9ZSuuVI",
          videoTitle: "The Only Power BI Portfolio Project You Need",
          videoChannel: "Mo Chen",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Data Story Presentation",
        description: "Create a data-driven presentation that tells a compelling story to a mock stakeholder audience.",
        difficulty: "intermediate",
        estimatedHours: 4,
        skills: ["Data Storytelling", "Presentation", "KPI Design"],
      },
    },
  ],
};
