import { Track } from "./types";

export const blockchainTrack: Track = {
  id: "blockchain",
  title: "Blockchain Developer",
  description:
    "Build decentralized applications on Ethereum and other blockchains. Master Solidity, smart contracts, DeFi, NFTs, and Web3 development.",
  icon: "Link",
  color: "indigo",
  category: "infrastructure",
  modules: [
    {
      id: "bc-fundamentals",
      title: "Blockchain Fundamentals",
      description: "Core concepts: distributed ledgers, consensus, and cryptography.",
      icon: "BookOpen",
      trackId: "blockchain",
      order: 1,
      lessons: [
        {
          id: "bc-fund-1",
          title: "What is Blockchain?",
          description: "Distributed ledgers, blocks, hashing, and the chain.",
          duration: "12 min",
          videoId: "qOVAbKKSH10",
          videoTitle: "Blockchain Full Course",
          videoChannel: "freeCodeCamp",
          hasTerminal: false,
        },
        {
          id: "bc-fund-2",
          title: "Consensus Mechanisms",
          description: "Proof of Work, Proof of Stake, and other consensus algorithms.",
          duration: "12 min",
          videoId: "gTfNtop9vzM",
          videoTitle: "What is a Cryptographic Hashing Function?",
          videoChannel: "Whiteboard Crypto",
          hasTerminal: false,
        },
        {
          id: "bc-fund-3",
          title: "Cryptographic Primitives",
          description: "Hash functions, digital signatures, and Merkle trees.",
          duration: "12 min",
          videoId: "3QCykHU89To",
          videoTitle: "12 Consensus Mechanisms + How they Work",
          videoChannel: "Whiteboard Crypto",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Implement SHA-256 hashing and verify a simple Merkle tree in Python.",
            validation: "hashlib|sha256|merkle|digest|hexdigest",
          },
        },
        {
          id: "bc-fund-4",
          title: "Bitcoin & Ethereum Overview",
          description: "Comparing Bitcoin and Ethereum architectures and capabilities.",
          duration: "10 min",
          videoId: "pyaIppMhuic",
          videoTitle: "What are Smart Contracts in Crypto?",
          videoChannel: "Whiteboard Crypto",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Simple Blockchain",
        description: "Implement a basic blockchain in Python with blocks, hashing, and validation.",
        difficulty: "beginner",
        estimatedHours: 4,
        skills: ["Blockchain", "Cryptography", "Python"],
      },
    },
    {
      id: "bc-ethereum",
      title: "Ethereum & EVM",
      description: "Understanding Ethereum, the EVM, accounts, and transactions.",
      icon: "Cpu",
      trackId: "blockchain",
      order: 2,
      lessons: [
        {
          id: "bc-eth-1",
          title: "Ethereum Architecture",
          description: "State machine, accounts, gas, and the EVM.",
          duration: "15 min",
          videoId: "sTOcqS4msoU",
          videoTitle: "What is the EVM? Ethereum Virtual Machine",
          videoChannel: "Whiteboard Crypto",
          hasTerminal: false,
        },
        {
          id: "bc-eth-2",
          title: "Transactions & Gas",
          description: "Transaction lifecycle, gas estimation, and EIP-1559.",
          duration: "12 min",
          videoId: "RQzuQb0dfBM",
          videoTitle: "Learn Solidity in 20 Minutes!",
          videoChannel: "Dapp University",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Use ethers.js to create and send a transaction on a test network.",
            validation: "ethers|provider|sendTransaction|gasLimit|wait",
          },
        },
        {
          id: "bc-eth-3",
          title: "Ethereum Clients & Nodes",
          description: "Running nodes, Infura, Alchemy, and RPC providers.",
          duration: "10 min",
          videoId: "8N0lLN26BIE",
          videoTitle: "How To Create a Token (Step-by-Step ERC20)",
          videoChannel: "Whiteboard Crypto",
          hasTerminal: false,
        },
        {
          id: "bc-eth-4",
          title: "Layer 2 Solutions",
          description: "Rollups (Optimistic, ZK), sidechains, and scaling solutions.",
          duration: "10 min",
          videoId: "3ehaSqwUZ0s",
          videoTitle: "What is Ethereum Gas?",
          videoChannel: "Whiteboard Crypto",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Ethereum Explorer",
        description: "Build a simple Ethereum block/transaction explorer using a provider API.",
        difficulty: "beginner",
        estimatedHours: 3,
        skills: ["Ethereum", "ethers.js", "RPC"],
      },
    },
    {
      id: "bc-solidity",
      title: "Solidity Programming",
      description: "Learn Solidity for writing smart contracts on Ethereum.",
      icon: "Code",
      trackId: "blockchain",
      order: 3,
      lessons: [
        {
          id: "bc-sol-1",
          title: "Solidity Basics",
          description: "Data types, functions, modifiers, and state variables.",
          duration: "15 min",
          videoId: "gyMwXuJrbJQ",
          videoTitle: "Solidity Full Course",
          videoChannel: "freeCodeCamp",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a Solidity contract with state variables, a constructor, and getter/setter functions.",
            validation: "pragma solidity|contract|function|public|mapping",
          },
        },
        {
          id: "bc-sol-2",
          title: "Mappings, Arrays & Structs",
          description: "Complex data structures in Solidity.",
          duration: "12 min",
          videoId: "G07mD_uYZRI",
          videoTitle: "Solidity Data Location (Storage, Memory and Calldata)",
          videoChannel: "EatTheBlocks",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Create a Solidity contract with a struct, mapping, and array for managing users.",
            validation: "struct|mapping|push|memory|storage",
          },
        },
        {
          id: "bc-sol-3",
          title: "Events & Error Handling",
          description: "Emitting events, require, revert, and custom errors.",
          duration: "10 min",
          videoId: "1Mi1ub9bIv8",
          videoTitle: "Solidity Tutorial: Error Handling",
          videoChannel: "EatTheBlocks",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a contract with events, require checks, and custom error types.",
            validation: "event|emit|require|revert|error",
          },
        },
        {
          id: "bc-sol-4",
          title: "Inheritance & Interfaces",
          description: "Contract inheritance, abstract contracts, and interfaces.",
          duration: "12 min",
          videoId: "Ck5PUwL2D6I",
          videoTitle: "Inheritance - Solidity 0.8",
          videoChannel: "Smart Contract Programmer",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Create an interface, an abstract contract, and a concrete implementation.",
            validation: "interface|abstract|override|virtual|is",
          },
        },
        {
          id: "bc-sol-5",
          title: "Gas Optimization",
          description: "Writing gas-efficient Solidity code.",
          duration: "10 min",
          videoId: "da52yRwWi1E",
          videoTitle: "Smart Contract Design Patterns",
          videoChannel: "a16z crypto",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Token Contract",
        description: "Write an ERC-20 token contract from scratch following the standard.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["Solidity", "ERC-20", "Smart Contracts"],
      },
    },
    {
      id: "bc-dev-tools",
      title: "Development Tools",
      description: "Hardhat, Foundry, testing frameworks, and deployment.",
      icon: "Wrench",
      trackId: "blockchain",
      order: 4,
      lessons: [
        {
          id: "bc-tool-1",
          title: "Hardhat Setup & Workflow",
          description: "Project setup, compilation, testing, and deployment with Hardhat.",
          duration: "15 min",
          videoId: "yD3BsYlRLA4",
          videoTitle: "Hardhat: Simple and Easy way of deploying Smart Contracts",
          videoChannel: "EatTheBlocks",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Initialize a Hardhat project, compile a contract, and run a basic test.",
            validation: "npx hardhat|compile|test|describe|it\\(",
          },
        },
        {
          id: "bc-tool-2",
          title: "Foundry & Forge",
          description: "Fast testing and deployment with Foundry's Forge toolkit.",
          duration: "12 min",
          videoId: "iz0BM1Hjuq4",
          videoTitle: "Quick Introduction to Unit Testing in Hardhat",
          videoChannel: "EatTheBlocks",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a Foundry test for a Solidity contract using forge-std assertions.",
            validation: "forge test|assertEq|function test|setUp",
          },
        },
        {
          id: "bc-tool-3",
          title: "Contract Verification & Etherscan",
          description: "Verifying and interacting with contracts on Etherscan.",
          duration: "8 min",
          videoId: "GBc3lBrXEBo",
          videoTitle: "Build and Deploy Smart Contracts using Hardhat",
          videoChannel: "Patrick Collins",
          hasTerminal: false,
        },
        {
          id: "bc-tool-4",
          title: "Testing Smart Contracts",
          description: "Unit tests, integration tests, and fuzzing for contracts.",
          duration: "15 min",
          videoId: "5Uj6uR3fp-U",
          videoTitle: "IPFS: Interplanetary file storage!",
          videoChannel: "Simply Explained",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write comprehensive tests for a token contract including edge cases and reverts.",
            validation: "expect|revertedWith|to\\.equal|balanceOf",
          },
        },
      ],
      project: {
        title: "Tested & Deployed Contract",
        description: "Build, test, and deploy a smart contract to a testnet with full test coverage.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["Hardhat", "Testing", "Deployment"],
      },
    },
    {
      id: "bc-web3",
      title: "Web3 Frontend Development",
      description: "Build dApp frontends with ethers.js, wagmi, and wallet integration.",
      icon: "Globe",
      trackId: "blockchain",
      order: 5,
      lessons: [
        {
          id: "bc-web3-1",
          title: "ethers.js & Web3 Providers",
          description: "Connecting to Ethereum, reading blockchain data, and sending transactions.",
          duration: "15 min",
          videoId: "yk7nVp5HTCk",
          videoTitle: "Master Ethers.js for Blockchain Step-by-Step",
          videoChannel: "Dapp University",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Use ethers.js to connect to a provider, read a contract's state, and call a function.",
            validation: "ethers\\.Contract|provider|abi|getBalance|call",
          },
        },
        {
          id: "bc-web3-2",
          title: "Wallet Integration (MetaMask)",
          description: "Connecting wallets, handling accounts, and chain switching.",
          duration: "12 min",
          videoId: "vZQEvKRuqfw",
          videoTitle: "The BEST way to detect Metamask in your dApp",
          videoChannel: "Dapp University",
          hasTerminal: false,
        },
        {
          id: "bc-web3-3",
          title: "wagmi & viem",
          description: "Modern React hooks for Ethereum with wagmi library.",
          duration: "12 min",
          videoId: "a0osIaAOFSE",
          videoTitle: "The Complete Guide to Full Stack Ethereum Development",
          videoChannel: "Nader Dabit",
          hasTerminal: false,
        },
        {
          id: "bc-web3-4",
          title: "IPFS & Decentralized Storage",
          description: "Storing files on IPFS and Arweave for dApps.",
          duration: "10 min",
          videoId: "JpOLhkmtOak",
          videoTitle: "Building on Ethereum with GraphQL and The Graph",
          videoChannel: "Nader Dabit",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Upload a file to IPFS using the Pinata SDK and retrieve its CID.",
            validation: "pinata|ipfs|upload|CID|hash",
          },
        },
      ],
      project: {
        title: "dApp Frontend",
        description: "Build a React frontend for a smart contract with wallet connection and transactions.",
        difficulty: "intermediate",
        estimatedHours: 6,
        skills: ["ethers.js", "wagmi", "React", "Web3"],
      },
    },
    {
      id: "bc-defi",
      title: "DeFi & Token Standards",
      description: "Decentralized finance protocols, ERC standards, and DeFi patterns.",
      icon: "Coins",
      trackId: "blockchain",
      order: 6,
      lessons: [
        {
          id: "bc-defi-1",
          title: "ERC-20 Tokens",
          description: "The ERC-20 standard, OpenZeppelin, and token economics.",
          duration: "12 min",
          videoId: "k9HYC0EJU6E",
          videoTitle: "What is DEFI? Decentralized Finance Explained",
          videoChannel: "Finematics",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Deploy an ERC-20 token using OpenZeppelin contracts.",
            validation: "ERC20|_mint|totalSupply|transfer|approve",
          },
        },
        {
          id: "bc-defi-2",
          title: "ERC-721 & ERC-1155 (NFTs)",
          description: "Non-fungible and multi-token standards.",
          duration: "12 min",
          videoId: "1PbZMudPP5E",
          videoTitle: "What is an Automated Market Maker?",
          videoChannel: "Whiteboard Crypto",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write an ERC-721 NFT contract with minting and metadata URI.",
            validation: "ERC721|tokenURI|_safeMint|_tokenId",
          },
        },
        {
          id: "bc-defi-3",
          title: "DEX & AMM Concepts",
          description: "Automated market makers, liquidity pools, and Uniswap.",
          duration: "12 min",
          videoId: "aTp9er6S73M",
          videoTitle: "Lending And Borrowing In DEFI Explained",
          videoChannel: "Finematics",
          hasTerminal: false,
        },
        {
          id: "bc-defi-4",
          title: "Flash Loans & Yield Farming",
          description: "Advanced DeFi patterns and composability.",
          duration: "10 min",
          videoId: "2bjVWclBD_s",
          videoTitle: "Code an NFT Marketplace like OpenSea",
          videoChannel: "Dapp University",
          hasTerminal: false,
        },
      ],
      project: {
        title: "DeFi Protocol",
        description: "Build a simple DeFi protocol with token staking and reward distribution.",
        difficulty: "advanced",
        estimatedHours: 8,
        skills: ["DeFi", "ERC-20", "Smart Contracts"],
      },
    },
    {
      id: "bc-security",
      title: "Smart Contract Security",
      description: "Common vulnerabilities, auditing, and secure development practices.",
      icon: "ShieldCheck",
      trackId: "blockchain",
      order: 7,
      lessons: [
        {
          id: "bc-sec-1",
          title: "Common Vulnerabilities",
          description: "Reentrancy, integer overflow, front-running, and access control.",
          duration: "15 min",
          videoId: "76So4jCysAQ",
          videoTitle: "Reentrancy Attacks - Everything You Need To Know",
          videoChannel: "EatTheBlocks",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Identify and fix a reentrancy vulnerability in a sample contract.",
            validation: "nonReentrant|ReentrancyGuard|checks-effects-interactions",
          },
        },
        {
          id: "bc-sec-2",
          title: "Auditing Tools",
          description: "Slither, Mythril, and manual audit techniques.",
          duration: "12 min",
          videoId: "Dxex3b-eMq0",
          videoTitle: "Find Smart Contract Vulnerabilities with Slither",
          videoChannel: "Smart Contract Programmer",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Run Slither on a Solidity contract and interpret the findings.",
            validation: "slither|detector|severity|finding",
          },
        },
        {
          id: "bc-sec-3",
          title: "Secure Development Patterns",
          description: "OpenZeppelin, access control, and upgradeable contracts.",
          duration: "12 min",
          videoId: "TmZ8gH-toX0",
          videoTitle: "How to Audit a Smart Contract",
          videoChannel: "Patrick Collins",
          hasTerminal: false,
        },
        {
          id: "bc-sec-4",
          title: "Upgradeable Contracts (Proxy Pattern)",
          description: "Transparent and UUPS proxy patterns for upgradeable contracts.",
          duration: "12 min",
          videoId: "bdXJmWajZRY",
          videoTitle: "Upgrading your Smart Contracts - Tutorial",
          videoChannel: "Patrick Collins",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Security Audit Report",
        description: "Perform a security audit on a set of smart contracts and produce a findings report.",
        difficulty: "advanced",
        estimatedHours: 6,
        skills: ["Security Auditing", "Slither", "Secure Patterns"],
      },
    },
  ],
};
