import { Track } from "./types";

export const dataAnalystTrack: Track = {
  id: "data-analyst",
  title: "Data Analyst",
  description:
    "Master data analysis from spreadsheets to Python. Learn to collect, clean, analyze, and visualize data to drive business decisions.",
  icon: "BarChart3",
  color: "emerald",
  category: "data-ai",
  modules: [
    {
      id: "da-intro",
      title: "Introduction to Data Analytics",
      description: "Understand the role of a data analyst and the analytics lifecycle.",
      icon: "BookOpen",
      trackId: "data-analyst",
      order: 1,
      lessons: [
        {
          id: "da-intro-1",
          title: "What is Data Analytics?",
          description: "Overview of data analytics, its importance, and career paths.",
          duration: "10 min",
          videoId: "yZvFH7B6gKI",
          videoTitle: "Data Analytics Full Course",
          videoChannel: "freeCodeCamp",
          hasTerminal: false,
        },
        {
          id: "da-intro-2",
          title: "The Analytics Lifecycle",
          description: "From data collection to insights — understanding the end-to-end process.",
          duration: "8 min",
          videoId: "Fef9Vk9fVPg",
          videoTitle: "How to Become a Data Analyst in 2025",
          videoChannel: "Adam Finer - Learn BI Online",
          hasTerminal: false,
        },
        {
          id: "da-intro-3",
          title: "Types of Data Analysis",
          description: "Descriptive, diagnostic, predictive, and prescriptive analytics.",
          duration: "10 min",
          videoId: "TdbeymTcYYE",
          videoTitle: "The Ultimate Coding Setup for Data Science",
          videoChannel: "Rob Mulla",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Analytics Case Study",
        description: "Analyze a sample business scenario and identify the type of analytics needed.",
        difficulty: "beginner",
        estimatedHours: 2,
        skills: ["Analytical Thinking", "Problem Framing"],
      },
    },
    {
      id: "da-excel",
      title: "Excel for Data Analysis",
      description: "Master spreadsheet fundamentals, formulas, pivot tables and charts.",
      icon: "Table",
      trackId: "data-analyst",
      order: 2,
      lessons: [
        {
          id: "da-excel-1",
          title: "Spreadsheet Fundamentals",
          description: "Navigating Excel/Sheets, formatting, and basic data entry.",
          duration: "12 min",
          videoId: "Vl0H-qTclOg",
          videoTitle: "Excel Full Course",
          videoChannel: "freeCodeCamp",
          hasTerminal: false,
        },
        {
          id: "da-excel-2",
          title: "Formulas & Functions",
          description: "SUM, AVERAGE, VLOOKUP, IF, COUNTIF and more.",
          duration: "15 min",
          videoId: "yHzT_BUggQk",
          videoTitle: "Advanced Pivot Table Techniques",
          videoChannel: "Leila Gharani",
          hasTerminal: false,
        },
        {
          id: "da-excel-3",
          title: "Pivot Tables",
          description: "Summarize and analyze large datasets with pivot tables.",
          duration: "12 min",
          videoId: "_jmiEGZ6PIY",
          videoTitle: "Cleaning Data in Excel",
          videoChannel: "Alex The Analyst",
          hasTerminal: false,
        },
        {
          id: "da-excel-4",
          title: "Charts & Data Visualization in Excel",
          description: "Create bar charts, line charts, and dashboards in Excel.",
          duration: "10 min",
          videoId: "F4YhfVHA2M0",
          videoTitle: "Excel Data Validation Tutorial",
          videoChannel: "Leila Gharani",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Sales Dashboard in Excel",
        description: "Build an interactive sales dashboard using pivot tables and charts.",
        difficulty: "beginner",
        estimatedHours: 3,
        skills: ["Excel", "Pivot Tables", "Data Visualization"],
      },
    },
    {
      id: "da-sql",
      title: "SQL for Data Analysis",
      description: "Write SQL queries to extract, filter, aggregate, and join data.",
      icon: "Database",
      trackId: "data-analyst",
      order: 3,
      lessons: [
        {
          id: "da-sql-1",
          title: "SQL Basics & SELECT",
          description: "SELECT, WHERE, ORDER BY, and LIMIT.",
          duration: "12 min",
          videoId: "HXV3zeQKqGY",
          videoTitle: "SQL Tutorial - Full Database Course",
          videoChannel: "freeCodeCamp",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a SQL query to select all columns from a 'customers' table where the city is 'New York'.",
            validation: "SELECT.*FROM.*customers.*WHERE.*city.*=.*'New York'",
          },
        },
        {
          id: "da-sql-2",
          title: "Aggregation Functions",
          description: "COUNT, SUM, AVG, MIN, MAX and GROUP BY.",
          duration: "15 min",
          videoId: "xkYpNfpmbGY",
          videoTitle: "SQL Joins - Beginner to PRO Masterclass",
          videoChannel: "Chandoo",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a SQL query to find the average order amount grouped by customer_id.",
            validation: "SELECT.*AVG.*GROUP BY.*customer_id",
          },
        },
        {
          id: "da-sql-3",
          title: "JOINs",
          description: "INNER JOIN, LEFT JOIN, RIGHT JOIN, and FULL OUTER JOIN.",
          duration: "15 min",
          videoId: "7NBt0V8ebGk",
          videoTitle: "Window Functions in MySQL",
          videoChannel: "Alex The Analyst",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a query joining 'orders' and 'customers' tables on customer_id.",
            validation: "JOIN.*customers.*ON.*customer_id",
          },
        },
        {
          id: "da-sql-4",
          title: "Subqueries & CTEs",
          description: "Nested queries and Common Table Expressions for complex analysis.",
          duration: "12 min",
          videoId: "qfyynHBFOsM",
          videoTitle: "SQL Data Exploration",
          videoChannel: "Alex The Analyst",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a CTE that finds customers with more than 5 orders, then select from it.",
            validation: "WITH.*AS.*SELECT.*FROM",
          },
        },
      ],
      project: {
        title: "E-commerce Data Analysis with SQL",
        description: "Query an e-commerce database to find top products, customer segments, and revenue trends.",
        difficulty: "intermediate",
        estimatedHours: 4,
        skills: ["SQL", "JOINs", "Aggregation", "CTEs"],
      },
    },
    {
      id: "da-python-basics",
      title: "Python for Data Analysis",
      description: "Learn Python fundamentals and essential libraries for data work.",
      icon: "Code",
      trackId: "data-analyst",
      order: 4,
      lessons: [
        {
          id: "da-py-1",
          title: "Python Basics",
          description: "Variables, data types, loops, functions, and conditionals.",
          duration: "15 min",
          videoId: "rfscVS0vtbw",
          videoTitle: "Learn Python - Full Course",
          videoChannel: "freeCodeCamp",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a Python function that takes a list of numbers and returns the average.",
            validation: "def.*average|sum.*len",
          },
        },
        {
          id: "da-py-2",
          title: "Working with Files",
          description: "Reading CSV, JSON, and text files in Python.",
          duration: "12 min",
          videoId: "DkjCaAMBGWM",
          videoTitle: "Learning Pandas for Data Analysis? Start Here.",
          videoChannel: "Rob Mulla",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write Python code to read a CSV file using the csv module and print each row.",
            validation: "import csv|csv.reader",
          },
        },
        {
          id: "da-py-3",
          title: "NumPy Fundamentals",
          description: "Arrays, vectorized operations, and numerical computing.",
          duration: "15 min",
          videoId: "QUT1VHiLmmI",
          videoTitle: "NumPy Full Course",
          videoChannel: "freeCodeCamp",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Create a NumPy array of 10 random integers and compute the mean and standard deviation.",
            validation: "np\\.mean|np\\.std|numpy",
          },
        },
        {
          id: "da-py-4",
          title: "Jupyter Notebooks",
          description: "Using Jupyter for interactive data analysis and documentation.",
          duration: "10 min",
          videoId: "iNEwkaYmPqY",
          videoTitle: "How I use Python as a Data Analyst",
          videoChannel: "Luke Barousse",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Python Data Processing Script",
        description: "Build a Python script that reads a dataset, computes statistics, and outputs a summary.",
        difficulty: "beginner",
        estimatedHours: 3,
        skills: ["Python", "NumPy", "File I/O"],
      },
    },
    {
      id: "da-pandas",
      title: "Data Manipulation with Pandas",
      description: "Master the Pandas library for data wrangling and analysis.",
      icon: "Table2",
      trackId: "data-analyst",
      order: 5,
      lessons: [
        {
          id: "da-pandas-1",
          title: "DataFrames & Series",
          description: "Creating, indexing, and slicing Pandas DataFrames.",
          duration: "15 min",
          videoId: "vmEHCJofslg",
          videoTitle: "Pandas Tutorial",
          videoChannel: "Keith Galli",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Create a DataFrame from a dictionary with columns: name, age, salary. Filter rows where salary > 50000.",
            validation: "pd\\.DataFrame|df\\[.*>.*50000\\]",
          },
        },
        {
          id: "da-pandas-2",
          title: "Filtering & Sorting",
          description: "Boolean indexing, query method, sort_values, and sort_index.",
          duration: "12 min",
          videoId: "DkjCaAMBGWM",
          videoTitle: "Learning Pandas for Data Analysis? Start Here.",
          videoChannel: "Rob Mulla",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Use pandas to filter a DataFrame for rows where age > 30 and sort by salary descending.",
            validation: "sort_values|ascending.*False",
          },
        },
        {
          id: "da-pandas-3",
          title: "GroupBy & Aggregation",
          description: "Group data, apply aggregate functions, and create summary tables.",
          duration: "15 min",
          videoId: "iNEwkaYmPqY",
          videoTitle: "How I use Python as a Data Analyst",
          videoChannel: "Luke Barousse",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Group a sales DataFrame by 'region' and compute total and average revenue.",
            validation: "groupby.*region|agg",
          },
        },
        {
          id: "da-pandas-4",
          title: "Merging & Joining DataFrames",
          description: "pd.merge, concat, and handling multi-table data.",
          duration: "12 min",
          videoId: "gtjxAH8uaP0",
          videoTitle: "Pandas and Python for Data Analysis by Example",
          videoChannel: "freeCodeCamp.org",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Merge two DataFrames on a common 'id' column using a left join.",
            validation: "pd\\.merge|how.*left",
          },
        },
      ],
      project: {
        title: "Customer Data Wrangling",
        description: "Clean, merge, and transform multiple CSV files into a single analysis-ready dataset.",
        difficulty: "intermediate",
        estimatedHours: 4,
        skills: ["Pandas", "Data Wrangling", "Merging"],
      },
    },
    {
      id: "da-viz",
      title: "Data Visualization",
      description: "Create impactful charts and plots with Matplotlib and Seaborn.",
      icon: "LineChart",
      trackId: "data-analyst",
      order: 6,
      lessons: [
        {
          id: "da-viz-1",
          title: "Matplotlib Basics",
          description: "Line plots, bar charts, scatter plots, and customization.",
          duration: "15 min",
          videoId: "3Xc3CA655Y4",
          videoTitle: "Matplotlib Tutorial",
          videoChannel: "freeCodeCamp",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Create a Matplotlib bar chart showing sales for 5 products.",
            validation: "plt\\.bar|matplotlib",
          },
        },
        {
          id: "da-viz-2",
          title: "Seaborn for Statistical Plots",
          description: "Heatmaps, box plots, violin plots, and pair plots with Seaborn.",
          duration: "12 min",
          videoId: "ooqXQ37XHMM",
          videoTitle: "Seaborn Is The Easier Matplotlib",
          videoChannel: "NeuralNine",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Create a Seaborn heatmap showing the correlation matrix of a DataFrame.",
            validation: "sns\\.heatmap|seaborn",
          },
        },
        {
          id: "da-viz-3",
          title: "Interactive Visualizations with Plotly",
          description: "Build interactive and web-ready charts with Plotly.",
          duration: "12 min",
          videoId: "FwjaHCVNBWA",
          videoTitle: "Power BI for Data Analytics - Full Course",
          videoChannel: "Luke Barousse",
          hasTerminal: false,
        },
        {
          id: "da-viz-4",
          title: "Choosing the Right Chart",
          description: "Best practices for selecting visualization types based on data.",
          duration: "8 min",
          videoId: "tNLp_JVipoQ",
          videoTitle: "Learn Tableau in 15 minutes",
          videoChannel: "Chandoo",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Visualization Portfolio",
        description: "Create a portfolio of 5 different visualization types from a real-world dataset.",
        difficulty: "intermediate",
        estimatedHours: 4,
        skills: ["Matplotlib", "Seaborn", "Plotly", "Data Storytelling"],
      },
    },
    {
      id: "da-cleanup",
      title: "Data Cleaning & Preprocessing",
      description: "Handle missing values, outliers, duplicates, and data quality issues.",
      icon: "Eraser",
      trackId: "data-analyst",
      order: 7,
      lessons: [
        {
          id: "da-clean-1",
          title: "Handling Missing Data",
          description: "Identifying, imputing, and dropping missing values.",
          duration: "12 min",
          videoId: "_jmiEGZ6PIY",
          videoTitle: "Cleaning Data in Excel",
          videoChannel: "Alex The Analyst",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Use Pandas to identify missing values in a DataFrame and fill them with the column mean.",
            validation: "fillna|isnull|isna|mean",
          },
        },
        {
          id: "da-clean-2",
          title: "Dealing with Duplicates",
          description: "Finding and removing duplicate records.",
          duration: "8 min",
          videoId: "bDhvCp3_lYw",
          videoTitle: "Data Cleaning in Pandas",
          videoChannel: "Alex The Analyst",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Find and remove duplicate rows from a DataFrame using Pandas.",
            validation: "duplicated|drop_duplicates",
          },
        },
        {
          id: "da-clean-3",
          title: "Outlier Detection",
          description: "IQR method, Z-scores, and visual methods for outlier detection.",
          duration: "12 min",
          videoId: "P_iMSYQnqac",
          videoTitle: "Handling Missing Data Easily Explained",
          videoChannel: "Krish Naik",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Calculate the IQR for a column and filter out outliers beyond 1.5 * IQR.",
            validation: "quantile|IQR|Q1|Q3",
          },
        },
        {
          id: "da-clean-4",
          title: "Data Type Conversion & Formatting",
          description: "Parsing dates, converting types, and standardizing formats.",
          duration: "10 min",
          videoId: "OW5OgsLpDCQ",
          videoTitle: "What is ETL (Extract, Transform, Load)?",
          videoChannel: "IBM Technology",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Convert a string column to datetime and extract the month.",
            validation: "pd\\.to_datetime|dt\\.month",
          },
        },
      ],
      project: {
        title: "Messy Data Challenge",
        description: "Clean a deliberately messy dataset with missing values, duplicates, and inconsistent formats.",
        difficulty: "intermediate",
        estimatedHours: 3,
        skills: ["Data Cleaning", "Pandas", "Quality Assurance"],
      },
    },
    {
      id: "da-bi-tools",
      title: "BI Tools (Tableau & Power BI)",
      description: "Build dashboards and reports with industry-standard BI platforms.",
      icon: "LayoutDashboard",
      trackId: "data-analyst",
      order: 8,
      lessons: [
        {
          id: "da-bi-1",
          title: "Introduction to Tableau",
          description: "Connecting data, building worksheets, and creating dashboards.",
          duration: "15 min",
          videoId: "TPMlZxRRaBQ",
          videoTitle: "Tableau Full Course",
          videoChannel: "freeCodeCamp",
          hasTerminal: false,
        },
        {
          id: "da-bi-2",
          title: "Power BI Fundamentals",
          description: "Data modeling, DAX basics, and report building in Power BI.",
          duration: "15 min",
          videoId: "3u7MQz1EyPY",
          videoTitle: "Power BI Full Course",
          videoChannel: "freeCodeCamp",
          hasTerminal: false,
        },
        {
          id: "da-bi-3",
          title: "Building Interactive Dashboards",
          description: "Filters, parameters, drill-downs, and calculated fields.",
          duration: "12 min",
          videoId: "6xv1KvCMF1Q",
          videoTitle: "How to Install Tableau and Create First Visualization",
          videoChannel: "Alex The Analyst",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Executive Dashboard",
        description: "Build a multi-page interactive dashboard in Tableau or Power BI from a real dataset.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["Tableau", "Power BI", "Dashboard Design"],
      },
    },
    {
      id: "da-statistics",
      title: "Statistics for Data Analysis",
      description: "Essential statistics concepts every data analyst needs.",
      icon: "Calculator",
      trackId: "data-analyst",
      order: 9,
      lessons: [
        {
          id: "da-stat-1",
          title: "Descriptive Statistics",
          description: "Mean, median, mode, variance, and standard deviation.",
          duration: "12 min",
          videoId: "xxpc-HPKN28",
          videoTitle: "Statistics Fundamentals",
          videoChannel: "StatQuest",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Compute mean, median, and standard deviation for a list of numbers in Python.",
            validation: "mean|median|std|statistics",
          },
        },
        {
          id: "da-stat-2",
          title: "Probability Distributions",
          description: "Normal, binomial, and Poisson distributions.",
          duration: "12 min",
          videoId: "CfZa1daLjwo",
          videoTitle: "Introduction to Probability Distributions",
          videoChannel: "365 Data Science",
          hasTerminal: false,
        },
        {
          id: "da-stat-3",
          title: "Hypothesis Testing",
          description: "t-tests, chi-square tests, and p-values.",
          duration: "15 min",
          videoId: "0oc49DyA3hU",
          videoTitle: "Hypothesis Testing",
          videoChannel: "StatQuest",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Perform a two-sample t-test using scipy.stats and interpret the p-value.",
            validation: "scipy\\.stats|ttest|p.value|pvalue",
          },
        },
        {
          id: "da-stat-4",
          title: "Correlation & Regression Basics",
          description: "Pearson correlation, simple linear regression.",
          duration: "12 min",
          videoId: "qA-x72ju2kM",
          videoTitle: "The Differences Between Correlation and Regression",
          videoChannel: "365 Data Science",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Calculate the Pearson correlation between two arrays using NumPy or scipy.",
            validation: "corrcoef|pearsonr|correlation",
          },
        },
        {
          id: "da-stat-5",
          title: "Confidence Intervals",
          description: "Understanding and computing confidence intervals.",
          duration: "10 min",
          videoId: "GE3JOFwTWVM",
          videoTitle: "What is Time Series Analysis?",
          videoChannel: "IBM Technology",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Statistical Analysis Report",
        description: "Perform a full statistical analysis on a dataset including hypothesis testing and regression.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["Statistics", "Hypothesis Testing", "Python", "scipy"],
      },
    },
    {
      id: "da-eda",
      title: "Exploratory Data Analysis",
      description: "Systematic approach to understanding datasets before modeling.",
      icon: "Search",
      trackId: "data-analyst",
      order: 10,
      lessons: [
        {
          id: "da-eda-1",
          title: "EDA Process & Techniques",
          description: "Structured approach to exploring new datasets.",
          duration: "12 min",
          videoId: "Liv6eeb1VfE",
          videoTitle: "Exploratory Data Analysis in Pandas",
          videoChannel: "Alex The Analyst",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Load a dataset with Pandas and use .info(), .describe(), and .value_counts() to explore it.",
            validation: "info\\(\\)|describe\\(\\)|value_counts",
          },
        },
        {
          id: "da-eda-2",
          title: "Univariate & Bivariate Analysis",
          description: "Analyzing single and paired variables with distributions and relationships.",
          duration: "12 min",
          videoId: "kWZEXXd2tZA",
          videoTitle: "How to Think Like a Data Analyst",
          videoChannel: "Maven Analytics",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Create a histogram and a scatter plot for two columns of a DataFrame.",
            validation: "hist|scatter|plt\\.",
          },
        },
        {
          id: "da-eda-3",
          title: "Feature Engineering for Analysis",
          description: "Creating derived columns, binning, and encoding categorical data.",
          duration: "10 min",
          videoId: "xhB-dmKmzRk",
          videoTitle: "Step By Step Process In EDA And Feature Engineering",
          videoChannel: "Krish Naik",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Create a new 'age_group' column that bins ages into categories.",
            validation: "pd\\.cut|bins|age_group",
          },
        },
      ],
      project: {
        title: "Complete EDA on a Real Dataset",
        description: "Perform an end-to-end EDA on a public dataset and present key findings.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["EDA", "Pandas", "Visualization", "Statistics"],
      },
    },
    {
      id: "da-reporting",
      title: "Reporting & Data Storytelling",
      description: "Communicate insights effectively through reports and presentations.",
      icon: "Presentation",
      trackId: "data-analyst",
      order: 11,
      lessons: [
        {
          id: "da-report-1",
          title: "Data Storytelling Principles",
          description: "Structuring narratives around data to drive action.",
          duration: "10 min",
          videoId: "lgCNTuLBMK4",
          videoTitle: "A Beginners Guide To The Data Analysis Process",
          videoChannel: "CareerFoundry",
          hasTerminal: false,
        },
        {
          id: "da-report-2",
          title: "Building Automated Reports",
          description: "Using Python to generate PDF/HTML reports with data.",
          duration: "12 min",
          videoId: "t3cAUt7sOQg",
          videoTitle: "12 Dashboard design tips for better data visualization",
          videoChannel: "Geckoboard",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a Python script that generates an HTML report with summary statistics and charts.",
            validation: "html|report|write|open",
          },
        },
        {
          id: "da-report-3",
          title: "Presenting to Stakeholders",
          description: "Best practices for presenting data insights to non-technical audiences.",
          duration: "8 min",
          videoId: "QMP858aZcow",
          videoTitle: "5 Impactful Data Science Projects For Your Portfolio",
          videoChannel: "Ken Jee",
          hasTerminal: false,
        },
      ],
      project: {
        title: "End-to-End Analysis Report",
        description: "Take a raw dataset, analyze it, and create a professional report with recommendations.",
        difficulty: "advanced",
        estimatedHours: 6,
        skills: ["Reporting", "Data Storytelling", "Python", "Visualization"],
      },
    },
  ],
};
