import { Track } from "./types";

export const devrelTrack: Track = {
  id: "devrel",
  title: "Developer Relations",
  description:
    "Bridge the gap between developers and your product. Master technical content creation, community building, developer experience, advocacy, and public speaking.",
  icon: "Megaphone",
  color: "pink",
  category: "management",
  modules: [
    {
      id: "dr-foundations",
      title: "DevRel Foundations",
      description: "What DevRel is, career paths, and core competencies.",
      icon: "BookOpen",
      trackId: "devrel",
      order: 1,
      lessons: [
        {
          id: "dr-found-1",
          title: "Introduction to Developer Relations",
          description: "What DevRel is, its mission, and how it fits in an organization.",
          duration: "10 min",
          videoId: "CN4Zzdg49VI",
          videoTitle: "Developer Relations: A Complete Guide",
          videoChannel: "Jono Bacon",
          hasTerminal: false,
        },
        {
          id: "dr-found-2",
          title: "DevRel Career Paths",
          description: "Developer Advocate, Community Manager, DevEx Engineer, and more.",
          duration: "10 min",
          videoId: "iA2SQ4OL4GU",
          videoTitle: "Developer Relations: New Career Path for Developers",
          videoChannel: "Tadas Petra",
          hasTerminal: false,
        },
        {
          id: "dr-found-3",
          title: "Measuring DevRel Impact",
          description: "KPIs, metrics, and demonstrating ROI of developer relations.",
          duration: "12 min",
          videoId: "yYMRnwnim3s",
          videoTitle: "DevRel Deep Dive: What It Is, How to Measure It",
          videoChannel: "Tejas Kumar",
          hasTerminal: false,
        },
        {
          id: "dr-found-4",
          title: "DevRel Strategy & Planning",
          description: "Building a DevRel strategy aligned with business objectives.",
          duration: "12 min",
          videoId: "ZsCFGiQKb5Q",
          videoTitle: "Developer Relations Jobs: The Complete Guide",
          videoChannel: "Jono Bacon",
          hasTerminal: false,
        },
      ],
      project: {
        title: "DevRel Strategy",
        description: "Create a DevRel strategy doc with goals, channels, KPIs, and quarterly plan.",
        difficulty: "beginner",
        estimatedHours: 4,
        skills: ["Strategy", "Planning", "Metrics"],
      },
    },
    {
      id: "dr-content",
      title: "Technical Content Creation",
      description: "Writing blogs, tutorials, guides, and documentation.",
      icon: "FileText",
      trackId: "devrel",
      order: 2,
      lessons: [
        {
          id: "dr-cont-1",
          title: "Technical Blog Writing",
          description: "Writing compelling technical blog posts that educate and engage.",
          duration: "12 min",
          videoId: "YODPgBadj80",
          videoTitle: "How to Write Technical Blog Posts",
          videoChannel: "freeCodeCamp Talks",
          hasTerminal: false,
        },
        {
          id: "dr-cont-2",
          title: "Tutorial & Guide Creation",
          description: "Building step-by-step tutorials with code samples.",
          duration: "12 min",
          videoId: "vT5pcc30Ffw",
          videoTitle: "Technical Writing Course for Beginners",
          videoChannel: "freeCodeCamp.org",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a complete tutorial in Markdown that demonstrates building a simple REST API with code snippets and explanations.",
            validation: "##|```|curl|endpoint|GET|POST|response",
          },
        },
        {
          id: "dr-cont-3",
          title: "Developer Documentation",
          description: "API docs, SDK docs, and developer portal best practices.",
          duration: "12 min",
          videoId: "0CSyIBHQy9g",
          videoTitle: "API Documentation Best Practices — Full Course",
          videoChannel: "freeCodeCamp.org",
          hasTerminal: false,
        },
        {
          id: "dr-cont-4",
          title: "Video Content & Screencasts",
          description: "Creating YouTube videos, screencasts, and live coding content.",
          duration: "10 min",
          videoId: "N6-Q2dgodLs",
          videoTitle: "How I Make Videos for Programmers",
          videoChannel: "Jeff Delaney",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Content Pipeline",
        description: "Create a content pipeline with 3 blog posts, a tutorial, and a screencast script.",
        difficulty: "intermediate",
        estimatedHours: 6,
        skills: ["Writing", "Tutorials", "Content Strategy"],
      },
    },
    {
      id: "dr-speaking",
      title: "Public Speaking & Conferences",
      description: "Conference talks, workshops, and live demos.",
      icon: "Mic",
      trackId: "devrel",
      order: 3,
      lessons: [
        {
          id: "dr-speak-1",
          title: "CFP Submissions",
          description: "Writing compelling Call for Proposals that get accepted.",
          duration: "10 min",
          videoId: "ncPeY_FR9Uw",
          videoTitle: "How to Create a Conference Talk Submission",
          videoChannel: "Jono Bacon",
          hasTerminal: false,
        },
        {
          id: "dr-speak-2",
          title: "Talk Preparation & Storytelling",
          description: "Structuring talks, building narratives, and slide design.",
          duration: "12 min",
          videoId: "wRwKWKD38g0",
          videoTitle: "8-Step Guide to Conference Tech Talk Preparation",
          videoChannel: "Beachcasts",
          hasTerminal: false,
        },
        {
          id: "dr-speak-3",
          title: "Live Demos & Workshops",
          description: "Running live coding demos and interactive workshops.",
          duration: "12 min",
          videoId: "Hfq2WsppUhI",
          videoTitle: "How to Create Technical Tutorials with Screencasting",
          videoChannel: "Donn Felker",
          hasTerminal: false,
        },
        {
          id: "dr-speak-4",
          title: "Podcasts & Livestreaming",
          description: "Guest appearances, hosting podcasts, and Twitch/YouTube live.",
          duration: "10 min",
          videoId: "7AMRfNKwuYo",
          videoTitle: "How Does Live Streaming Platform Work?",
          videoChannel: "ByteByteGo",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Conference Talk",
        description: "Prepare a complete conference talk with slides, demo, and CFP submission.",
        difficulty: "intermediate",
        estimatedHours: 6,
        skills: ["Speaking", "Presentation", "Demos"],
      },
    },
    {
      id: "dr-community",
      title: "Community Building",
      description: "Building and nurturing developer communities.",
      icon: "Users",
      trackId: "devrel",
      order: 4,
      lessons: [
        {
          id: "dr-comm-1",
          title: "Community Strategy",
          description: "Choosing platforms, setting guidelines, and community goals.",
          duration: "12 min",
          videoId: "Llse_S9pgIc",
          videoTitle: "Community Building Masterclass",
          videoChannel: "Jono Bacon",
          hasTerminal: false,
        },
        {
          id: "dr-comm-2",
          title: "Discord & Forum Management",
          description: "Running developer communities on Discord, GitHub, and forums.",
          duration: "10 min",
          videoId: "SJi469BuU6g",
          videoTitle: "30 Proven Discord Hacks for Building Communities",
          videoChannel: "Jono Bacon",
          hasTerminal: false,
        },
        {
          id: "dr-comm-3",
          title: "Ambassador & Champion Programs",
          description: "Building advocate programs and empowering community leaders.",
          duration: "10 min",
          videoId: "Rfbm2ASpyTA",
          videoTitle: "How to Launch a Successful Champion Program",
          videoChannel: "CMX",
          hasTerminal: false,
        },
        {
          id: "dr-comm-4",
          title: "Events & Meetups",
          description: "Organizing hackathons, meetups, and community events.",
          duration: "10 min",
          videoId: "SkwKOVCDGM8",
          videoTitle: "How to Meetup: Hosting and Finding Community Events",
          videoChannel: "Microsoft Developer",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Community Launch Plan",
        description: "Design a community launch plan including platform setup, guidelines, programs, and growth targets.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["Community", "Events", "Programs"],
      },
    },
    {
      id: "dr-devex",
      title: "Developer Experience (DX)",
      description: "Improving SDKs, APIs, and the developer onboarding experience.",
      icon: "Wrench",
      trackId: "devrel",
      order: 5,
      lessons: [
        {
          id: "dr-dx-1",
          title: "Developer Experience Principles",
          description: "What makes a great DX — friction, time-to-hello-world, and joy.",
          duration: "12 min",
          videoId: "lQdeWHPgoMs",
          videoTitle: "The Elements of Developer Experience Design",
          videoChannel: "DevOpsDays",
          hasTerminal: false,
        },
        {
          id: "dr-dx-2",
          title: "SDK & API Design Feedback",
          description: "Collecting developer feedback and improving APIs.",
          duration: "10 min",
          videoId: "pgcB1sA9LrY",
          videoTitle: "SDKs & Code Samples — Cornerstones of API DX",
          videoChannel: "Nordic APIs",
          hasTerminal: false,
        },
        {
          id: "dr-dx-3",
          title: "Sample Apps & Quickstarts",
          description: "Building reference apps and quickstart guides.",
          duration: "12 min",
          videoId: "5Vn4vEPQjU0",
          videoTitle: "Deliver Great Onboarding with Sample Apps",
          videoChannel: "Salesforce Developers",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Create a quickstart template in bash that scaffolds a project with configuration, dependencies, and a hello-world example.",
            validation: "#!/bin/bash|mkdir|npm init|echo|template|quickstart",
          },
        },
      ],
      project: {
        title: "DX Audit",
        description: "Audit a developer product's DX — documentation, onboarding, SDKs — and propose improvements.",
        difficulty: "intermediate",
        estimatedHours: 4,
        skills: ["DX", "API Design", "Onboarding"],
      },
    },
    {
      id: "dr-social",
      title: "Social Media & Personal Brand",
      description: "Building a developer following and personal brand.",
      icon: "Share2",
      trackId: "devrel",
      order: 6,
      lessons: [
        {
          id: "dr-soc-1",
          title: "Twitter/X, LinkedIn & Dev.to",
          description: "Building a presence on developer-focused platforms.",
          duration: "10 min",
          videoId: "BUmoPpXuw5g",
          videoTitle: "Developing Your Brand Using Twitter",
          videoChannel: "Deeper Than Tech",
          hasTerminal: false,
        },
        {
          id: "dr-soc-2",
          title: "Building in Public",
          description: "Sharing your work, learnings, and journey publicly.",
          duration: "10 min",
          videoId: "S4vOufImYpI",
          videoTitle: "Everything to Know About Building in Public",
          videoChannel: "Vensy Krishna",
          hasTerminal: false,
        },
        {
          id: "dr-soc-3",
          title: "Open Source Contributions",
          description: "Contributing to OSS as a DevRel strategy.",
          duration: "10 min",
          videoId: "CML6vfKjQss",
          videoTitle: "Contributing to Open Source Can Change Your Life",
          videoChannel: "Learn Fast Make Things",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Personal Brand Plan",
        description: "Create a 3-month personal branding strategy with content calendar and platform focus.",
        difficulty: "beginner",
        estimatedHours: 3,
        skills: ["Social Media", "Branding", "Open Source"],
      },
    },
    {
      id: "dr-tools",
      title: "DevRel Tools & Workflows",
      description: "Tools, automation, and workflows for developer relations.",
      icon: "Settings",
      trackId: "devrel",
      order: 7,
      lessons: [
        {
          id: "dr-tool-1",
          title: "DevRel Toolchain",
          description: "CMS, analytics, community tools, and content management.",
          duration: "10 min",
          videoId: "dInKN8IfxOg",
          videoTitle: "What is Developer Relations — The DevRel Data Problem",
          videoChannel: "Trevor Spires",
          hasTerminal: false,
        },
        {
          id: "dr-tool-2",
          title: "Automating DevRel Workflows",
          description: "GitHub Actions, social scheduling, and content automation.",
          duration: "10 min",
          videoId: "bS9R6aCVEzw",
          videoTitle: "n8n Will Change Your Life as a Developer",
          videoChannel: "Fireship",
          hasTerminal: false,
        },
        {
          id: "dr-tool-3",
          title: "Feedback Loops & Product Influence",
          description: "Channeling developer feedback to product teams effectively.",
          duration: "10 min",
          videoId: "ubgnSdOczXY",
          videoTitle: "Shorten the Feedback Loop: Developer Experience",
          videoChannel: "Platform Engineering",
          hasTerminal: false,
        },
      ],
      project: {
        title: "DevRel Portfolio",
        description: "Build a DevRel portfolio showcasing content, talks, community impact, and developer feedback.",
        difficulty: "advanced",
        estimatedHours: 5,
        skills: ["Portfolio", "Tools", "Automation"],
      },
    },
  ],
};
