import { Track } from "./types";

export const engineeringManagerTrack: Track = {
  id: "engineering-manager",
  title: "Engineering Manager",
  description:
    "Lead engineering teams to deliver great software. Master people management, technical leadership, hiring, performance management, and organizational design.",
  icon: "Users",
  color: "teal",
  category: "management",
  modules: [
    {
      id: "em-foundations",
      title: "Engineering Management Foundations",
      description: "Transitioning to management and core EM responsibilities.",
      icon: "BookOpen",
      trackId: "engineering-manager",
      order: 1,
      lessons: [
        {
          id: "em-found-1",
          title: "IC to Manager Transition",
          description: "Making the switch from individual contributor to engineering manager.",
          duration: "12 min",
          videoId: "MqdMr_aIrOs",
          videoTitle: "Why You Need to Transition from IC to Manager",
          videoChannel: "Dev Interrupted",
          hasTerminal: false,
        },
        {
          id: "em-found-2",
          title: "EM Roles & Responsibilities",
          description: "What engineering managers do: people, process, and technical leadership.",
          duration: "10 min",
          videoId: "5Qf5sOqRuLk",
          videoTitle: "The Most Important Engineering Manager Skills",
          videoChannel: "Exponent",
          hasTerminal: false,
        },
        {
          id: "em-found-3",
          title: "Time Management for EMs",
          description: "Calendar management, maker vs manager schedule, and delegation.",
          duration: "10 min",
          videoId: "aov1fIxydyU",
          videoTitle: "Time Management Masterclass for Engineering Managers",
          videoChannel: "Level-Up Engineering",
          hasTerminal: false,
        },
        {
          id: "em-found-4",
          title: "Building Trust & Psychological Safety",
          description: "Creating environments where teams thrive and innovate.",
          duration: "12 min",
          videoId: "IV8wCxgj5p4",
          videoTitle: "Guide to Cultivating Psychological Safety at Work",
          videoChannel: "Simon Sinek",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Management README",
        description: "Write a personal management README that communicates your working style, expectations, and values.",
        difficulty: "beginner",
        estimatedHours: 3,
        skills: ["Communication", "Self-Awareness", "Documentation"],
      },
    },
    {
      id: "em-people",
      title: "People Management",
      description: "1:1s, feedback, coaching, and career development.",
      icon: "Heart",
      trackId: "engineering-manager",
      order: 2,
      lessons: [
        {
          id: "em-people-1",
          title: "Effective 1:1 Meetings",
          description: "Running productive 1:1s that build relationships and unblock work.",
          duration: "12 min",
          videoId: "LWz57CpcSnE",
          videoTitle: "6 Tips for Productive 1:1 Meetings with Your Manager",
          videoChannel: "Jeff Su",
          hasTerminal: false,
        },
        {
          id: "em-people-2",
          title: "Giving & Receiving Feedback",
          description: "SBI model, radical candor, and creating a feedback culture.",
          duration: "12 min",
          videoId: "wtl5UrrgU8c",
          videoTitle: "The Secret to Giving Great Feedback",
          videoChannel: "TED",
          hasTerminal: false,
        },
        {
          id: "em-people-3",
          title: "Career Development & Growth Plans",
          description: "Creating growth frameworks and career ladders for ICs.",
          duration: "12 min",
          videoId: "NX6qIbflNyY",
          videoTitle: "The Truth About Career Progression",
          videoChannel: "TEDx Talks",
          hasTerminal: false,
        },
        {
          id: "em-people-4",
          title: "Performance Management",
          description: "Performance reviews, PIPs, and managing underperformance.",
          duration: "10 min",
          videoId: "XfurSDKlbmw",
          videoTitle: "Performance Review Biases and How to Counter Them",
          videoChannel: "The Pragmatic Engineer",
          hasTerminal: false,
        },
        {
          id: "em-people-5",
          title: "Mentoring & Coaching",
          description: "Coaching mindset, mentorship programs, and sponsor relationships.",
          duration: "10 min",
          videoId: "TChiE1FDXdY",
          videoTitle: "What I Got Wrong About Mentorship",
          videoChannel: "Simon Sinek",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Growth Framework",
        description: "Design an engineering career ladder with levels, competencies, and promotion criteria.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["Career Frameworks", "Performance", "Coaching"],
      },
    },
    {
      id: "em-hiring",
      title: "Hiring & Team Building",
      description: "Recruiting, interviewing, and building high-performing teams.",
      icon: "UserPlus",
      trackId: "engineering-manager",
      order: 3,
      lessons: [
        {
          id: "em-hire-1",
          title: "Defining Roles & Job Descriptions",
          description: "Writing effective JDs and defining hiring criteria.",
          duration: "10 min",
          videoId: "4MAqVxrkkiU",
          videoTitle: "What is a Job Evaluation? Process & Strategy",
          videoChannel: "AIHR",
          hasTerminal: false,
        },
        {
          id: "em-hire-2",
          title: "Interview Design & Rubrics",
          description: "Structured interviews, coding challenges, and evaluation rubrics.",
          duration: "12 min",
          videoId: "vFOw_m5zNCs",
          videoTitle: "Confessions from a Big Tech Hiring Manager",
          videoChannel: "The Pragmatic Engineer",
          hasTerminal: false,
        },
        {
          id: "em-hire-3",
          title: "Sourcing & Pipeline Management",
          description: "Building diverse pipelines and sourcing strategies.",
          duration: "10 min",
          videoId: "sxjgL64czRY",
          videoTitle: "How to Master Recruiting",
          videoChannel: "TEDx Talks",
          hasTerminal: false,
        },
        {
          id: "em-hire-4",
          title: "Onboarding New Engineers",
          description: "30/60/90 plans, buddy systems, and ramp-up programs.",
          duration: "10 min",
          videoId: "Kgl79ajbv_c",
          videoTitle: "Best Practices for Developer Onboarding",
          videoChannel: "Tech Lead Journal",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Hiring Process",
        description: "Design a complete hiring process including JD, interview stages, rubrics, and onboarding plan.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["Hiring", "Interviews", "Onboarding"],
      },
    },
    {
      id: "em-delivery",
      title: "Project Delivery & Process",
      description: "Shipping software reliably with agile practices.",
      icon: "Truck",
      trackId: "engineering-manager",
      order: 4,
      lessons: [
        {
          id: "em-del-1",
          title: "Agile Practices for EMs",
          description: "Scrum, Kanban, and choosing the right process for your team.",
          duration: "12 min",
          videoId: "Atfxtk2Q90k",
          videoTitle: "Using Agile Techniques to Build Inclusive Teams",
          videoChannel: "LeadDev",
          hasTerminal: false,
        },
        {
          id: "em-del-2",
          title: "Estimation & Planning",
          description: "Story points, t-shirt sizing, sprint planning, and velocity tracking.",
          duration: "10 min",
          videoId: "v21jg8wb1eU",
          videoTitle: "How To Estimate Software Development Time",
          videoChannel: "Modern Software Engineering",
          hasTerminal: false,
        },
        {
          id: "em-del-3",
          title: "Managing Technical Debt",
          description: "Identifying, quantifying, and paying down technical debt.",
          duration: "12 min",
          videoId: "Bq8w2fkyDnk",
          videoTitle: "Manage Technical Debt Like This",
          videoChannel: "Modern Software Engineering",
          hasTerminal: false,
        },
        {
          id: "em-del-4",
          title: "Incident Management",
          description: "On-call rotations, incident response, and blameless postmortems.",
          duration: "12 min",
          videoId: "9JYVOUKNQ3A",
          videoTitle: "How to Run a Post-Mortem Meeting",
          videoChannel: "Bran van der Meer",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Team Process Design",
        description: "Design a development process for a team including ceremonies, tooling, and metrics.",
        difficulty: "intermediate",
        estimatedHours: 4,
        skills: ["Agile", "Process Design", "Incident Management"],
      },
    },
    {
      id: "em-technical",
      title: "Technical Leadership",
      description: "Staying technical while leading teams.",
      icon: "Code",
      trackId: "engineering-manager",
      order: 5,
      lessons: [
        {
          id: "em-tech-1",
          title: "Architecture Decision-Making",
          description: "ADRs, tech radar, and guiding architectural decisions.",
          duration: "12 min",
          videoId: "LMBqGPLvonU",
          videoTitle: "Architecture Decision Records",
          videoChannel: "Software Architecture Monday",
          hasTerminal: false,
        },
        {
          id: "em-tech-2",
          title: "Code Review Culture",
          description: "Establishing effective code review practices and standards.",
          duration: "10 min",
          videoId: "xT3oFHBDEZY",
          videoTitle: "Code Reviews, for the Culture",
          videoChannel: "LeadDev",
          hasTerminal: false,
        },
        {
          id: "em-tech-3",
          title: "Tech Strategy & Vision",
          description: "Creating a technology strategy aligned with business goals.",
          duration: "12 min",
          videoId: "H0EK0B1QvVA",
          videoTitle: "Mastering Tech Leadership in 50 Minutes",
          videoChannel: "GOTO Conferences",
          hasTerminal: false,
        },
        {
          id: "em-tech-4",
          title: "Platform & Infrastructure Decisions",
          description: "Build vs buy, vendor selection, and technology evaluation.",
          duration: "10 min",
          videoId: "_zH7TIXcjEs",
          videoTitle: "Tips For Building Successful Platform Teams",
          videoChannel: "Modern Software Engineering",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Tech Strategy Document",
        description: "Write a technology strategy document with ADRs, tech radar, and multi-quarter plan.",
        difficulty: "advanced",
        estimatedHours: 5,
        skills: ["Architecture", "Strategy", "Decision-Making"],
      },
    },
    {
      id: "em-org-design",
      title: "Organization Design",
      description: "Team topologies, scaling, and organizational dynamics.",
      icon: "Network",
      trackId: "engineering-manager",
      order: 6,
      lessons: [
        {
          id: "em-org-1",
          title: "Team Topologies",
          description: "Stream-aligned, platform, enabling, and complicated-subsystem teams.",
          duration: "12 min",
          videoId: "amfhYDbzjLU",
          videoTitle: "How To Make Development Teams Self-Serving",
          videoChannel: "Modern Software Engineering",
          hasTerminal: false,
        },
        {
          id: "em-org-2",
          title: "Scaling Engineering Organizations",
          description: "Growing from 5 to 50+ engineers — org design patterns.",
          duration: "12 min",
          videoId: "dbig1bYpRmE",
          videoTitle: "Scaling Engineering Hiring",
          videoChannel: "ELC",
          hasTerminal: false,
        },
        {
          id: "em-org-3",
          title: "Cross-Team Collaboration",
          description: "RFCs, working groups, guilds, and cross-functional alignment.",
          duration: "10 min",
          videoId: "a6J0uIG33WE",
          videoTitle: "Cross Team Collaboration and Communication",
          videoChannel: "Codementor",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Org Design Proposal",
        description: "Design a team structure for a growing engineering org with clear ownership boundaries.",
        difficulty: "advanced",
        estimatedHours: 5,
        skills: ["Org Design", "Team Topologies", "Scaling"],
      },
    },
    {
      id: "em-culture",
      title: "Engineering Culture & DEI",
      description: "Building inclusive, innovative engineering cultures.",
      icon: "Globe",
      trackId: "engineering-manager",
      order: 7,
      lessons: [
        {
          id: "em-cult-1",
          title: "Building Engineering Culture",
          description: "Values, norms, and rituals that define engineering culture.",
          duration: "10 min",
          videoId: "AsnJUVQD4BY",
          videoTitle: "How to Build an Engineering Culture",
          videoChannel: "O'Reilly",
          hasTerminal: false,
        },
        {
          id: "em-cult-2",
          title: "Diversity, Equity & Inclusion",
          description: "Building diverse teams and creating inclusive environments.",
          duration: "12 min",
          videoId: "emnqyGhBg6U",
          videoTitle: "Building Inclusive Engineering Teams",
          videoChannel: "REFACTR",
          hasTerminal: false,
        },
        {
          id: "em-cult-3",
          title: "Remote & Distributed Teams",
          description: "Managing remote teams, async communication, and distributed culture.",
          duration: "12 min",
          videoId: "aRaF-waAFj0",
          videoTitle: "Remote Inclusion in Distributed Engineering Teams",
          videoChannel: "LeadDev",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Culture Playbook",
        description: "Create a team culture playbook with values, communication norms, and DEI initiatives.",
        difficulty: "intermediate",
        estimatedHours: 4,
        skills: ["Culture", "DEI", "Remote Work"],
      },
    },
    {
      id: "em-executive",
      title: "Executive Communication",
      description: "Communicating upward, business acumen, and strategic thinking.",
      icon: "Presentation",
      trackId: "engineering-manager",
      order: 8,
      lessons: [
        {
          id: "em-exec-1",
          title: "Managing Up",
          description: "Working with your manager, VPs, and executives effectively.",
          duration: "10 min",
          videoId: "C0W4H6jMLKg",
          videoTitle: "Why Middle Management is the Hardest Job",
          videoChannel: "Simon Sinek",
          hasTerminal: false,
        },
        {
          id: "em-exec-2",
          title: "Budgeting & Resource Planning",
          description: "Headcount planning, cost management, and ROI communication.",
          duration: "12 min",
          videoId: "ecs9oUe2dZk",
          videoTitle: "How to Create a Project Budget",
          videoChannel: "Adriana Girdler",
          hasTerminal: false,
        },
        {
          id: "em-exec-3",
          title: "EM Career Paths",
          description: "From EM to senior EM, director, VP Engineering — growth paths.",
          duration: "10 min",
          videoId: "1HVPYqCnJlo",
          videoTitle: "Choosing Your Engineering Path: IC or Manager",
          videoChannel: "Google for Developers",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Quarterly Business Review",
        description: "Prepare and present a QBR including team metrics, achievements, and roadmap for your org.",
        difficulty: "advanced",
        estimatedHours: 5,
        skills: ["Communication", "Business Acumen", "Strategy"],
      },
    },
  ],
};
