import { Track } from "./types";

export const gameDeveloperTrack: Track = {
  id: "game-developer",
  title: "Game Developer",
  description:
    "Build games from concept to release. Master game engines, programming, physics, AI, graphics, audio, and publishing on multiple platforms.",
  icon: "Gamepad2",
  color: "red",
  category: "gaming",
  modules: [
    {
      id: "gd-fundamentals",
      title: "Game Development Fundamentals",
      description: "Core concepts, game loops, and the game development pipeline.",
      icon: "BookOpen",
      trackId: "game-developer",
      order: 1,
      lessons: [
        {
          id: "gd-fund-1",
          title: "Introduction to Game Dev",
          description: "Game development overview, roles, and career paths.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "gd-fund-2",
          title: "The Game Loop",
          description: "Input, update, render — the core loop of every game.",
          duration: "12 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Implement a basic game loop in Python with fixed timestep and frame rate control.",
            validation: "while|time|delta|update|render|fps",
          },
        },
        {
          id: "gd-fund-3",
          title: "Game Design Basics",
          description: "Mechanics, dynamics, aesthetics, and game design documents.",
          duration: "10 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Game Design Document",
        description: "Write a GDD for a simple game including mechanics, features, and technical requirements.",
        difficulty: "beginner",
        estimatedHours: 3,
        skills: ["Game Design", "Documentation"],
      },
    },
    {
      id: "gd-programming",
      title: "Game Programming",
      description: "Programming fundamentals for game development.",
      icon: "Code",
      trackId: "game-developer",
      order: 2,
      lessons: [
        {
          id: "gd-prog-1",
          title: "C# for Game Dev",
          description: "C# fundamentals: classes, inheritance, events, and delegates.",
          duration: "15 min",
          videoId: "GhQdlMFjlS4",
          videoTitle: "C# Full Course",
          videoChannel: "freeCodeCamp",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a C# class hierarchy for game entities with inheritance and interfaces.",
            validation: "class|interface|override|virtual|public",
          },
        },
        {
          id: "gd-prog-2",
          title: "Data Structures for Games",
          description: "Spatial partitioning, object pools, and game-specific structures.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "gd-prog-3",
          title: "Design Patterns for Games",
          description: "Component, Observer, State, Command, and Object Pool patterns.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "gd-prog-4",
          title: "Math for Games",
          description: "Vectors, matrices, quaternions, and trigonometry for games.",
          duration: "15 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Implement 2D vector operations: add, subtract, normalize, dot product, and angle between.",
            validation: "class Vector|normalize|dot|magnitude|angle",
          },
        },
      ],
      project: {
        title: "Game Math Library",
        description: "Build a reusable math library for 2D game development.",
        difficulty: "intermediate",
        estimatedHours: 4,
        skills: ["C#", "Game Math", "Design Patterns"],
      },
    },
    {
      id: "gd-unity",
      title: "Unity Engine",
      description: "Build games with Unity — the most popular game engine.",
      icon: "Box",
      trackId: "game-developer",
      order: 3,
      lessons: [
        {
          id: "gd-unity-1",
          title: "Unity Editor & Project Setup",
          description: "Navigating Unity, creating projects, and importing assets.",
          duration: "15 min",
          videoId: "gB1F9G0JXOo",
          videoTitle: "Unity Beginner Tutorial",
          videoChannel: "freeCodeCamp",
          hasTerminal: false,
        },
        {
          id: "gd-unity-2",
          title: "GameObjects, Components & Scripts",
          description: "The component model, MonoBehaviour, and scripting in Unity.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "gd-unity-3",
          title: "Physics & Collisions",
          description: "Rigidbody, colliders, triggers, and physics materials.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "gd-unity-4",
          title: "UI System (UI Toolkit / Canvas)",
          description: "Building game UIs with Unity's UI systems.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "gd-unity-5",
          title: "Animation System",
          description: "Animator controller, blend trees, and animation events.",
          duration: "12 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "2D Platformer",
        description: "Build a complete 2D platformer with player movement, enemies, and collectibles in Unity.",
        difficulty: "intermediate",
        estimatedHours: 8,
        skills: ["Unity", "C#", "Physics", "Animation"],
      },
    },
    {
      id: "gd-godot",
      title: "Godot Engine",
      description: "Open source game development with Godot and GDScript.",
      icon: "Gem",
      trackId: "game-developer",
      order: 4,
      lessons: [
        {
          id: "gd-godot-1",
          title: "Godot Editor & Nodes",
          description: "Scene tree, nodes, and the Godot workflow.",
          duration: "15 min",
          videoId: "LOhfqjmasi0",
          videoTitle: "Godot Complete Course",
          videoChannel: "freeCodeCamp",
          hasTerminal: false,
        },
        {
          id: "gd-godot-2",
          title: "GDScript Fundamentals",
          description: "GDScript syntax, signals, and node communication.",
          duration: "15 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a GDScript class for a player character with movement and jumping.",
            validation: "extends|func _process|func _ready|velocity|move",
          },
        },
        {
          id: "gd-godot-3",
          title: "Godot Physics & TileMaps",
          description: "CharacterBody2D, Area2D, and tilemap-based levels.",
          duration: "12 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Top-Down RPG in Godot",
        description: "Build a top-down RPG with character movement, NPCs, and dialogue in Godot.",
        difficulty: "intermediate",
        estimatedHours: 8,
        skills: ["Godot", "GDScript", "Game Design"],
      },
    },
    {
      id: "gd-graphics",
      title: "Graphics & Rendering",
      description: "Shaders, lighting, particles, and visual effects.",
      icon: "Sparkles",
      trackId: "game-developer",
      order: 5,
      lessons: [
        {
          id: "gd-gfx-1",
          title: "Rendering Pipeline Basics",
          description: "Vertices, fragments, and the GPU rendering pipeline.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "gd-gfx-2",
          title: "Shader Programming",
          description: "Writing vertex and fragment shaders.",
          duration: "15 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a simple GLSL fragment shader that creates a gradient effect.",
            validation: "void main|gl_FragColor|vec4|uniform|varying",
          },
        },
        {
          id: "gd-gfx-3",
          title: "Lighting & Shadows",
          description: "Directional, point, and spot lights with shadow mapping.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "gd-gfx-4",
          title: "Particle Systems",
          description: "Creating effects: fire, smoke, explosions, and magic.",
          duration: "10 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Visual Effects Demo",
        description: "Create a demo scene showcasing custom shaders, lighting, and particle effects.",
        difficulty: "advanced",
        estimatedHours: 6,
        skills: ["Shaders", "Lighting", "VFX"],
      },
    },
    {
      id: "gd-audio",
      title: "Game Audio",
      description: "Sound effects, music, and audio programming.",
      icon: "Volume2",
      trackId: "game-developer",
      order: 6,
      lessons: [
        {
          id: "gd-audio-1",
          title: "Audio Fundamentals",
          description: "Sound formats, spatial audio, and audio buses.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "gd-audio-2",
          title: "Implementing Game Audio",
          description: "Sound managers, audio pools, and dynamic music systems.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "gd-audio-3",
          title: "Audio Middleware (FMOD, Wwise)",
          description: "Professional audio tools for games.",
          duration: "10 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Audio-Enhanced Game",
        description: "Add comprehensive sound design to an existing game project.",
        difficulty: "intermediate",
        estimatedHours: 4,
        skills: ["Game Audio", "Sound Design"],
      },
    },
    {
      id: "gd-ai",
      title: "Game AI",
      description: "NPC behavior, pathfinding, decision-making, and procedural generation.",
      icon: "Brain",
      trackId: "game-developer",
      order: 7,
      lessons: [
        {
          id: "gd-ai-1",
          title: "Pathfinding (A*, Navigation Meshes)",
          description: "Implementing A* algorithm and using navigation meshes.",
          duration: "15 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Implement the A* pathfinding algorithm for a 2D grid.",
            validation: "def.*a_star|heuristic|open_set|came_from|neighbor",
          },
        },
        {
          id: "gd-ai-2",
          title: "Behavior Trees",
          description: "Building NPC AI with behavior trees.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "gd-ai-3",
          title: "State Machines for AI",
          description: "Finite state machines for enemy and NPC behavior.",
          duration: "12 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Implement a finite state machine for an enemy AI with Idle, Patrol, Chase, and Attack states.",
            validation: "class.*State|Idle|Patrol|Chase|transition",
          },
        },
        {
          id: "gd-ai-4",
          title: "Procedural Content Generation",
          description: "Random level generation, noise functions, and PCG.",
          duration: "10 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "AI System",
        description: "Build a game scene with AI-driven enemies using pathfinding and behavior trees.",
        difficulty: "advanced",
        estimatedHours: 6,
        skills: ["Game AI", "Pathfinding", "Behavior Trees"],
      },
    },
    {
      id: "gd-publishing",
      title: "Publishing & Marketing",
      description: "Prepare, optimize, and publish games across platforms.",
      icon: "Upload",
      trackId: "game-developer",
      order: 8,
      lessons: [
        {
          id: "gd-pub-1",
          title: "Platform Builds",
          description: "Building for PC, console, mobile, and web platforms.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "gd-pub-2",
          title: "Performance Optimization",
          description: "Profiling, LOD, batching, and optimization techniques.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "gd-pub-3",
          title: "Steam & itch.io Publishing",
          description: "Preparing store pages, achievements, and distribution.",
          duration: "10 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Game Release",
        description: "Polish and publish a complete game to itch.io with store page and trailer.",
        difficulty: "advanced",
        estimatedHours: 6,
        skills: ["Publishing", "Optimization", "Marketing"],
      },
    },
  ],
};
