import { Track } from "./types";

export const iosTrack: Track = {
  id: "ios",
  title: "iOS Developer",
  description:
    "Build beautiful iOS applications with Swift and SwiftUI. Master the Apple ecosystem, UIKit, data persistence, networking, and App Store publishing.",
  icon: "Apple",
  color: "slate",
  category: "mobile",
  modules: [
    {
      id: "ios-intro",
      title: "iOS Development Fundamentals",
      description: "Getting started with iOS development and Xcode.",
      icon: "BookOpen",
      trackId: "ios",
      order: 1,
      lessons: [
        {
          id: "ios-intro-1",
          title: "iOS Development Overview",
          description: "The Apple ecosystem, iOS platform, and development tools.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "ios-intro-2",
          title: "Setting Up Xcode",
          description: "Install Xcode, configure simulators, and create your first project.",
          duration: "12 min",
          videoId: "F2ojC6TNwws",
          videoTitle: "iOS Development Course",
          videoChannel: "CodeWithChris",
          hasTerminal: false,
        },
        {
          id: "ios-intro-3",
          title: "Project Structure & Targets",
          description: "Understanding Xcode project structure, schemes, and build settings.",
          duration: "10 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Hello iOS",
        description: "Create your first iOS app with a greeting screen and basic interactions.",
        difficulty: "beginner",
        estimatedHours: 2,
        skills: ["Xcode", "Project Setup"],
      },
    },
    {
      id: "ios-swift",
      title: "Swift Programming",
      description: "Master the Swift programming language for iOS development.",
      icon: "Code",
      trackId: "ios",
      order: 2,
      lessons: [
        {
          id: "ios-sw-1",
          title: "Swift Basics",
          description: "Variables, types, optionals, control flow, and functions.",
          duration: "15 min",
          videoId: "8Xg7E9shq0U",
          videoTitle: "Swift Programming Tutorial",
          videoChannel: "freeCodeCamp",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a Swift function that safely unwraps an optional String using guard let and returns its uppercased value.",
            validation: "func|guard let|Optional|String|return",
          },
        },
        {
          id: "ios-sw-2",
          title: "Structs, Classes & Protocols",
          description: "Value types, reference types, protocols, and protocol-oriented programming.",
          duration: "15 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Create a protocol for Drawable shapes and implement it for Circle and Rectangle structs.",
            validation: "protocol|struct|func.*draw|extension",
          },
        },
        {
          id: "ios-sw-3",
          title: "Closures & Higher-Order Functions",
          description: "Closures, map, filter, reduce, and functional patterns.",
          duration: "12 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Use map, filter, and reduce on an array of integers to find the sum of even squares.",
            validation: "map|filter|reduce|\\$0",
          },
        },
        {
          id: "ios-sw-4",
          title: "Concurrency (async/await)",
          description: "Swift concurrency: async/await, actors, and structured concurrency.",
          duration: "15 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write an async function that fetches data from two URLs concurrently using async let.",
            validation: "async|await|async let|Task",
          },
        },
        {
          id: "ios-sw-5",
          title: "Error Handling & Generics",
          description: "do-try-catch, custom errors, Result type, and generics.",
          duration: "12 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Create a generic Result handler for network responses with custom error types.",
            validation: "enum.*Error|throws|Result|Generic|<T>",
          },
        },
      ],
      project: {
        title: "Swift Challenges",
        description: "Complete a set of Swift programming challenges covering all core concepts.",
        difficulty: "beginner",
        estimatedHours: 3,
        skills: ["Swift", "Concurrency", "Protocols"],
      },
    },
    {
      id: "ios-swiftui",
      title: "SwiftUI",
      description: "Build modern declarative UIs with SwiftUI.",
      icon: "Layout",
      trackId: "ios",
      order: 3,
      lessons: [
        {
          id: "ios-sui-1",
          title: "SwiftUI Fundamentals",
          description: "Views, modifiers, @State, and the declarative paradigm.",
          duration: "20 min",
          videoId: "F2ojC6TNwws",
          videoTitle: "SwiftUI Tutorial",
          videoChannel: "CodeWithChris",
          hasTerminal: false,
        },
        {
          id: "ios-sui-2",
          title: "Layouts (VStack, HStack, ZStack, Grid)",
          description: "SwiftUI layout system, alignment, and lazy containers.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "ios-sui-3",
          title: "State Management",
          description: "@State, @Binding, @ObservedObject, @StateObject, and @EnvironmentObject.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "ios-sui-4",
          title: "Lists & Navigation",
          description: "List, NavigationStack, NavigationLink, and detail views.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "ios-sui-5",
          title: "Animations & Gestures",
          description: "withAnimation, matchedGeometryEffect, and gesture recognition.",
          duration: "12 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "SwiftUI Showcase App",
        description: "Build a multi-screen app showcasing various SwiftUI components and animations.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["SwiftUI", "State Management", "Animations"],
      },
    },
    {
      id: "ios-architecture",
      title: "App Architecture",
      description: "MVVM, Clean Architecture, and dependency injection for iOS.",
      icon: "Layers",
      trackId: "ios",
      order: 4,
      lessons: [
        {
          id: "ios-arch-1",
          title: "MVVM in SwiftUI",
          description: "ViewModel pattern with ObservableObject and @Published.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "ios-arch-2",
          title: "The Composable Architecture (TCA)",
          description: "Introduction to TCA for scalable SwiftUI apps.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "ios-arch-3",
          title: "Dependency Injection",
          description: "Environment values, protocols, and DI patterns in Swift.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "ios-arch-4",
          title: "Modularization",
          description: "Swift packages, modules, and organizing large iOS projects.",
          duration: "10 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Well-Architected iOS App",
        description: "Refactor an app to follow MVVM with clean separation and dependency injection.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["MVVM", "Clean Architecture", "DI"],
      },
    },
    {
      id: "ios-data",
      title: "Data Persistence",
      description: "Store data with Core Data, SwiftData, and UserDefaults.",
      icon: "Database",
      trackId: "ios",
      order: 5,
      lessons: [
        {
          id: "ios-data-1",
          title: "SwiftData",
          description: "Apple's modern persistence framework with @Model and @Query.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "ios-data-2",
          title: "Core Data Fundamentals",
          description: "Managed objects, contexts, and fetch requests.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "ios-data-3",
          title: "UserDefaults & Keychain",
          description: "Simple storage and secure credential storage.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "ios-data-4",
          title: "CloudKit Sync",
          description: "Syncing data across devices with iCloud and CloudKit.",
          duration: "12 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Persistent Todo App",
        description: "Build a todo app with SwiftData persistence and CloudKit sync.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["SwiftData", "Core Data", "CloudKit"],
      },
    },
    {
      id: "ios-networking",
      title: "Networking",
      description: "URLSession, REST APIs, and modern networking patterns.",
      icon: "Globe",
      trackId: "ios",
      order: 6,
      lessons: [
        {
          id: "ios-net-1",
          title: "URLSession & Async/Await",
          description: "Making API calls with modern Swift concurrency.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "ios-net-2",
          title: "JSON Decoding (Codable)",
          description: "Mapping JSON to Swift types with Codable protocol.",
          duration: "12 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Define a Swift Codable struct for a user profile JSON and decode a sample response.",
            validation: "Codable|Decodable|JSONDecoder|decode",
          },
        },
        {
          id: "ios-net-3",
          title: "Network Layer Architecture",
          description: "Building a reusable network layer with generics and protocols.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "ios-net-4",
          title: "WebSockets & Real-Time",
          description: "Real-time communication in iOS apps.",
          duration: "10 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "API-Connected iOS App",
        description: "Build an app that fetches, caches, and displays data from a REST API.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["URLSession", "Codable", "Networking"],
      },
    },
    {
      id: "ios-uikit",
      title: "UIKit Essentials",
      description: "Understanding UIKit for legacy apps and advanced use cases.",
      icon: "Palette",
      trackId: "ios",
      order: 7,
      lessons: [
        {
          id: "ios-uik-1",
          title: "UIKit Overview",
          description: "UIViewController, UIView, and the UIKit lifecycle.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "ios-uik-2",
          title: "Auto Layout",
          description: "Constraints, stack views, and responsive layouts.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "ios-uik-3",
          title: "UIKit & SwiftUI Interop",
          description: "UIViewRepresentable and UIHostingController for mixing frameworks.",
          duration: "10 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "UIKit Component Bridge",
        description: "Build a SwiftUI app that integrates UIKit components via representables.",
        difficulty: "intermediate",
        estimatedHours: 3,
        skills: ["UIKit", "SwiftUI Interop"],
      },
    },
    {
      id: "ios-testing",
      title: "Testing",
      description: "Unit testing, UI testing, and snapshot testing for iOS.",
      icon: "TestTube",
      trackId: "ios",
      order: 8,
      lessons: [
        {
          id: "ios-test-1",
          title: "XCTest Unit Testing",
          description: "Writing and running unit tests with XCTest.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "ios-test-2",
          title: "UI Testing with XCUITest",
          description: "Automated UI testing for SwiftUI and UIKit.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "ios-test-3",
          title: "Snapshot & Preview Testing",
          description: "Testing UI appearance and SwiftUI previews.",
          duration: "10 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Comprehensive Test Suite",
        description: "Add unit and UI tests to an existing iOS app with 80%+ coverage.",
        difficulty: "intermediate",
        estimatedHours: 4,
        skills: ["XCTest", "UI Testing", "TDD"],
      },
    },
    {
      id: "ios-publishing",
      title: "App Store Publishing",
      description: "Prepare, submit, and market your app on the App Store.",
      icon: "Upload",
      trackId: "ios",
      order: 9,
      lessons: [
        {
          id: "ios-pub-1",
          title: "App Store Connect",
          description: "Setting up your app, metadata, and screenshots.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "ios-pub-2",
          title: "Code Signing & Provisioning",
          description: "Certificates, identifiers, provisioning profiles, and entitlements.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "ios-pub-3",
          title: "CI/CD with Xcode Cloud & Fastlane",
          description: "Automated builds, tests, and deployment pipelines.",
          duration: "12 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a Fastlane configuration (Fastfile) for building and uploading to TestFlight.",
            validation: "lane|gym|pilot|fastlane|deliver",
          },
        },
        {
          id: "ios-pub-4",
          title: "App Review Guidelines",
          description: "Understanding Apple's review process and common rejection reasons.",
          duration: "8 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Publish-Ready iOS App",
        description: "Prepare a full app submission with screenshots, metadata, and CI/CD pipeline.",
        difficulty: "advanced",
        estimatedHours: 5,
        skills: ["App Store", "Fastlane", "CI/CD"],
      },
    },
  ],
};
