import { Track } from "./types";

export const machineLearningTrack: Track = {
  id: "machine-learning",
  title: "Machine Learning Engineer",
  description:
    "Build, train, and deploy machine learning models. From math foundations to deep learning, NLP, computer vision, and production deployment.",
  icon: "Brain",
  color: "pink",
  category: "data-ai",
  modules: [
    {
      id: "ml-intro",
      title: "ML Introduction",
      description: "Machine learning landscape, types of learning, and getting started.",
      icon: "BookOpen",
      trackId: "machine-learning",
      order: 1,
      lessons: [
        {
          id: "ml-intro-1",
          title: "What is Machine Learning?",
          description: "Overview of ML, its applications, and career paths.",
          duration: "10 min",
          videoId: "ukzFI9rgwfU",
          videoTitle: "Machine Learning Explained",
          videoChannel: "Fireship",
          hasTerminal: false,
        },
        {
          id: "ml-intro-2",
          title: "Types of Machine Learning",
          description: "Supervised, unsupervised, semi-supervised, and reinforcement learning.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "ml-intro-3",
          title: "ML Development Workflow",
          description: "Problem framing, data collection, modeling, evaluation, and deployment.",
          duration: "10 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "ML Problem Framing",
        description: "Frame 3 real-world problems as ML tasks and identify the type of learning needed.",
        difficulty: "beginner",
        estimatedHours: 2,
        skills: ["Problem Framing", "ML Concepts"],
      },
    },
    {
      id: "ml-math",
      title: "Mathematical Foundations",
      description: "Linear algebra, calculus, probability, and statistics for ML.",
      icon: "Calculator",
      trackId: "machine-learning",
      order: 2,
      lessons: [
        {
          id: "ml-math-1",
          title: "Linear Algebra for ML",
          description: "Vectors, matrices, transformations, and decompositions.",
          duration: "20 min",
          videoId: "fNk_zzaMoSs",
          videoTitle: "Essence of Linear Algebra",
          videoChannel: "3Blue1Brown",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Implement matrix multiplication and find eigenvalues using NumPy.",
            validation: "np\\.dot|matmul|eig|numpy",
          },
        },
        {
          id: "ml-math-2",
          title: "Calculus & Optimization",
          description: "Gradients, partial derivatives, and gradient descent.",
          duration: "15 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Implement gradient descent to find the minimum of f(x) = x^2 + 4x + 4.",
            validation: "gradient|learning_rate|descent|while",
          },
        },
        {
          id: "ml-math-3",
          title: "Probability & Statistics",
          description: "Distributions, Bayes' theorem, and maximum likelihood.",
          duration: "15 min",
          videoId: "xxpc-HPKN28",
          videoTitle: "Statistics Fundamentals",
          videoChannel: "StatQuest",
          hasTerminal: false,
        },
        {
          id: "ml-math-4",
          title: "Information Theory",
          description: "Entropy, cross-entropy, and KL divergence in ML.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "ml-math-5",
          title: "Numerical Computation",
          description: "Floating point, overflow, underflow, and numerical stability.",
          duration: "8 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Math for ML Notebook",
        description: "Create a comprehensive notebook with implementations of key math concepts.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["Linear Algebra", "Calculus", "NumPy"],
      },
    },
    {
      id: "ml-python",
      title: "Python for ML",
      description: "Python ecosystem for machine learning development.",
      icon: "Code",
      trackId: "machine-learning",
      order: 3,
      lessons: [
        {
          id: "ml-py-1",
          title: "NumPy & Vectorization",
          description: "Efficient numerical computation with NumPy arrays.",
          duration: "15 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Implement a vectorized computation: normalize a matrix so each row sums to 1.",
            validation: "np\\.|sum|axis|reshape",
          },
        },
        {
          id: "ml-py-2",
          title: "Pandas for ML Data Prep",
          description: "Data loading, cleaning, and feature engineering with Pandas.",
          duration: "12 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Load a dataset, handle missing values, encode categories, and create train/test splits.",
            validation: "fillna|get_dummies|train_test_split",
          },
        },
        {
          id: "ml-py-3",
          title: "Matplotlib & Seaborn Visualization",
          description: "Plotting model performance, data distributions, and feature importance.",
          duration: "10 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Create a 2x2 subplot grid showing histogram, scatter plot, box plot, and heatmap.",
            validation: "subplot|plt\\.|sns\\.",
          },
        },
        {
          id: "ml-py-4",
          title: "Scikit-learn Overview",
          description: "The scikit-learn API: estimators, transformers, and pipelines.",
          duration: "15 min",
          videoId: "0B5eIE_1vpU",
          videoTitle: "Scikit-Learn Course",
          videoChannel: "freeCodeCamp",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Build a scikit-learn Pipeline with StandardScaler and LogisticRegression.",
            validation: "Pipeline|StandardScaler|LogisticRegression|fit",
          },
        },
      ],
      project: {
        title: "ML Data Toolkit",
        description: "Build a reusable Python module for data loading, cleaning, and preprocessing.",
        difficulty: "intermediate",
        estimatedHours: 4,
        skills: ["NumPy", "Pandas", "scikit-learn"],
      },
    },
    {
      id: "ml-data",
      title: "Data Collection & Preprocessing",
      description: "Gathering, cleaning, and preparing data for ML models.",
      icon: "Filter",
      trackId: "machine-learning",
      order: 4,
      lessons: [
        {
          id: "ml-data-1",
          title: "Data Collection Strategies",
          description: "Web scraping, APIs, synthetic data, and data augmentation.",
          duration: "12 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a Python script to collect data from a public API and save as CSV.",
            validation: "requests|json|csv|to_csv",
          },
        },
        {
          id: "ml-data-2",
          title: "Handling Missing & Noisy Data",
          description: "Imputation strategies, outlier handling, and denoising.",
          duration: "12 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Implement multiple imputation strategies (mean, median, KNN) and compare results.",
            validation: "SimpleImputer|KNNImputer|fillna|strategy",
          },
        },
        {
          id: "ml-data-3",
          title: "Feature Engineering",
          description: "Creating new features, encoding categories, and scaling.",
          duration: "15 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Create polynomial features, apply one-hot encoding, and use StandardScaler on a dataset.",
            validation: "PolynomialFeatures|OneHotEncoder|StandardScaler",
          },
        },
        {
          id: "ml-data-4",
          title: "Feature Selection",
          description: "Filter, wrapper, and embedded methods for feature selection.",
          duration: "10 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Use SelectKBest and feature importance from Random Forest to select top features.",
            validation: "SelectKBest|feature_importances_|RandomForest",
          },
        },
      ],
      project: {
        title: "Feature Engineering Pipeline",
        description: "Build a complete preprocessing pipeline for a messy real-world dataset.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["Feature Engineering", "Data Preprocessing", "scikit-learn"],
      },
    },
    {
      id: "ml-supervised",
      title: "Supervised Learning",
      description: "Classification and regression algorithms in depth.",
      icon: "Target",
      trackId: "machine-learning",
      order: 5,
      lessons: [
        {
          id: "ml-sup-1",
          title: "Linear & Logistic Regression",
          description: "Linear models from scratch and with scikit-learn.",
          duration: "15 min",
          videoId: "nk2CQITm_eo",
          videoTitle: "Linear Regression",
          videoChannel: "StatQuest",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Implement linear regression from scratch using gradient descent, then compare with sklearn.",
            validation: "gradient|weights|predict|LinearRegression",
          },
        },
        {
          id: "ml-sup-2",
          title: "Decision Trees & Random Forests",
          description: "Tree-based methods, bagging, and feature importance.",
          duration: "15 min",
          videoId: "J4Wdy0Wc_xQ",
          videoTitle: "Random Forests",
          videoChannel: "StatQuest",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Train a Random Forest on a classification task and visualize feature importances.",
            validation: "RandomForestClassifier|feature_importances_|fit|predict",
          },
        },
        {
          id: "ml-sup-3",
          title: "Support Vector Machines",
          description: "SVM theory, kernels, and practical usage.",
          duration: "12 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Train SVM classifiers with linear and RBF kernels and compare decision boundaries.",
            validation: "SVC|kernel.*rbf|kernel.*linear|fit",
          },
        },
        {
          id: "ml-sup-4",
          title: "Gradient Boosting (XGBoost, LightGBM)",
          description: "Boosting algorithms and hyperparameter tuning.",
          duration: "15 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Train an XGBoost model with hyperparameter tuning using GridSearchCV.",
            validation: "XGBClassifier|GridSearchCV|param_grid|fit",
          },
        },
        {
          id: "ml-sup-5",
          title: "Naive Bayes & KNN",
          description: "Probabilistic classifiers and instance-based learning.",
          duration: "10 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Compare Naive Bayes and KNN classifiers on a text classification dataset.",
            validation: "GaussianNB|KNeighborsClassifier|predict|accuracy",
          },
        },
      ],
      project: {
        title: "Supervised Learning Benchmark",
        description: "Compare 5+ algorithms on multiple datasets and build a comprehensive comparison report.",
        difficulty: "intermediate",
        estimatedHours: 6,
        skills: ["Classification", "Regression", "Model Comparison"],
      },
    },
    {
      id: "ml-unsupervised",
      title: "Unsupervised Learning",
      description: "Clustering, dimensionality reduction, and anomaly detection.",
      icon: "Shapes",
      trackId: "machine-learning",
      order: 6,
      lessons: [
        {
          id: "ml-unsup-1",
          title: "K-Means & Hierarchical Clustering",
          description: "Centroid-based and linkage-based clustering.",
          duration: "15 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Apply K-Means clustering, use the elbow method, and visualize clusters.",
            validation: "KMeans|inertia_|elbow|scatter",
          },
        },
        {
          id: "ml-unsup-2",
          title: "DBSCAN & Density-Based Methods",
          description: "Density-based clustering for arbitrary-shape clusters.",
          duration: "10 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Apply DBSCAN to a dataset with noise and compare results with K-Means.",
            validation: "DBSCAN|eps|min_samples|labels_",
          },
        },
        {
          id: "ml-unsup-3",
          title: "PCA & Dimensionality Reduction",
          description: "PCA, t-SNE, and UMAP for visualization and compression.",
          duration: "15 min",
          videoId: "HMOI_lkCRBo",
          videoTitle: "PCA Explained",
          videoChannel: "StatQuest",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Apply PCA to reduce a high-dimensional dataset and plot explained variance ratio.",
            validation: "PCA|explained_variance_ratio_|n_components|fit_transform",
          },
        },
        {
          id: "ml-unsup-4",
          title: "Anomaly Detection",
          description: "Isolation Forest, One-Class SVM, and autoencoders for anomaly detection.",
          duration: "12 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Use Isolation Forest to detect anomalies in a dataset and evaluate results.",
            validation: "IsolationForest|predict|contamination|anomal",
          },
        },
      ],
      project: {
        title: "Customer Segmentation",
        description: "Segment customers using clustering and visualize segments with dimensionality reduction.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["Clustering", "PCA", "Visualization"],
      },
    },
    {
      id: "ml-deep-learning",
      title: "Deep Learning",
      description: "Neural networks, CNNs, RNNs, and transformers.",
      icon: "Network",
      trackId: "machine-learning",
      order: 7,
      lessons: [
        {
          id: "ml-dl-1",
          title: "Neural Network Fundamentals",
          description: "Perceptrons, activation functions, backpropagation, and loss functions.",
          duration: "20 min",
          videoId: "aircAruvnKk",
          videoTitle: "Neural Networks",
          videoChannel: "3Blue1Brown",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Implement a simple neural network from scratch with forward pass and backpropagation.",
            validation: "sigmoid|forward|backward|weights|gradient",
          },
        },
        {
          id: "ml-dl-2",
          title: "PyTorch Fundamentals",
          description: "Tensors, autograd, nn.Module, and training loops.",
          duration: "20 min",
          videoId: "V_xro1bcAuA",
          videoTitle: "PyTorch Full Course",
          videoChannel: "freeCodeCamp",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Build a PyTorch neural network with 2 hidden layers and train it on sample data.",
            validation: "nn\\.Module|forward|optimizer|loss\\.backward",
          },
        },
        {
          id: "ml-dl-3",
          title: "Convolutional Neural Networks",
          description: "CNNs for image classification, convolutions, and pooling.",
          duration: "15 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Build a CNN in PyTorch with Conv2d, MaxPool2d, and fully connected layers.",
            validation: "Conv2d|MaxPool2d|nn\\.Linear|forward",
          },
        },
        {
          id: "ml-dl-4",
          title: "Recurrent Neural Networks & LSTMs",
          description: "Sequence modeling with RNNs and LSTM networks.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "ml-dl-5",
          title: "Transformers & Attention",
          description: "Self-attention, transformer architecture, and Hugging Face.",
          duration: "20 min",
          videoId: "kCc8FmEb1nY",
          videoTitle: "Let's Build GPT",
          videoChannel: "Andrej Karpathy",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Image Classifier",
        description: "Build and train a CNN to classify images with PyTorch.",
        difficulty: "advanced",
        estimatedHours: 8,
        skills: ["PyTorch", "CNNs", "Deep Learning"],
      },
    },
    {
      id: "ml-evaluation",
      title: "Model Evaluation & Tuning",
      description: "Evaluate, tune, and select the best models.",
      icon: "SlidersHorizontal",
      trackId: "machine-learning",
      order: 8,
      lessons: [
        {
          id: "ml-eval-1",
          title: "Evaluation Metrics",
          description: "Accuracy, precision, recall, F1, AUC-ROC, and confusion matrix.",
          duration: "15 min",
          videoId: "Kdsp6soqA7o",
          videoTitle: "ROC and AUC",
          videoChannel: "StatQuest",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Compute precision, recall, F1, and plot a ROC curve for a binary classifier.",
            validation: "precision_score|recall_score|f1_score|roc_curve",
          },
        },
        {
          id: "ml-eval-2",
          title: "Cross-Validation Strategies",
          description: "K-fold, stratified, time series, and leave-one-out CV.",
          duration: "12 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Implement stratified 5-fold cross-validation and report mean and std of scores.",
            validation: "StratifiedKFold|cross_val_score|cv|mean|std",
          },
        },
        {
          id: "ml-eval-3",
          title: "Hyperparameter Tuning",
          description: "Grid search, random search, and Bayesian optimization.",
          duration: "15 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Use RandomizedSearchCV to tune hyperparameters of a Random Forest classifier.",
            validation: "RandomizedSearchCV|param_distributions|best_params_",
          },
        },
        {
          id: "ml-eval-4",
          title: "Bias-Variance Tradeoff",
          description: "Understanding overfitting, underfitting, and regularization.",
          duration: "10 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Model Selection Framework",
        description: "Build a framework that evaluates multiple models with cross-validation and hyperparameter tuning.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["Model Evaluation", "Hyperparameter Tuning", "scikit-learn"],
      },
    },
    {
      id: "ml-deployment",
      title: "ML Model Deployment",
      description: "Deploy ML models to production with APIs, containers, and monitoring.",
      icon: "Rocket",
      trackId: "machine-learning",
      order: 9,
      lessons: [
        {
          id: "ml-deploy-1",
          title: "Model Serialization",
          description: "Saving and loading models with pickle, joblib, and ONNX.",
          duration: "10 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Train a model, save it with joblib, and load it back to make predictions.",
            validation: "joblib\\.dump|joblib\\.load|predict",
          },
        },
        {
          id: "ml-deploy-2",
          title: "Building ML APIs with FastAPI",
          description: "Serve ML models as REST APIs with FastAPI.",
          duration: "15 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Create a FastAPI endpoint that accepts features and returns model predictions.",
            validation: "FastAPI|app\\.|predict|@app\\.post",
          },
        },
        {
          id: "ml-deploy-3",
          title: "Containerizing ML Models",
          description: "Docker for ML model packaging and deployment.",
          duration: "12 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a Dockerfile for an ML API service with Python dependencies.",
            validation: "FROM.*python|COPY|RUN.*pip|CMD|EXPOSE",
          },
        },
        {
          id: "ml-deploy-4",
          title: "Model Monitoring",
          description: "Data drift, model degradation, and monitoring in production.",
          duration: "10 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "ML Model API",
        description: "Deploy a trained model as a containerized REST API with monitoring.",
        difficulty: "advanced",
        estimatedHours: 6,
        skills: ["FastAPI", "Docker", "Model Serving"],
      },
    },
    {
      id: "ml-advanced",
      title: "Advanced Topics (NLP, CV, RL)",
      description: "Specialized domains: natural language processing, computer vision, and reinforcement learning.",
      icon: "Sparkles",
      trackId: "machine-learning",
      order: 10,
      lessons: [
        {
          id: "ml-adv-1",
          title: "NLP Fundamentals",
          description: "Text preprocessing, TF-IDF, word embeddings, and transformers for NLP.",
          duration: "15 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Build a text classifier using TF-IDF and a classification model with scikit-learn.",
            validation: "TfidfVectorizer|fit_transform|predict|text",
          },
        },
        {
          id: "ml-adv-2",
          title: "Computer Vision with PyTorch",
          description: "Image classification, object detection, and transfer learning.",
          duration: "15 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Use a pre-trained ResNet model from torchvision for transfer learning on a custom dataset.",
            validation: "torchvision|resnet|pretrained|transfer",
          },
        },
        {
          id: "ml-adv-3",
          title: "Reinforcement Learning Basics",
          description: "Q-learning, policy gradients, and OpenAI Gym.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "ml-adv-4",
          title: "Generative Models",
          description: "GANs, VAEs, and diffusion models overview.",
          duration: "12 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Specialized ML Application",
        description: "Build a complete application in one specialized domain (NLP, CV, or RL).",
        difficulty: "advanced",
        estimatedHours: 8,
        skills: ["NLP", "Computer Vision", "Specialized ML"],
      },
    },
  ],
};
