import { Track } from "./types";

export const postgresqlTrack: Track = {
  id: "postgresql",
  title: "PostgreSQL DBA",
  description:
    "Master PostgreSQL database administration, performance tuning, replication, security, and advanced features for production environments.",
  icon: "Database",
  color: "sky",
  category: "infrastructure",
  modules: [
    {
      id: "pg-fundamentals",
      title: "PostgreSQL Fundamentals",
      description: "Core PostgreSQL concepts, installation, and basic administration.",
      icon: "BookOpen",
      trackId: "postgresql",
      order: 1,
      lessons: [
        {
          id: "pg-fund-1",
          title: "Introduction to PostgreSQL",
          description: "History, features, and why PostgreSQL.",
          duration: "10 min",
          videoId: "qw--VYLpxG4",
          videoTitle: "PostgreSQL Tutorial",
          videoChannel: "freeCodeCamp",
          hasTerminal: false,
        },
        {
          id: "pg-fund-2",
          title: "Installation & Configuration",
          description: "Installing PostgreSQL, pg_hba.conf, and postgresql.conf.",
          duration: "12 min",
          videoId: "qw--VYLpxG4",
          videoTitle: "Learn PostgreSQL Tutorial — Full Course for Beginners",
          videoChannel: "freeCodeCamp.org",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Install PostgreSQL, create a database, and verify the connection with psql.",
            validation: "createdb|psql|\\\\c|CREATE DATABASE",
          },
        },
        {
          id: "pg-fund-3",
          title: "SQL Refresher",
          description: "DDL, DML, TCL — creating tables, inserting, querying data.",
          duration: "15 min",
          videoId: "p3qvj9hO_Bo",
          videoTitle: "Learn SQL In 60 Minutes",
          videoChannel: "Web Dev Simplified",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Create a table with constraints, insert data, and write a query with JOINs.",
            validation: "CREATE TABLE|INSERT INTO|SELECT.*JOIN",
          },
        },
        {
          id: "pg-fund-4",
          title: "Data Types & Domains",
          description: "PostgreSQL data types: arrays, JSONB, UUID, custom types.",
          duration: "12 min",
          videoId: "lF1T-PjX2gQ",
          videoTitle: "Fantastic Data Types & Domain Types",
          videoChannel: "Scaling Postgres",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Create a table using JSONB, array, and UUID columns, then query the JSONB data.",
            validation: "JSONB|UUID|ARRAY|->|@>",
          },
        },
      ],
      project: {
        title: "PostgreSQL Setup & Schema",
        description: "Set up a PostgreSQL instance and design a normalized schema for a sample application.",
        difficulty: "beginner",
        estimatedHours: 3,
        skills: ["PostgreSQL", "SQL", "Schema Design"],
      },
    },
    {
      id: "pg-advanced-sql",
      title: "Advanced SQL",
      description: "Window functions, CTEs, recursive queries, and advanced features.",
      icon: "Braces",
      trackId: "postgresql",
      order: 2,
      lessons: [
        {
          id: "pg-adv-1",
          title: "Window Functions",
          description: "ROW_NUMBER, RANK, LEAD, LAG, and frame specifications.",
          duration: "15 min",
          videoId: "rIcB4zMYMas",
          videoTitle: "SQL Window Functions Clearly Explained",
          videoChannel: "Maven Analytics",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write queries using ROW_NUMBER, RANK, and LAG to analyze sales data.",
            validation: "OVER|PARTITION BY|ROW_NUMBER|RANK|LAG",
          },
        },
        {
          id: "pg-adv-2",
          title: "CTEs & Recursive Queries",
          description: "WITH clause, recursive CTEs for hierarchical data.",
          duration: "15 min",
          videoId: "LJC8277LONg",
          videoTitle: "SQL WITH Clause — CTEs vs Subqueries vs Temp Tables",
          videoChannel: "Maven Analytics",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a recursive CTE to traverse an employee-manager hierarchy.",
            validation: "WITH RECURSIVE|UNION ALL|SELECT.*FROM",
          },
        },
        {
          id: "pg-adv-3",
          title: "JSONB Operations",
          description: "Querying, indexing, and manipulating JSONB data.",
          duration: "12 min",
          videoId: "nxeUiRz4G-M",
          videoTitle: "How to Store and Query JSON Data in Postgres",
          videoChannel: "Supabase",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Query a JSONB column using containment, path queries, and jsonb_agg.",
            validation: "@>|->|jsonb_agg|jsonb_each",
          },
        },
        {
          id: "pg-adv-4",
          title: "Lateral Joins & Subqueries",
          description: "LATERAL joins and correlated subqueries.",
          duration: "10 min",
          videoId: "NiiN63lEzvI",
          videoTitle: "LATERAL Joins in SQL — Write Smarter Queries",
          videoChannel: "techTFQ",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a query using LATERAL JOIN to find the top 3 orders per customer.",
            validation: "LATERAL|LIMIT 3|ORDER BY",
          },
        },
      ],
      project: {
        title: "Advanced SQL Challenges",
        description: "Solve 10 advanced SQL challenges using window functions, CTEs, and JSONB.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["Advanced SQL", "Window Functions", "CTEs"],
      },
    },
    {
      id: "pg-indexing",
      title: "Indexing & Performance",
      description: "Index types, query planning, and performance optimization.",
      icon: "Zap",
      trackId: "postgresql",
      order: 3,
      lessons: [
        {
          id: "pg-idx-1",
          title: "Index Types",
          description: "B-tree, GiST, GIN, BRIN, and hash indexes.",
          duration: "15 min",
          videoId: "_HG2eB27j00",
          videoTitle: "PostgreSQL Indexes — B-Tree, GIN, BRIN Explained",
          videoChannel: "JaneExplainsIT",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Create B-tree, GIN (for JSONB), and partial indexes, then compare query plans.",
            validation: "CREATE INDEX|USING GIN|USING BRIN|WHERE",
          },
        },
        {
          id: "pg-idx-2",
          title: "EXPLAIN & Query Plans",
          description: "Reading EXPLAIN ANALYZE output and identifying bottlenecks.",
          duration: "15 min",
          videoId: "P7EUFtjeAmI",
          videoTitle: "Postgres Explain Explained",
          videoChannel: "Hussein Nasser",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Use EXPLAIN (ANALYZE, BUFFERS) to analyze a slow query and suggest improvements.",
            validation: "EXPLAIN.*ANALYZE|Seq Scan|Index Scan|BUFFERS",
          },
        },
        {
          id: "pg-idx-3",
          title: "Query Optimization Techniques",
          description: "Rewriting queries, index-only scans, and join strategies.",
          duration: "12 min",
          videoId: "YON9PliOYFk",
          videoTitle: "5 Secrets for Making PostgreSQL Run Blazing Fast",
          videoChannel: "Dreams of Code",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Optimize a slow query by adding appropriate indexes and rewriting the query.",
            validation: "CREATE INDEX|EXPLAIN|Bitmap|Hash Join",
          },
        },
        {
          id: "pg-idx-4",
          title: "pg_stat_statements & Monitoring",
          description: "Identifying slow queries and monitoring database performance.",
          duration: "10 min",
          videoId: "_waM0GsH4HY",
          videoTitle: "Identifying Slow Queries and Fixing Them!",
          videoChannel: "US PostgreSQL Association",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Enable pg_stat_statements and query it to find the top 5 slowest queries.",
            validation: "pg_stat_statements|mean_exec_time|calls|ORDER BY",
          },
        },
      ],
      project: {
        title: "Performance Audit",
        description: "Audit a database for performance issues and implement optimizations.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["Indexing", "Query Optimization", "EXPLAIN"],
      },
    },
    {
      id: "pg-admin",
      title: "Database Administration",
      description: "Users, roles, tablespaces, maintenance, and backup/restore.",
      icon: "Settings",
      trackId: "postgresql",
      order: 4,
      lessons: [
        {
          id: "pg-admin-1",
          title: "Users, Roles & Permissions",
          description: "GRANT, REVOKE, row-level security, and role management.",
          duration: "12 min",
          videoId: "mtPM3iZFE04",
          videoTitle: "Roles, Privileges, and Security in PostgreSQL",
          videoChannel: "Microsoft Developer",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Create roles with specific permissions and enable row-level security on a table.",
            validation: "CREATE ROLE|GRANT|ROW LEVEL SECURITY|POLICY",
          },
        },
        {
          id: "pg-admin-2",
          title: "Backup & Restore",
          description: "pg_dump, pg_restore, and continuous archiving with WAL.",
          duration: "15 min",
          videoId: "WB6WzuFHcP8",
          videoTitle: "Backing Up a Postgres Database with pg_dump",
          videoChannel: "WittCode",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Create a pg_dump backup in custom format and restore it to a new database.",
            validation: "pg_dump|pg_restore|--format|createdb",
          },
        },
        {
          id: "pg-admin-3",
          title: "VACUUM, ANALYZE & Maintenance",
          description: "Autovacuum tuning, ANALYZE, and routine maintenance tasks.",
          duration: "12 min",
          videoId: "D832gi8Qrv4",
          videoTitle: "Optimizing Autovacuum: PostgreSQL's Vacuum Cleaner",
          videoChannel: "Microsoft Developer",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Check table bloat, run VACUUM FULL, and verify with pg_stat_user_tables.",
            validation: "VACUUM|ANALYZE|pg_stat_user_tables|dead_tup",
          },
        },
        {
          id: "pg-admin-4",
          title: "Tablespaces & Storage",
          description: "Managing tablespaces, TOAST tables, and storage strategies.",
          duration: "10 min",
          videoId: "rMTgfgmZzNo",
          videoTitle: "What are Tablespaces in Postgres",
          videoChannel: "Redincs Technology",
          hasTerminal: false,
        },
      ],
      project: {
        title: "DBA Playbook",
        description: "Create an operational runbook for PostgreSQL backup, maintenance, and user management.",
        difficulty: "intermediate",
        estimatedHours: 4,
        skills: ["DBA", "Backup", "Security", "Maintenance"],
      },
    },
    {
      id: "pg-replication",
      title: "Replication & High Availability",
      description: "Streaming replication, logical replication, and HA architectures.",
      icon: "Copy",
      trackId: "postgresql",
      order: 5,
      lessons: [
        {
          id: "pg-rep-1",
          title: "Streaming Replication",
          description: "Primary-standby setup, WAL shipping, and synchronous replication.",
          duration: "15 min",
          videoId: "Yy0GJjRQcRQ",
          videoTitle: "PostgreSQL Streaming Replication Tutorial",
          videoChannel: "High-Performance Programming",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Configure postgresql.conf for streaming replication (wal_level, max_wal_senders).",
            validation: "wal_level.*replica|max_wal_senders|primary_conninfo",
          },
        },
        {
          id: "pg-rep-2",
          title: "Logical Replication",
          description: "Publications, subscriptions, and selective table replication.",
          duration: "12 min",
          videoId: "OvSzLjkMmQo",
          videoTitle: "PostgreSQL Logical Replication Guide",
          videoChannel: "High-Performance Programming",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Create a publication and subscription for logical replication of specific tables.",
            validation: "CREATE PUBLICATION|CREATE SUBSCRIPTION|FOR TABLE",
          },
        },
        {
          id: "pg-rep-3",
          title: "Failover & Patroni",
          description: "Automatic failover with Patroni, etcd, and HAProxy.",
          duration: "12 min",
          videoId: "RHwglGf_z40",
          videoTitle: "High Availability PostgreSQL with Patroni",
          videoChannel: "Techno Tim",
          hasTerminal: false,
        },
        {
          id: "pg-rep-4",
          title: "Connection Pooling (PgBouncer)",
          description: "PgBouncer configuration and connection management.",
          duration: "10 min",
          videoId: "ddKm7a7xOpk",
          videoTitle: "PgBouncer Tutorial",
          videoChannel: "High-Performance Programming",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a PgBouncer configuration for transaction-level pooling.",
            validation: "pool_mode.*transaction|max_client_conn|default_pool_size",
          },
        },
      ],
      project: {
        title: "HA PostgreSQL Setup",
        description: "Design and document a high-availability PostgreSQL architecture.",
        difficulty: "advanced",
        estimatedHours: 6,
        skills: ["Replication", "HA", "Patroni", "PgBouncer"],
      },
    },
    {
      id: "pg-extensions",
      title: "Extensions & Advanced Features",
      description: "PostGIS, pg_cron, partitioning, and the extension ecosystem.",
      icon: "Puzzle",
      trackId: "postgresql",
      order: 6,
      lessons: [
        {
          id: "pg-ext-1",
          title: "Table Partitioning",
          description: "Range, list, and hash partitioning for large tables.",
          duration: "12 min",
          videoId: "oJj-pltxBUM",
          videoTitle: "PostgreSQL Partitioning Tutorial",
          videoChannel: "High-Performance Programming",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Create a range-partitioned table by date with monthly partitions.",
            validation: "PARTITION BY RANGE|CREATE TABLE.*PARTITION OF|FOR VALUES FROM",
          },
        },
        {
          id: "pg-ext-2",
          title: "Full-Text Search",
          description: "tsvector, tsquery, and GIN indexes for text search.",
          duration: "12 min",
          videoId: "GRwIa-ce7RA",
          videoTitle: "Master Postgres Full-text Search in 5 Minutes",
          videoChannel: "Supabase",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Set up full-text search with tsvector, tsquery, and a GIN index.",
            validation: "tsvector|tsquery|to_tsvector|@@|GIN",
          },
        },
        {
          id: "pg-ext-3",
          title: "PostGIS & Geospatial",
          description: "Location-based queries with PostGIS extension.",
          duration: "12 min",
          videoId: "FKzw9HJ6XYA",
          videoTitle: "PostGIS Explained: The Spatial Database",
          videoChannel: "Matt Forrest",
          hasTerminal: false,
        },
        {
          id: "pg-ext-4",
          title: "Stored Procedures & Functions",
          description: "PL/pgSQL functions, triggers, and event triggers.",
          duration: "12 min",
          videoId: "7AsbMoJLA8I",
          videoTitle: "PostgreSQL Stored Procedures Explained",
          videoChannel: "Ruslan Brilenkov",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Create a PL/pgSQL trigger function that logs changes to an audit table.",
            validation: "CREATE FUNCTION|RETURNS TRIGGER|NEW|OLD|CREATE TRIGGER",
          },
        },
      ],
      project: {
        title: "PostgreSQL Feature Showcase",
        description: "Build a demo database utilizing partitioning, FTS, and triggers.",
        difficulty: "advanced",
        estimatedHours: 5,
        skills: ["Partitioning", "FTS", "PL/pgSQL", "Extensions"],
      },
    },
  ],
};
