import { Track } from "./types";

export const productManagerTrack: Track = {
  id: "product-manager",
  title: "Product Manager",
  description:
    "Learn to drive product strategy, discovery, and delivery. Master user research, roadmapping, prioritization, analytics, and cross-functional leadership to build products users love.",
  icon: "Target",
  color: "violet",
  category: "management",
  modules: [
    {
      id: "pm-foundations",
      title: "Product Management Foundations",
      description: "Core PM concepts, roles, and the product lifecycle.",
      icon: "BookOpen",
      trackId: "product-manager",
      order: 1,
      lessons: [
        {
          id: "pm-found-1",
          title: "What Is Product Management?",
          description: "The PM role, responsibilities, and how PM fits in an organization.",
          duration: "10 min",
          videoId: "4yQtEx7-NQs",
          videoTitle: "Intro to Product Management",
          videoChannel: "Product School",
          hasTerminal: false,
        },
        {
          id: "pm-found-2",
          title: "Product Lifecycle & Strategy",
          description: "From ideation to sunset — the full product lifecycle.",
          duration: "12 min",
          videoId: "bI48pbtMgKE",
          videoTitle: "Product Management 101: The Product Lifecycle",
          videoChannel: "Stanford Online",
          hasTerminal: false,
        },
        {
          id: "pm-found-3",
          title: "Product-Market Fit",
          description: "Identifying, measuring, and achieving product-market fit.",
          duration: "12 min",
          videoId: "0LNQxT9LvM0",
          videoTitle: "How To Find Product Market Fit",
          videoChannel: "Y Combinator",
          hasTerminal: false,
        },
        {
          id: "pm-found-4",
          title: "PM Frameworks & Mental Models",
          description: "Jobs-to-be-Done, RICE, Kano model, and other PM frameworks.",
          duration: "12 min",
          videoId: "vibwBA-29F4",
          videoTitle: "How to Use Mental Models in Your Product Role",
          videoChannel: "Product School",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Product Vision Document",
        description: "Write a product vision doc for a new product including target audience, competitive analysis, and positioning.",
        difficulty: "beginner",
        estimatedHours: 4,
        skills: ["Strategy", "Analysis", "Documentation"],
      },
    },
    {
      id: "pm-discovery",
      title: "Product Discovery & Research",
      description: "User research, interviews, surveys, and discovery techniques.",
      icon: "Search",
      trackId: "product-manager",
      order: 2,
      lessons: [
        {
          id: "pm-disc-1",
          title: "User Research Methods",
          description: "Qualitative and quantitative research approaches.",
          duration: "12 min",
          videoId: "BtKHHIBJnL8",
          videoTitle: "15 User Research Methods to Know",
          videoChannel: "NNgroup",
          hasTerminal: false,
        },
        {
          id: "pm-disc-2",
          title: "User Interviews & Surveys",
          description: "Conducting effective user interviews and designing surveys.",
          duration: "12 min",
          videoId: "z1iF1c8w5Lg",
          videoTitle: "How To Talk To Users",
          videoChannel: "Y Combinator",
          hasTerminal: false,
        },
        {
          id: "pm-disc-3",
          title: "Competitive Analysis",
          description: "Analyzing competitors, market landscape, and differentiation.",
          duration: "10 min",
          videoId: "UnBL8h8TVX8",
          videoTitle: "How to Do Competitive Analysis",
          videoChannel: "Product School",
          hasTerminal: false,
        },
        {
          id: "pm-disc-4",
          title: "Problem Framing & Opportunity Assessment",
          description: "Identifying the right problems to solve and sizing opportunities.",
          duration: "12 min",
          videoId: "4KG84YFR8Sc",
          videoTitle: "Problem Framing — The PM's Superpower",
          videoChannel: "Design Sprint Academy",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Discovery Sprint",
        description: "Run a mini discovery sprint: interview users, synthesize findings, and identify key opportunities.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["Research", "Interviews", "Synthesis"],
      },
    },
    {
      id: "pm-roadmap",
      title: "Roadmapping & Prioritization",
      description: "Building roadmaps, prioritizing features, and managing stakeholders.",
      icon: "Map",
      trackId: "product-manager",
      order: 3,
      lessons: [
        {
          id: "pm-road-1",
          title: "Product Roadmap Types",
          description: "Now/Next/Later, timeline-based, outcome-based, and opportunity roadmaps.",
          duration: "12 min",
          videoId: "KPwRprJNt8E",
          videoTitle: "What is a Product Roadmap?",
          videoChannel: "ProductPlan",
          hasTerminal: false,
        },
        {
          id: "pm-road-2",
          title: "Prioritization Frameworks",
          description: "RICE, MoSCoW, Value vs Effort, ICE, and weighted scoring.",
          duration: "15 min",
          videoId: "pzyRafZJ-0M",
          videoTitle: "What is the RICE Scoring Model?",
          videoChannel: "ProductPlan",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Implement a RICE scoring calculator that prioritizes a list of features by Reach, Impact, Confidence, and Effort.",
            validation: "reach|impact|confidence|effort|score|sort|priority",
          },
        },
        {
          id: "pm-road-3",
          title: "Stakeholder Management",
          description: "Aligning stakeholders, managing expectations, and communication.",
          duration: "10 min",
          videoId: "yfjRht9bXkE",
          videoTitle: "Managing Stakeholders as a PM",
          videoChannel: "Product School",
          hasTerminal: false,
        },
        {
          id: "pm-road-4",
          title: "OKRs & Goal Setting",
          description: "Objectives and Key Results for product teams.",
          duration: "10 min",
          videoId: "MV4UViKjJ34",
          videoTitle: "OKRs Explained",
          videoChannel: "What Matters",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Product Roadmap",
        description: "Create a 6-month product roadmap with prioritized features, OKRs, and dependency mapping.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["Roadmapping", "Prioritization", "OKRs"],
      },
    },
    {
      id: "pm-specs",
      title: "Product Specs & Requirements",
      description: "Writing PRDs, user stories, and acceptance criteria.",
      icon: "FileText",
      trackId: "product-manager",
      order: 4,
      lessons: [
        {
          id: "pm-spec-1",
          title: "Writing PRDs",
          description: "Structure and content of effective Product Requirements Documents.",
          duration: "15 min",
          videoId: "JJzODsXsCt0",
          videoTitle: "How to Write a Product Requirements Document",
          videoChannel: "HelloPM",
          hasTerminal: false,
        },
        {
          id: "pm-spec-2",
          title: "User Stories & Acceptance Criteria",
          description: "User story format, INVEST criteria, and writing clear acceptance criteria.",
          duration: "12 min",
          videoId: "q26147zlcMU",
          videoTitle: "User Stories and Acceptance Criteria Example",
          videoChannel: "The Business Analysis Doctor",
          hasTerminal: false,
        },
        {
          id: "pm-spec-3",
          title: "Wireframing & Prototyping for PMs",
          description: "Low-fidelity wireframes and prototyping to communicate ideas.",
          duration: "10 min",
          videoId: "urVHC-ReSV0",
          videoTitle: "Figma Wireframe Masterclass for Product Managers",
          videoChannel: "HelloPM",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Product Specification",
        description: "Write a complete PRD with user stories, acceptance criteria, and wireframes for a feature.",
        difficulty: "intermediate",
        estimatedHours: 4,
        skills: ["PRDs", "User Stories", "Wireframing"],
      },
    },
    {
      id: "pm-analytics",
      title: "Product Analytics & Metrics",
      description: "Data-driven product decisions with analytics and experimentation.",
      icon: "BarChart3",
      trackId: "product-manager",
      order: 5,
      lessons: [
        {
          id: "pm-anal-1",
          title: "Key Product Metrics",
          description: "North Star, AARRR, retention, engagement, and monetization metrics.",
          duration: "12 min",
          videoId: "iN_jeOAzoso",
          videoTitle: "Product Manager KPIs and Metrics",
          videoChannel: "Simplilearn",
          hasTerminal: false,
        },
        {
          id: "pm-anal-2",
          title: "Analytics Tools & Instrumentation",
          description: "Setting up tracking, event schemas, and analytics tools.",
          duration: "12 min",
          videoId: "QgSbWIrz__s",
          videoTitle: "How to Track and Analyze User Data",
          videoChannel: "Anthony Saltarelli",
          hasTerminal: false,
        },
        {
          id: "pm-anal-3",
          title: "A/B Testing & Experimentation",
          description: "Hypothesis testing, statistical significance, and experiment design.",
          duration: "15 min",
          videoId: "jEpwNaHjD68",
          videoTitle: "How To A/B Test a Product",
          videoChannel: "Exponent",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Calculate statistical significance for an A/B test given control and variant conversion rates.",
            validation: "z_score|p_value|significance|conversion|sample_size|control|variant",
          },
        },
        {
          id: "pm-anal-4",
          title: "Funnel Analysis & Cohorts",
          description: "Analyzing user funnels and cohort-based retention.",
          duration: "10 min",
          videoId: "n7sLeyicekA",
          videoTitle: "Funnel and Cohort Analysis",
          videoChannel: "Knownsense Labs",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Analytics Dashboard",
        description: "Design a product analytics dashboard with KPIs, funnels, and cohort charts.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["Analytics", "Metrics", "Experimentation"],
      },
    },
    {
      id: "pm-agile",
      title: "Agile & Delivery",
      description: "Working with engineering teams to ship products.",
      icon: "Zap",
      trackId: "product-manager",
      order: 6,
      lessons: [
        {
          id: "pm-agile-1",
          title: "Agile for PMs",
          description: "Scrum, Kanban, and how PMs work within agile frameworks.",
          duration: "12 min",
          videoId: "ihhNWV9vHX0",
          videoTitle: "Agile Project Management Explained in 10 Minutes",
          videoChannel: "Max Mao",
          hasTerminal: false,
        },
        {
          id: "pm-agile-2",
          title: "Sprint Planning & Refinement",
          description: "Backlog grooming, sprint planning, and estimation.",
          duration: "10 min",
          videoId: "jBUqRo0LgZ0",
          videoTitle: "The Power of Backlog Refinement",
          videoChannel: "Mountain Goat Software",
          hasTerminal: false,
        },
        {
          id: "pm-agile-3",
          title: "Working with Engineering",
          description: "Effective collaboration with engineering teams.",
          duration: "10 min",
          videoId: "-EIty2Um9A0",
          videoTitle: "Tips for PMs Working With Engineers",
          videoChannel: "Dianna Yau",
          hasTerminal: false,
        },
        {
          id: "pm-agile-4",
          title: "Launch Planning & GTM",
          description: "Planning launches, go-to-market strategy, and release management.",
          duration: "12 min",
          videoId: "KMVjS5HRHIk",
          videoTitle: "How To Create a Go-To-Market Strategy",
          videoChannel: "Dreamit",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Launch Plan",
        description: "Create a comprehensive launch plan for a product release including GTM strategy and success metrics.",
        difficulty: "intermediate",
        estimatedHours: 4,
        skills: ["Agile", "Launch Planning", "GTM"],
      },
    },
    {
      id: "pm-growth",
      title: "Growth & Monetization",
      description: "Growth strategies, pricing models, and monetization.",
      icon: "TrendingUp",
      trackId: "product-manager",
      order: 7,
      lessons: [
        {
          id: "pm-grow-1",
          title: "Growth Frameworks",
          description: "Growth loops, viral mechanics, and growth levers.",
          duration: "12 min",
          videoId: "UTmFuSZfJ9U",
          videoTitle: "Why Product-Led Growth is the Future",
          videoChannel: "Lenny's Podcast",
          hasTerminal: false,
        },
        {
          id: "pm-grow-2",
          title: "Pricing & Monetization Models",
          description: "Freemium, SaaS, usage-based, and marketplace pricing.",
          duration: "10 min",
          videoId: "A6veeCbKIzw",
          videoTitle: "The Art and Science of Pricing",
          videoChannel: "Lenny's Podcast",
          hasTerminal: false,
        },
        {
          id: "pm-grow-3",
          title: "Customer Retention & Engagement",
          description: "Reducing churn, increasing engagement, and loyalty programs.",
          duration: "10 min",
          videoId: "L4MUMc3usoQ",
          videoTitle: "5 Proven Customer Retention Strategies",
          videoChannel: "Customer Success Collective",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Growth Strategy",
        description: "Develop a growth strategy with acquisition channels, retention tactics, and pricing analysis.",
        difficulty: "advanced",
        estimatedHours: 5,
        skills: ["Growth", "Pricing", "Retention"],
      },
    },
    {
      id: "pm-leadership",
      title: "PM Leadership",
      description: "Leading without authority, influence, and career growth.",
      icon: "Crown",
      trackId: "product-manager",
      order: 8,
      lessons: [
        {
          id: "pm-lead-1",
          title: "Influence Without Authority",
          description: "Leading cross-functional teams as a PM.",
          duration: "10 min",
          videoId: "uhJA2s7wkFM",
          videoTitle: "Influence Without Authority",
          videoChannel: "Shreyas Doshi",
          hasTerminal: false,
        },
        {
          id: "pm-lead-2",
          title: "Executive Communication",
          description: "Presenting to leadership, board updates, and data storytelling.",
          duration: "10 min",
          videoId: "Fzi4T94QCjw",
          videoTitle: "5 Rules for Communicating with Executives",
          videoChannel: "Dr. Grace Lee",
          hasTerminal: false,
        },
        {
          id: "pm-lead-3",
          title: "PM Career Growth",
          description: "APM to VP Product — career paths and skill development.",
          duration: "10 min",
          videoId: "cnuF3su9-N4",
          videoTitle: "Product Manager Career Path: Climbing the PM Ladder",
          videoChannel: "Exponent",
          hasTerminal: false,
        },
      ],
      project: {
        title: "PM Portfolio",
        description: "Build a PM portfolio showcasing product thinking, case studies, and impact metrics.",
        difficulty: "advanced",
        estimatedHours: 6,
        skills: ["Leadership", "Communication", "Portfolio"],
      },
    },
  ],
};
