import { Track } from "./types";

export const softwareArchitectTrack: Track = {
  id: "software-architect",
  title: "Software Architect",
  description:
    "Design systems that scale, perform, and evolve. Master architectural patterns, distributed systems, cloud architecture, security, and technical decision-making.",
  icon: "Building2",
  color: "slate",
  category: "infrastructure",
  modules: [
    {
      id: "sa-foundations",
      title: "Architecture Foundations",
      description: "Core principles, trade-offs, and the architect's role.",
      icon: "BookOpen",
      trackId: "software-architect",
      order: 1,
      lessons: [
        {
          id: "sa-found-1",
          title: "What Is Software Architecture?",
          description: "Architecture vs design, the architect role, and architectural thinking.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "sa-found-2",
          title: "Quality Attributes & Trade-offs",
          description: "Performance, scalability, availability, security, and trade-off analysis.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "sa-found-3",
          title: "Architecture Decision Records (ADRs)",
          description: "Documenting decisions with context, consequences, and rationale.",
          duration: "10 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write an ADR in Markdown for choosing between monolith and microservices architecture.",
            validation: "## Status|## Context|## Decision|## Consequences|monolith|microservice",
          },
        },
        {
          id: "sa-found-4",
          title: "SOLID, DRY, KISS & YAGNI",
          description: "Foundational design principles and when to apply them.",
          duration: "10 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Architecture Review",
        description: "Conduct an architecture review of an existing system and write an assessment report.",
        difficulty: "beginner",
        estimatedHours: 4,
        skills: ["Analysis", "ADRs", "Communication"],
      },
    },
    {
      id: "sa-patterns",
      title: "Architectural Patterns",
      description: "Major architectural styles and when to use them.",
      icon: "LayoutGrid",
      trackId: "software-architect",
      order: 2,
      lessons: [
        {
          id: "sa-pat-1",
          title: "Monolithic Architecture",
          description: "Modular monoliths, benefits, and when monoliths are the right choice.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "sa-pat-2",
          title: "Microservices Architecture",
          description: "Service boundaries, communication patterns, and microservice trade-offs.",
          duration: "15 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Design a microservices architecture by defining service boundaries and APIs for an e-commerce system.",
            validation: "service|api|endpoint|catalog|order|payment|gateway",
          },
        },
        {
          id: "sa-pat-3",
          title: "Event-Driven Architecture",
          description: "Event sourcing, CQRS, message brokers, and event-driven patterns.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "sa-pat-4",
          title: "Serverless & FaaS Architecture",
          description: "Function-as-a-Service, event-driven serverless, and cold starts.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "sa-pat-5",
          title: "Hexagonal & Clean Architecture",
          description: "Ports & adapters, clean architecture, and domain-centric design.",
          duration: "12 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Implement a hexagonal architecture skeleton with domain, ports, and adapters layers in Python.",
            validation: "class.*Port|class.*Adapter|domain|port|adapter|interface",
          },
        },
      ],
      project: {
        title: "Architecture Comparison",
        description: "Compare 3 architectural approaches for a real use case with trade-off matrices.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["Patterns", "Trade-offs", "Documentation"],
      },
    },
    {
      id: "sa-distributed",
      title: "Distributed Systems",
      description: "CAP theorem, consensus, consistency, and distributed data.",
      icon: "Network",
      trackId: "software-architect",
      order: 3,
      lessons: [
        {
          id: "sa-dist-1",
          title: "CAP Theorem & Consistency Models",
          description: "Understanding CAP, eventual consistency, and strong consistency.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "sa-dist-2",
          title: "Consensus Algorithms (Raft, Paxos)",
          description: "How distributed systems agree on state.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "sa-dist-3",
          title: "Distributed Data Patterns",
          description: "Sharding, replication, partitioning, and data locality.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "sa-dist-4",
          title: "Service Mesh & Communication",
          description: "gRPC, REST, GraphQL, service mesh, and sidecar patterns.",
          duration: "12 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Implement a simple service discovery mechanism and health check system in Python.",
            validation: "register|discover|health|heartbeat|service|instance",
          },
        },
        {
          id: "sa-dist-5",
          title: "Saga Pattern & Distributed Transactions",
          description: "Orchestration vs choreography and compensating transactions.",
          duration: "12 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Distributed System Design",
        description: "Design a distributed system handling millions of requests with consistency guarantees.",
        difficulty: "advanced",
        estimatedHours: 8,
        skills: ["Distributed Systems", "CAP", "Data Patterns"],
      },
    },
    {
      id: "sa-cloud",
      title: "Cloud Architecture",
      description: "Designing for the cloud — AWS, Azure, GCP patterns.",
      icon: "Cloud",
      trackId: "software-architect",
      order: 4,
      lessons: [
        {
          id: "sa-cloud-1",
          title: "Cloud Design Patterns",
          description: "Circuit breaker, bulkhead, retry, throttling, and ambassador patterns.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "sa-cloud-2",
          title: "Multi-Tier & N-Tier Architectures",
          description: "Presentation, application, and data tiers in the cloud.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "sa-cloud-3",
          title: "Container Orchestration Architecture",
          description: "Kubernetes architecture, service mesh, and container patterns.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "sa-cloud-4",
          title: "Infrastructure as Code",
          description: "Terraform, Pulumi, CloudFormation, and IaC best practices.",
          duration: "12 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a Terraform module that defines a VPC with public/private subnets and an application load balancer.",
            validation: "resource|aws_vpc|aws_subnet|cidr_block|module|variable",
          },
        },
      ],
      project: {
        title: "Cloud Architecture Blueprint",
        description: "Create a cloud architecture blueprint for a SaaS platform with diagrams and IaC.",
        difficulty: "advanced",
        estimatedHours: 8,
        skills: ["Cloud", "IaC", "Kubernetes"],
      },
    },
    {
      id: "sa-scalability",
      title: "Scalability & Performance",
      description: "Designing systems that handle growth.",
      icon: "TrendingUp",
      trackId: "software-architect",
      order: 5,
      lessons: [
        {
          id: "sa-scale-1",
          title: "Horizontal vs Vertical Scaling",
          description: "Scaling strategies, auto-scaling, and capacity planning.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "sa-scale-2",
          title: "Caching Strategies",
          description: "Cache-aside, read-through, write-through, and cache invalidation.",
          duration: "12 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Implement a cache-aside pattern with TTL and LRU eviction in Python.",
            validation: "class Cache|get|set|ttl|evict|lru|capacity",
          },
        },
        {
          id: "sa-scale-3",
          title: "CDNs, Load Balancers & Edge Computing",
          description: "Content delivery, load balancing algorithms, and edge computing.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "sa-scale-4",
          title: "Database Scaling Patterns",
          description: "Read replicas, sharding, connection pooling, and query optimization.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "sa-scale-5",
          title: "Rate Limiting & Back Pressure",
          description: "Token bucket, sliding window, and back pressure mechanisms.",
          duration: "10 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Implement a token bucket rate limiter that handles burst traffic gracefully.",
            validation: "class.*RateLimiter|token|bucket|refill|allow|consume",
          },
        },
      ],
      project: {
        title: "Scale-Up Design",
        description: "Take a system handling 1K req/s and design it to handle 1M req/s with detailed scaling plan.",
        difficulty: "advanced",
        estimatedHours: 6,
        skills: ["Scaling", "Caching", "Performance"],
      },
    },
    {
      id: "sa-security",
      title: "Security Architecture",
      description: "Designing secure systems from the ground up.",
      icon: "Shield",
      trackId: "software-architect",
      order: 6,
      lessons: [
        {
          id: "sa-sec-1",
          title: "Threat Modeling",
          description: "STRIDE, attack trees, and systematic threat identification.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "sa-sec-2",
          title: "Authentication & Authorization Patterns",
          description: "OAuth 2.0, OIDC, RBAC, ABAC, and zero-trust architecture.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "sa-sec-3",
          title: "Data Protection & Encryption",
          description: "Encryption at rest, in transit, key management, and data classification.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "sa-sec-4",
          title: "API Security",
          description: "API gateways, rate limiting, input validation, and API security patterns.",
          duration: "10 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Security Architecture Review",
        description: "Perform a threat model and security architecture review for a sample application.",
        difficulty: "advanced",
        estimatedHours: 6,
        skills: ["Threat Modeling", "Security", "Authentication"],
      },
    },
    {
      id: "sa-reliability",
      title: "Reliability & Resilience",
      description: "Designing systems that stay up and recover gracefully.",
      icon: "HeartPulse",
      trackId: "software-architect",
      order: 7,
      lessons: [
        {
          id: "sa-rel-1",
          title: "Availability & SLAs/SLOs/SLIs",
          description: "Defining and measuring reliability with SLAs, SLOs, and SLIs.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "sa-rel-2",
          title: "Fault Tolerance Patterns",
          description: "Circuit breaker, bulkhead, timeout, retry, and fallback patterns.",
          duration: "15 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Implement a circuit breaker pattern with closed, open, and half-open states.",
            validation: "class.*CircuitBreaker|CLOSED|OPEN|HALF_OPEN|failure_count|threshold|state",
          },
        },
        {
          id: "sa-rel-3",
          title: "Chaos Engineering",
          description: "Chaos Monkey, fault injection, and building confidence in resilience.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "sa-rel-4",
          title: "Disaster Recovery & Business Continuity",
          description: "RPO, RTO, multi-region failover, and DR planning.",
          duration: "12 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Resilience Plan",
        description: "Design a resilience plan with fault tolerance, DR strategy, and chaos testing approach.",
        difficulty: "advanced",
        estimatedHours: 6,
        skills: ["Resilience", "SRE", "Disaster Recovery"],
      },
    },
    {
      id: "sa-system-design",
      title: "System Design Practice",
      description: "End-to-end system design interviews and real-world practice.",
      icon: "Presentation",
      trackId: "software-architect",
      order: 8,
      lessons: [
        {
          id: "sa-sd-1",
          title: "System Design Interview Framework",
          description: "The structured approach to system design problems.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "sa-sd-2",
          title: "Design a URL Shortener",
          description: "Classic system design: hashing, databases, caching, and analytics.",
          duration: "15 min",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Design and implement a URL shortener with base62 encoding and collision handling.",
            validation: "encode|decode|base62|shorten|expand|hash|url",
          },
        },
        {
          id: "sa-sd-3",
          title: "Design a Chat System",
          description: "Real-time messaging, WebSockets, message storage, and presence.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "sa-sd-4",
          title: "Design a Video Streaming Platform",
          description: "Upload pipeline, transcoding, CDN, and adaptive bitrate streaming.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "sa-sd-5",
          title: "Design a Distributed Cache",
          description: "Consistent hashing, replication, and cache cluster design.",
          duration: "15 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "System Design Portfolio",
        description: "Complete 3 end-to-end system designs with diagrams, trade-off analysis, and detailed write-ups.",
        difficulty: "advanced",
        estimatedHours: 10,
        skills: ["System Design", "Architecture", "Communication"],
      },
    },
    {
      id: "sa-evolution",
      title: "Architecture Evolution",
      description: "Evolving architectures, migration strategies, and modernization.",
      icon: "RefreshCw",
      trackId: "software-architect",
      order: 9,
      lessons: [
        {
          id: "sa-evo-1",
          title: "Strangler Fig Pattern",
          description: "Incrementally migrating from monolith to microservices.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "sa-evo-2",
          title: "API Versioning & Evolution",
          description: "Versioning strategies, backwards compatibility, and deprecation.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "sa-evo-3",
          title: "Technical Debt Management",
          description: "Identifying, quantifying, and strategically paying down tech debt.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "sa-evo-4",
          title: "Architecture Governance",
          description: "Fitness functions, tech radar, and governance without bureaucracy.",
          duration: "10 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Migration Strategy",
        description: "Design a migration strategy to modernize a legacy system with phased approach and risk mitigation.",
        difficulty: "advanced",
        estimatedHours: 6,
        skills: ["Migration", "Modernization", "Governance"],
      },
    },
  ],
};
