import { Track } from "./types";

export const technicalWriterTrack: Track = {
  id: "technical-writer",
  title: "Technical Writer",
  description:
    "Create clear, effective technical documentation. Master API docs, user guides, style guides, docs-as-code, and developer experience writing.",
  icon: "FileText",
  color: "orange",
  category: "design-writing",
  modules: [
    {
      id: "tw-foundations",
      title: "Technical Writing Foundations",
      description: "Core principles of effective technical communication.",
      icon: "BookOpen",
      trackId: "technical-writer",
      order: 1,
      lessons: [
        {
          id: "tw-found-1",
          title: "What is Technical Writing?",
          description: "The role, importance, and types of technical documentation.",
          duration: "10 min",
          videoId: "cxlVFHs6Gmc",
          videoTitle: "Google Technical Writing",
          videoChannel: "Google",
          hasTerminal: false,
        },
        {
          id: "tw-found-2",
          title: "Audience Analysis",
          description: "Understanding your readers and adjusting content accordingly.",
          duration: "10 min",
          videoId: "TXisTiNAWyE",
          videoTitle: "How I Write Technical Documents - Audience Analysis",
          videoChannel: "Amruta",
          hasTerminal: false,
        },
        {
          id: "tw-found-3",
          title: "Writing Clearly & Concisely",
          description: "Active voice, short sentences, and eliminating ambiguity.",
          duration: "12 min",
          videoId: "vT5pcc30Ffw",
          videoTitle: "Technical Writing Course for Beginners",
          videoChannel: "freeCodeCamp.org",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Rewrite the following passive voice sentences into active voice and simplify them.",
            validation: "rewrite|active|simplif",
          },
        },
        {
          id: "tw-found-4",
          title: "Structuring Technical Documents",
          description: "Headings, progressive disclosure, and scannable content.",
          duration: "10 min",
          videoId: "ro6Jspi9QqM",
          videoTitle: "An Introduction to Information Architecture",
          videoChannel: "Write The Docs",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Writing Improvement Exercise",
        description: "Take a poorly written technical document and rewrite it following best practices.",
        difficulty: "beginner",
        estimatedHours: 2,
        skills: ["Clear Writing", "Editing", "Structure"],
      },
    },
    {
      id: "tw-docs-types",
      title: "Types of Documentation",
      description: "Understanding different documentation formats and their purposes.",
      icon: "Files",
      trackId: "technical-writer",
      order: 2,
      lessons: [
        {
          id: "tw-type-1",
          title: "Tutorials & How-To Guides",
          description: "Writing step-by-step tutorials that guide users through tasks.",
          duration: "12 min",
          videoId: "d6Cs11AZqV4",
          videoTitle: "Writing technical documentation - tutorial with Confluence",
          videoChannel: "Christian Lempa",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a tutorial for setting up a Node.js project with steps, prerequisites, and expected output.",
            validation: "## Prerequisites|## Step|```|npm|node",
          },
        },
        {
          id: "tw-type-2",
          title: "Reference Documentation",
          description: "API references, configuration references, and technical specs.",
          duration: "12 min",
          videoId: "h_WsKO_NWuw",
          videoTitle: "Introduction: Documenting APIs",
          videoChannel: "Tom Johnson",
          hasTerminal: false,
        },
        {
          id: "tw-type-3",
          title: "Conceptual Documentation",
          description: "Explaining concepts, architecture, and mental models.",
          duration: "10 min",
          videoId: "og-M2hh42XE",
          videoTitle: "Documentation Isnt Just One Thing",
          videoChannel: "Document360",
          hasTerminal: false,
        },
        {
          id: "tw-type-4",
          title: "README Files",
          description: "Writing effective READMEs that help users get started quickly.",
          duration: "10 min",
          videoId: "O_XWkBCjj5U",
          videoTitle: "How to write Release Notes",
          videoChannel: "Learn Technical Writing with Rahul Karn",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a README.md for a sample project with installation, usage, API, and contributing sections.",
            validation: "# |## Installation|## Usage|## Contributing|```",
          },
        },
      ],
      project: {
        title: "Documentation Set",
        description: "Create a complete documentation set (tutorial + reference + conceptual) for a sample tool.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["Documentation Types", "Markdown", "Structure"],
      },
    },
    {
      id: "tw-api-docs",
      title: "API Documentation",
      description: "Write and generate excellent API documentation.",
      icon: "FileCode",
      trackId: "technical-writer",
      order: 3,
      lessons: [
        {
          id: "tw-api-1",
          title: "API Documentation Fundamentals",
          description: "Endpoints, parameters, responses, and examples.",
          duration: "12 min",
          videoId: "pRS9LRBgjYg",
          videoTitle: "REST API and OpenAPI",
          videoChannel: "IBM Technology",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write API documentation for a REST endpoint including method, path, parameters, and example response.",
            validation: "## |GET|POST|Parameters|Response|```json",
          },
        },
        {
          id: "tw-api-2",
          title: "OpenAPI / Swagger",
          description: "Writing OpenAPI specifications and generating docs.",
          duration: "15 min",
          videoId: "XNVo9WkCoak",
          videoTitle: "How to Create API Documentation in Postman",
          videoChannel: "Postman",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write an OpenAPI 3.0 specification for a users endpoint with GET and POST operations.",
            validation: "openapi|paths|/users|get|post|schema|responses",
          },
        },
        {
          id: "tw-api-3",
          title: "Code Samples & SDKs",
          description: "Writing effective code samples in multiple languages.",
          duration: "12 min",
          videoId: "sumQULczJOg",
          videoTitle: "Creating code samples for API/SDK documentation",
          videoChannel: "soap! technical communication",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write code samples for the same API call in Python, JavaScript, and cURL.",
            validation: "```python|```javascript|```bash|curl|requests|fetch",
          },
        },
        {
          id: "tw-api-4",
          title: "Authentication Documentation",
          description: "Documenting OAuth, API keys, and JWT authentication flows.",
          duration: "10 min",
          videoId: "ZV5yTm4pT8g",
          videoTitle: "OAuth 2 Explained In Simple Terms",
          videoChannel: "ByteByteGo",
          hasTerminal: false,
        },
      ],
      project: {
        title: "API Documentation Portal",
        description: "Create complete API docs for a REST API with OpenAPI spec and code samples.",
        difficulty: "intermediate",
        estimatedHours: 6,
        skills: ["API Docs", "OpenAPI", "Code Samples"],
      },
    },
    {
      id: "tw-tools",
      title: "Documentation Tools & Platforms",
      description: "Tools for writing, hosting, and managing documentation.",
      icon: "Wrench",
      trackId: "technical-writer",
      order: 4,
      lessons: [
        {
          id: "tw-tool-1",
          title: "Markdown & MDX",
          description: "Writing with Markdown and MDX for interactive docs.",
          duration: "12 min",
          videoId: "Z5sQHzKRxn8",
          videoTitle: "Docs-as-Code for Technical Writing",
          videoChannel: "AB Writing",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a Markdown document with headings, code blocks, tables, and admonitions.",
            validation: "# |```|\\||> |\\*\\*|---",
          },
        },
        {
          id: "tw-tool-2",
          title: "Static Site Generators (Docusaurus, MkDocs)",
          description: "Building documentation sites with SSGs.",
          duration: "15 min",
          videoId: "bSi9I_9OlzQ",
          videoTitle: "Docusaurus Vs Gitbook Vs Mkdocs",
          videoChannel: "Tobi Teaches",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Initialize a Docusaurus docs site and create a new documentation page.",
            validation: "npx|docusaurus|docs|sidebar|md",
          },
        },
        {
          id: "tw-tool-3",
          title: "Docs-as-Code Workflow",
          description: "Git-based workflows, PRs for docs, and CI/CD for documentation.",
          duration: "10 min",
          videoId: "urvM5nUArQ0",
          videoTitle: "Content Management Systems for Technical Writers",
          videoChannel: "AI for Career Success",
          hasTerminal: false,
        },
        {
          id: "tw-tool-4",
          title: "Diagramming (Mermaid, draw.io)",
          description: "Creating technical diagrams and architecture visuals.",
          duration: "10 min",
          videoId: "jCd6XfWLZsg",
          videoTitle: "Top 6 Tools to Turn Code into Beautiful Diagrams",
          videoChannel: "ByteByteGo",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Create a Mermaid sequence diagram showing an API request/response flow.",
            validation: "sequenceDiagram|participant|->|-->|->>",
          },
        },
      ],
      project: {
        title: "Documentation Site",
        description: "Build and deploy a documentation site for a project using Docusaurus or MkDocs.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["Docusaurus", "Markdown", "Docs-as-Code"],
      },
    },
    {
      id: "tw-style",
      title: "Style Guides & Standards",
      description: "Writing and maintaining style guides for consistency.",
      icon: "Ruler",
      trackId: "technical-writer",
      order: 5,
      lessons: [
        {
          id: "tw-style-1",
          title: "Industry Style Guides",
          description: "Google, Microsoft, and Apple developer style guides.",
          duration: "10 min",
          videoId: "ff2h22K4hqI",
          videoTitle: "Company style guide in technical writing",
          videoChannel: "AB Writing",
          hasTerminal: false,
        },
        {
          id: "tw-style-2",
          title: "Creating a Style Guide",
          description: "Terminology, voice & tone, formatting rules, and templates.",
          duration: "12 min",
          videoId: "r4ncgQ4U74Q",
          videoTitle: "How to write inclusive documentation",
          videoChannel: "Document360",
          hasTerminal: false,
        },
        {
          id: "tw-style-3",
          title: "Linting & Automation",
          description: "Vale, textlint, and automating style checks.",
          duration: "10 min",
          videoId: "CIwNjfTlmgA",
          videoTitle: "What Is Internationalization (I18N)",
          videoChannel: "Localization Academy",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Set up Vale with a custom style and run it on a documentation file.",
            validation: "vale|StylesPath|MinAlertLevel|BasedOnStyles",
          },
        },
      ],
      project: {
        title: "Team Style Guide",
        description: "Create a comprehensive style guide for a development team with automated linting.",
        difficulty: "intermediate",
        estimatedHours: 4,
        skills: ["Style Guides", "Vale", "Standards"],
      },
    },
    {
      id: "tw-devex",
      title: "Developer Experience (DevEx) Writing",
      description: "Writing for developer audiences — SDKs, CLIs, and onboarding.",
      icon: "Code",
      trackId: "technical-writer",
      order: 6,
      lessons: [
        {
          id: "tw-devex-1",
          title: "SDK Documentation",
          description: "Getting started guides, quickstarts, and SDK references.",
          duration: "12 min",
          videoId: "mRqoVlhtVzA",
          videoTitle: "The Secret Formula to Improve Developer Experience",
          videoChannel: "GitHub",
          hasTerminal: false,
        },
        {
          id: "tw-devex-2",
          title: "CLI Documentation",
          description: "Man pages, help text, and CLI reference docs.",
          duration: "10 min",
          videoId: "Kc_qR4hKVfA",
          videoTitle: "Guide for onboarding new developers to open source",
          videoChannel: "Jono Bacon",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a --help output and man page for a sample CLI tool.",
            validation: "Usage:|Options:|--help|DESCRIPTION|EXAMPLES",
          },
        },
        {
          id: "tw-devex-3",
          title: "Error Messages & Troubleshooting",
          description: "Writing helpful error messages and troubleshooting guides.",
          duration: "10 min",
          videoId: "WIdBdauqLUU",
          videoTitle: "Docs as Tests: Bringing Quality Assurance to Documentation",
          videoChannel: "WriteTechHub",
          hasTerminal: false,
        },
        {
          id: "tw-devex-4",
          title: "Changelog & Release Notes",
          description: "Writing clear changelogs and communicating breaking changes.",
          duration: "8 min",
          videoId: "yzeVMecydCE",
          videoTitle: "Complete Guide to Open Source - How to Contribute",
          videoChannel: "freeCodeCamp.org",
          hasTerminal: true,
          terminalExercise: {
            instructions: "Write a changelog entry following Keep a Changelog format with Added, Changed, and Fixed sections.",
            validation: "## \\[|### Added|### Changed|### Fixed|CHANGELOG",
          },
        },
      ],
      project: {
        title: "Developer Onboarding Docs",
        description: "Create a complete developer onboarding experience with quickstart and reference docs.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["DevEx", "SDK Docs", "Onboarding"],
      },
    },
    {
      id: "tw-career",
      title: "Technical Writing Career",
      description: "Building a portfolio and advancing in technical writing.",
      icon: "Briefcase",
      trackId: "technical-writer",
      order: 7,
      lessons: [
        {
          id: "tw-career-1",
          title: "Building a Technical Writing Portfolio",
          description: "Selecting samples, contributing to open source docs, and blogging.",
          duration: "10 min",
          videoId: "68ddwfpXHrE",
          videoTitle: "My Technical Writing Portfolio",
          videoChannel: "Amruta",
          hasTerminal: false,
        },
        {
          id: "tw-career-2",
          title: "Working with Engineers & Product Teams",
          description: "Collaboration workflows, information gathering, and review processes.",
          duration: "10 min",
          videoId: "_a1sjfBR6SU",
          videoTitle: "Common Technical Writer Interview Questions and Answers",
          videoChannel: "Technical Writer HQ",
          hasTerminal: false,
        },
        {
          id: "tw-career-3",
          title: "Measuring Documentation Quality",
          description: "Analytics, feedback loops, and continuous improvement.",
          duration: "8 min",
          videoId: "mpXL1inVJag",
          videoTitle: "How to Become a Freelance Technical Writer",
          videoChannel: "Alis Remote Vlogs",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Open Source Documentation Contribution",
        description: "Contribute documentation to an open source project and get it merged.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["Open Source", "Collaboration", "Portfolio"],
      },
    },
  ],
};
