import { Track } from "./types";

export const uxDesignTrack: Track = {
  id: "ux-design",
  title: "UX Designer",
  description:
    "Design intuitive, user-centered experiences. Master research, wireframing, prototyping, usability testing, and design systems.",
  icon: "Figma",
  color: "rose",
  category: "design-writing",
  modules: [
    {
      id: "ux-foundations",
      title: "UX Design Foundations",
      description: "Core principles, methodologies, and the UX design process.",
      icon: "BookOpen",
      trackId: "ux-design",
      order: 1,
      lessons: [
        {
          id: "ux-found-1",
          title: "What is UX Design?",
          description: "UX vs UI, the design thinking process, and the role of a UX designer.",
          duration: "10 min",
          videoId: "SRec90j6lTY",
          videoTitle: "UX Design Course",
          videoChannel: "freeCodeCamp",
          hasTerminal: false,
        },
        {
          id: "ux-found-2",
          title: "Design Thinking Framework",
          description: "Empathize, Define, Ideate, Prototype, Test — the 5 stages.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "ux-found-3",
          title: "UX Laws & Principles",
          description: "Hick's Law, Fitts' Law, Jakob's Law, and cognitive load.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "ux-found-4",
          title: "Accessibility (a11y) Fundamentals",
          description: "WCAG guidelines, screen readers, and inclusive design.",
          duration: "12 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "UX Audit",
        description: "Conduct a heuristic evaluation of an existing website using Nielsen's 10 heuristics.",
        difficulty: "beginner",
        estimatedHours: 3,
        skills: ["Heuristic Evaluation", "UX Principles"],
      },
    },
    {
      id: "ux-research",
      title: "User Research",
      description: "Methods for understanding users, their needs, and behaviors.",
      icon: "Users",
      trackId: "ux-design",
      order: 2,
      lessons: [
        {
          id: "ux-res-1",
          title: "Research Methods Overview",
          description: "Qualitative vs quantitative, generative vs evaluative research.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "ux-res-2",
          title: "User Interviews",
          description: "Planning, conducting, and analyzing user interviews.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "ux-res-3",
          title: "Surveys & Analytics",
          description: "Designing surveys and using analytics for quantitative insights.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "ux-res-4",
          title: "Personas & Journey Maps",
          description: "Creating user personas and mapping the user journey.",
          duration: "12 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "User Research Plan",
        description: "Design a complete research plan for a product including personas and journey maps.",
        difficulty: "beginner",
        estimatedHours: 4,
        skills: ["User Research", "Personas", "Journey Mapping"],
      },
    },
    {
      id: "ux-ia",
      title: "Information Architecture",
      description: "Organizing and structuring content for optimal user experiences.",
      icon: "FolderTree",
      trackId: "ux-design",
      order: 3,
      lessons: [
        {
          id: "ux-ia-1",
          title: "IA Fundamentals",
          description: "Organization schemes, labeling, and navigation design.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "ux-ia-2",
          title: "Card Sorting & Tree Testing",
          description: "Methods for validating information architecture.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "ux-ia-3",
          title: "Sitemaps & User Flows",
          description: "Creating sitemaps and documenting user task flows.",
          duration: "12 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Information Architecture Redesign",
        description: "Restructure the IA of an existing website based on card sorting results.",
        difficulty: "intermediate",
        estimatedHours: 4,
        skills: ["Information Architecture", "Card Sorting", "Sitemaps"],
      },
    },
    {
      id: "ux-wireframing",
      title: "Wireframing & Prototyping",
      description: "From sketches to interactive prototypes.",
      icon: "PenTool",
      trackId: "ux-design",
      order: 4,
      lessons: [
        {
          id: "ux-wire-1",
          title: "Sketching & Lo-Fi Wireframes",
          description: "Rapid ideation with sketches and low-fidelity wireframes.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "ux-wire-2",
          title: "Figma Fundamentals",
          description: "Frames, components, auto layout, and styles in Figma.",
          duration: "20 min",
          videoId: "kbZejnPXyLM",
          videoTitle: "Figma Tutorial for Beginners",
          videoChannel: "freeCodeCamp",
          hasTerminal: false,
        },
        {
          id: "ux-wire-3",
          title: "Hi-Fi Wireframes",
          description: "Creating detailed wireframes with real content and spacing.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "ux-wire-4",
          title: "Interactive Prototyping",
          description: "Adding interactions, transitions, and micro-animations in Figma.",
          duration: "15 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "App Prototype",
        description: "Design a complete app from lo-fi wireframes to interactive hi-fi prototype.",
        difficulty: "intermediate",
        estimatedHours: 6,
        skills: ["Figma", "Wireframing", "Prototyping"],
      },
    },
    {
      id: "ux-ui-design",
      title: "Visual & UI Design",
      description: "Color, typography, layout, and visual design principles.",
      icon: "Palette",
      trackId: "ux-design",
      order: 5,
      lessons: [
        {
          id: "ux-ui-1",
          title: "Color Theory & Palettes",
          description: "Color psychology, contrast ratios, and building palettes.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "ux-ui-2",
          title: "Typography",
          description: "Font selection, hierarchy, scale, and readability.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "ux-ui-3",
          title: "Layout & Grid Systems",
          description: "Grid-based design, spacing systems, and responsive layouts.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "ux-ui-4",
          title: "Iconography & Imagery",
          description: "Using icons, illustrations, and images effectively.",
          duration: "8 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "UI Style Guide",
        description: "Create a comprehensive UI style guide with colors, typography, and component specs.",
        difficulty: "intermediate",
        estimatedHours: 4,
        skills: ["Visual Design", "Color Theory", "Typography"],
      },
    },
    {
      id: "ux-design-systems",
      title: "Design Systems",
      description: "Building and maintaining scalable design systems.",
      icon: "Component",
      trackId: "ux-design",
      order: 6,
      lessons: [
        {
          id: "ux-ds-1",
          title: "Design System Fundamentals",
          description: "Tokens, components, patterns, and documentation.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "ux-ds-2",
          title: "Component Libraries in Figma",
          description: "Building reusable component libraries with variants.",
          duration: "15 min",
          hasTerminal: false,
        },
        {
          id: "ux-ds-3",
          title: "Design Handoff",
          description: "Developer handoff tools, specs, and collaboration.",
          duration: "10 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Mini Design System",
        description: "Build a design system with 10+ components, tokens, and documentation.",
        difficulty: "intermediate",
        estimatedHours: 6,
        skills: ["Design Systems", "Figma", "Documentation"],
      },
    },
    {
      id: "ux-testing",
      title: "Usability Testing",
      description: "Plan, conduct, and analyze usability tests.",
      icon: "ClipboardCheck",
      trackId: "ux-design",
      order: 7,
      lessons: [
        {
          id: "ux-test-1",
          title: "Usability Testing Methods",
          description: "Moderated, unmoderated, remote, and guerrilla testing.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "ux-test-2",
          title: "Writing Test Scripts",
          description: "Creating tasks, scenarios, and rating scales.",
          duration: "10 min",
          hasTerminal: false,
        },
        {
          id: "ux-test-3",
          title: "Analyzing & Reporting Results",
          description: "Synthesizing findings, severity ratings, and recommendations.",
          duration: "12 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Usability Test Report",
        description: "Conduct a usability test on a prototype and deliver a findings report.",
        difficulty: "intermediate",
        estimatedHours: 5,
        skills: ["Usability Testing", "Analysis", "Reporting"],
      },
    },
    {
      id: "ux-portfolio",
      title: "UX Portfolio & Career",
      description: "Build a portfolio and prepare for UX design roles.",
      icon: "Briefcase",
      trackId: "ux-design",
      order: 8,
      lessons: [
        {
          id: "ux-port-1",
          title: "Building Your UX Portfolio",
          description: "Case study structure, storytelling, and presentation.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "ux-port-2",
          title: "Writing UX Case Studies",
          description: "Problem, process, solution, and impact — the 4P framework.",
          duration: "12 min",
          hasTerminal: false,
        },
        {
          id: "ux-port-3",
          title: "UX Design Interviews",
          description: "Whiteboard challenges, portfolio presentations, and design critiques.",
          duration: "10 min",
          hasTerminal: false,
        },
      ],
      project: {
        title: "Portfolio Case Study",
        description: "Create a complete UX case study from research to final design.",
        difficulty: "intermediate",
        estimatedHours: 8,
        skills: ["Portfolio", "Case Study", "Storytelling"],
      },
    },
  ],
};
